### ISSUE TITLE
Python: empty outputModels[].result for generating complete models

### ISSUE THREAD

**Issue by zaytsevand** [asyncapi/modelina#1008]
#### Describe the bug
Empty models are generated by `PythonGenerator,` yet the spec is perfectly fine in AsyncAPI Studio (except for several warnings since I'm using a stripped-down version).

#### How to Reproduce
0. Tested for a version `1.0.0-next.29`
1. Try to generate complete models by a standard `PythonGenerator` with a standard preset for the following spec:
```
asyncapi: 2.5.0
info:
  title: ''
  version: ''
tags:
  - name: ''

channels:
  Ordering.Order.Created:
    description: ''
    publish:
      message:
        $ref: '#/components/messages/Ordering.OrderCreated'

components:
  messages:
    Ordering.OrderCreated:
      payload:
        $ref: '#/components/schemas/Ordering.Order'
  schemas:
    Ordering.Order:
      type: object
      required:
        - orderId
      properties:
        orderId:
          type: string
```
2. results will be a single model with a result equal to '\n\n'

#### Expected behavior
Based on AsyncAPI Studio, the models should not produce empty strings since they're rendered in the UI:
![image](https://user-images.githubusercontent.com/5207748/203600629-8b49590f-646a-4ddf-a294-44ca9400d98f.png)

**Comment by jonaslagoni** [comment]
@zaytsevand with version 1.1.1, the following is generated:

```
class OrderingDotOrder: 
  def __init__(self, input):
    self._orderId = input.orderId
    if hasattr(input, 'additionalProperties'):
        self._additionalProperties = input.additionalProperties

  @property
  def orderId(self):
        return self._orderId
  @orderId.setter
  def orderId(self, orderId):
        self._orderId = orderId

  @property
  def additionalProperties(self):
        return self._additionalProperties
  @additionalProperties.setter
  def additionalProperties(self, additionalProperties):
        self._additionalProperties = additionalProperties
```

Feel free to re-open if you are still experiencing problems.
