### ISSUE TITLE
Presets for additionalItems representations [RustGenerator]

### ISSUE THREAD

**Issue by leigh-johnson** [asyncapi/modelina#1018]
#### Describe the bug
RustGenerator is missing the `Eq` trait in the `#[derive]` block for an array of $ref objects, which results in the following compile error:

```
error[E0277]: can't compare `git_commit::GitCommit` with `git_commit::GitCommit`
  --> src/settings_reply.rs:13:5
   |
2  | #[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
   |                                                               ---------- in this derive macro expansion
...
13 |     git_history: Vec<crate::GitCommit>,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no implementation for `git_commit::GitCommit < git_commit::GitCommit` and `git_commit::GitCommit > git_commit::GitCommit`
```

#### How to Reproduce

1. Self-contained example below, full schema @ https://github.com/bitsy-ai/printnanny-asyncapi-schema/blob/40c6ff51eeae6a9b44f4b795c0e94100d706df11/2.4.0/printnanny-os.yml#L617
```
components:
  schema:
    GitCommit:
      name: GitHistory
      type: object
      properties:
        oid:
          type: string
        header:
          type: string
        message:
          type: string
        ts:
          type: integer
      required:
        - oid
        - header
        - message
        - ts
    SettingsReply:
      type: object
      additionalProperties: false
      properties:
        format:
          $ref: "#/components/schemas/SettingsFormat"
        filename:
          $ref: "#/components/schemas/SettingsFile"
        content:
          type: string
        head_git_commit:
          type: string
        git_history:
          type: array
          additionalItems: false
          items:
            $ref: "#/components/schemas/GitCommit"
```
2. Notice: `#[derive]` block is missing traits: `Eq` `Hash` `Ord` `PartialEq` `PartialOrd`

We probably want to make `Hash` an optional preset as well :thinking: 
```rust
// GitCommit represents a GitCommit model.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct GitCommit {
    #[serde(rename="oid")]
    oid: String,
    #[serde(rename="header")]
    header: String,
    #[serde(rename="message")]
    message: String,
    #[serde(rename="ts")]
    ts: i32,
    #[serde(rename="additionalProperties", skip_serializing_if = "Option::is_none")]
    additional_properties: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl GitCommit {
    pub fn new(oid: String, header: String, message: String, ts: i32, additional_properties: Option<std::collections::HashMap<String, serde_json::Value>>) -> GitCommit {
        GitCommit {
            oid,
            header,
            message,
            ts,
            additional_properties,
        }
    }
}
```

#### Expected behavior

The example above should render:
```rust
// GitCommit represents a GitCommit model.
#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
pub struct GitCommit {
    #[serde(rename="oid")]
    oid: String,
    #[serde(rename="header")]
    header: String,
    #[serde(rename="message")]
    message: String,
    #[serde(rename="ts")]
    ts: i32,
    #[serde(rename="additionalProperties", skip_serializing_if = "Option::is_none")]
    additional_properties: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl GitCommit {
    pub fn new(oid: String, header: String, message: String, ts: i32, additional_properties: Option<std::collections::HashMap<String, serde_json::Value>>) -> GitCommit {
        GitCommit {
            oid,
            header,
            message,
            ts,
            additional_properties,
        }
    }
}
```

**Comment by leigh-johnson** [comment]
Ah ok, I see what's happening here:

1. When `additionalProperties: true` is set (this is the default), a model is generated to accept an optional hashmap of `HashMap<String, serde_json::Value>`

2. However, there is no standard implementation for `Ord` `PartialOrd` `Hash` for a `HashMap` 

We need to break this up into two new presets:

### AdditionalItemsHashMap preset

This is the preset you would use with very simple `additionalItems` data structures, where the data structure's hierarchy is mostly flat OR the lookup key is known ahead of time to achieve O(1). 


- [ ] Ord` implementation that orders lexicographically/numerically and enforces a `string` or `number`  map key (just as a first step here). 

Note that sorting a HashMap will be `O(n * log(n))` complexity. If you need efficient 
sorting/traversal for the data structures in `additionaltems`, see `AdditionalItemsBTreeMap`

- [ ] Do not derive `Hash` trait for now

### AdditionalItemsBTreeMap preset

This is the preset you would use with an arbitrarily nested `additionalItems` data structure, where traversal time matters and the speed of operations like `Ord` and `PartialOrd` needs to be optimized. Sort and range selection operations on a Btree are O(log(n)).

For now, we're assuming `serde_json::Value` is the heterogenous type for key/value data structures. (but if you're reading this and use a different `serde` representation or a different serialization framework, please comment!)

**Comment by jonaslagoni** [comment]
Just providing some background info here.

> When additionalProperties: true is set (this is the default), a model is generated to accept an optional hashmap of HashMap<String, serde_json::Value>

That is the JSON Schema interpreter's way of saying the creator of the schema wants the object to be extended with properties that the end user themself can decide the keys of, they just have follow a specific data type. This is reflected by adding a property with type `ConstrainedDictionaryModel` that has the serialization type `unwrap`, which is the abstracted way of saying all entries in that dictionary, need to be serialized alongside the core properties within the same JSON object, i.e. `{"coreProperty": ..., "customProperty": ...}`

It's entirely fine for now to say those types of properties are not currently supported, until there is a better way to represent them.

For example this is what the Jackson preset for Java does (https://github.com/asyncapi/modelina/blob/109a553e09384f635f1eb7fbbd7b79910e76af89/src/generators/java/presets/JacksonPreset.ts#L16), as such a functionality is not supported by the library, so the property is simply not annotated once encountered.

If you just want to add the possibility for the user to choose between two types, you can add it as a simple option 🙂

**Comment by jonaslagoni** [comment]
Gonna remove this from the v1 roadmap, if this change does contain a breaking change, then we can always do it for v2 🙂

**Comment by AnimeshKumar923** [comment]
still valid? @jonaslagoni
