### ISSUE TITLE
Implement Display or ToString trait for enums [RustGenerator]

### ISSUE THREAD

**Issue by leigh-johnson** [asyncapi/modelina#1029]
#### Reason/Context

Rust enums are missing a `ToString` or `Display` implementation.

The OpenAPI client implements just `ToString`, but it's wiser to implement `Display` here. You also get `ToString` by implementing the `Display` trait.

This is needed to:

- Format enum using the default Display formatter (instead of Debug formatter, so `"{}" vs "{:#}")
- Infer a Rust enum variant from a string value

#### Description
Please try answering a few of those questions
- Update the default Enum preset for RustGenerator
- This is not a breaking change

#### Docs/References

https://doc.rust-lang.org/std/fmt/trait.Display.html

https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/rust/model.mustache#L20

**Comment by jonaslagoni** [comment]
Would highly recommend adding this through presets instead of through the default enum preset 🙂 

Here is how we do it for Java, through the CommonPreset, where you can make the model include `toString`, hashcode, etc.

This is to allow the user to choose between having the models include it, not, or through a custom implementation 🙂

**Comment by leigh-johnson** [comment]
> Would highly recommend adding this through presets instead of through the default enum preset slightly_smiling_face
> 
> Here is how we do it for Java, through the CommonPreset, where you can make the model include `toString`, hashcode, etc.
> 
> This is to allow the user to choose between having the models include it, not, or through a custom implementation slightly_smiling_face

Can you compose multiple Presets together? I'm looking at the Java and other implementations with Presets, and it seems like 1 Preset is used at a time.

https://github.com/asyncapi/modelina/blob/master/src/generators/java/JavaPreset.ts

Let's say `impl Display` and `impl Default` are implemented as two separate Enum presets; how would I use both?

**Comment by leigh-johnson** [comment]
I think the right place to implement this is as an option here, adding an `implementDisplay: boolean` option.

https://github.com/asyncapi/modelina/blob/next/src/generators/rust/presets/CommonPreset.ts#L8

Which is then used to render additional content here:
https://github.com/asyncapi/modelina/blob/next/src/generators/rust/presets/CommonPreset.ts#L96

**Comment by jonaslagoni** [comment]
> Let's say impl Display and impl Default are implemented as two separate Enum presets; how would I use both?

That's the neat thing, they are placed in sequence. So you can add as many as you would like:

```
const generator = new JavaGenerator({
  presets: [
    JAVA_CONSTRAINTS_PRESET,
    {
      preset: JAVA_COMMON_PRESET,
      options: {
        equal: true,
        hashCode: true
      },
    },
  ],
});
```

Which would first apply the `JAVA_CONSTRAINTS_PRESET` and next render the `JAVA_COMMON_PRESET` 🙂

**Comment by jonaslagoni** [comment]
> I think the right place to implement this is as an option here, adding an implementDisplay: boolean option.

That is definitely also an option 👍 

We haven't really figured out the "right" way to separate the logic in presets, cause it kinda depends on preference 🤷 You can place everything within one preset with a bunch of options, or layer them in a more compact single responsibility preset.

**Comment by jonaslagoni** [comment]
I dont see this as a blocker for releasing v1, removing it from the milestone. Do ping me if you disagree 😊
