### ISSUE TITLE
Python Pydantic improvements

### ISSUE THREAD

**Issue by zaytsevand** [asyncapi/modelina#1058]
##### Field.alias
It seems that for Pydantic `Field` typing use of `property.description` as an `alias` is incorrect, and `property.name` or some other field should be used instead. Current implementation:
```typescript
const PYTHON_PYDANTIC_CLASS_PRESET: ClassPresetType<PythonOptions> = {
  property(params) {
    const type = params.property.required
      ? params.property.property.type
      : `Optional[${params.property.property.type}]`;
    const alias = params.property.property.originalInput['description']
      ? `alias='${params.property.property.originalInput['description']}'`
      : '';

    return `${params.property.propertyName}: ${type} = Field(${alias})`;
  }
};
```
Possible fix:
```typescript
    const alias = params.property.property.originalInput['name']
      ? `alias='${params.property.property.originalInput['name']}'`
      : '';
```
##### Field.description
Introduce support for setting a Field's `description` from `property.description`

##### Extra.forbid
For models declaring `additionalProperties` as false enable native validation:
```python
from pydantic import BaseModel, Extra


class Model(BaseModel, extra=Extra.forbid):
    a: str
```

#### Description
- Change from `description` to `name` when setting `Field.alias` will be a breaking change, but it's more of a misuse or a bug in the current state.

**Comment by jonaslagoni** [comment]
I might be wrong, but is it the .originalPropertyName you are looking for here? 🧐

**Comment by dimitern** [comment]
There is another problem here: if the description used for the alias is a multi-line string containing single quotes, it will result in generating *broken* code:

```python
class Model(BaseModel):
    a: str = Field(alias='Single-line description is fine')
    b: str = Field(alias='Unless it contains ' in it - that breaks the code')  # unescaped ' in the string
    c: str = Field(alias='It is even worse
    for a mult-line strings
    here ' breaks it also
    ')
```

I believe the fix will be to use triple quotes for the `alias=...` value generated, that way no escaping is needed, and multi-line strings are also fine and work better with syntax-highlighting in IDEs:

```python
class Model(BaseModel):
    a: str = Field(alias='''Single-line description is fine''')
    b: str = Field(alias='''Contains ' in it - no longer breaks the code''')
    c: str = Field(alias='''It is better
    for a mult-line strings
    here ' or " do not break it
    ''')
```
