### ISSUE TITLE
Interfaces are not being documented via JSdoc

### ISSUE THREAD

**Issue by smoya** [asyncapi/modelina#106]
#### Describe the bug

Our current flow for generating docs is first transpile TypeScript to Javascript, then run `jsdoc2md` to generate the final Markdown file. See https://github.com/asyncapi/generator-model-sdk/blob/master/package.json#L62.

Documenting interfaces in jsdoc is totally possible thanks to the `@interface` tag. However, the tag is not supported by TS compiler. See https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html.

That means we cannot generate documentation for interfaces later on with `jsdoc2md` as those tags are not added ever.

#### Expected behavior
We somehow generate documentation for interfaces.

I would suggest we re-evaluate the current flow so we can either:

1. Generate the docs directly from TS:
    - https://github.com/microsoft/tsdoc (Standard, but I think it's WIP)
    - http://typedoc.org/
2. Rather we transpile using an alternative like https://github.com/SoftwareBrothers/better-docs#how-it-works

**Comment by jonaslagoni** [comment]
@all-contributors please add @smoya for bug

**Comment by jonaslagoni** [comment]
Still relevant

**Comment by smoya** [comment]
Still relevant imho cc @jonaslagoni

**Comment by smoya** [comment]
relevant

**Comment by smoya** [comment]
Old, but still relevant
