### ISSUE TITLE
Python Dataclasses supported for Modelina

### ISSUE THREAD

**Issue by indy-jonesy** [asyncapi/modelina#1070]
#### Reason/Context
Please try answering few of those questions
- Why we need this improvement?
- Dataclasses are the native object type used by Python
- How will this change help?
- Opens up broader support of Python outside of pydantic which is an external package (and appears to be what is currently supported)
- What is the motivation? 
- Ease of integration with existing core Python objects

#### Description
Please try answering few of those questions
- What changes have to be introduced?
- Support for having AsyncAPI YAML spec be able to support the code model for Python
- Will this be a breaking change?
- I don't believe so.
- How could it be implemented/designed?
- Probably piggyback off some of the current implementation of Python-Modelina support.

**Comment by jonaslagoni** [comment]
Thanks for raising the feature request @dis-olsby. Can you give an example of how such a class might look like with the data class support?

**Comment by AnimeshKumar923** [comment]
@jonaslagoni is this still valid?

_PS: I'm serving as a reminder :grin:_
