### ISSUE TITLE
Add support for Kotlin

### ISSUE THREAD

**Issue by LouisXhaferi** [asyncapi/modelina#1073]
#### Reason/Context
Kotlin is the standard language used for Android Development as well as an emerging language in Backend Development, especially using Frameworks like Spring Boot, Ktor or Quarkus.
Implementing a generator for Kotlin would enable users of modelina to generate models for all clients and servers using Kotlin.

Personally I've got a C++ application and a Kotlin Microservice that need to communicate asynchronously, so automatically generating models would be great.
As I noticed there's an active PR about C++ already.

#### Description
Adding support would require adding a generator for Kotlin.
Since there is also support for Java, maybe some of the code can be reused, since Kotlin and Java share the same platform after all.
If so, there would probably also be some refactoring to be done, so we eliminate duplicated code.

#### Tech Notes
Of course the main goal is to get it up and running and then optimize, but there are some goals that would be desirable to also reach at implementation.

**Must have:**
- Immutability by using Kotlin [Data classes](https://kotlinlang.org/docs/data-classes.html)
- Less boxing, by using [Inline Classes](https://kotlinlang.org/docs/inline-classes.html) where possible
- Dockerized Compilation Tests

**Nice to have:**
- Support for common JSON Serializers (Java Generator does this already)
- Implementing Unions via Sealed Interfaces

**Comment by LouisXhaferi** [comment]
### Note:
If the feature request is approved, I'm open to implementing it myself.
It might take some time and help since my knowledge of TypeScript is limited, but I think that there's enough reference material to get it done. 💃🏻

**Comment by jonaslagoni** [comment]
Hey @LouisXhaferi definitely sounds like a good feature!

We created a guide for how to create new generators, which you can find here: https://github.com/asyncapi/modelina/blob/next/docs/contributing.md#adding-a-new-generator

But it seems you are already there 🔥

Feel free to create a draft PR even if it's not finished, easier for me to help out if and for you to ask questions 👍

**Comment by LouisXhaferi** [comment]
Thanks for the Feedback @jonaslagoni!

Yes, I've been going for a couple of hours and so far I've been making surprisingly good progress, but I've yet to formally test anything 🤣
I've got working examples though, so that's a good start.

I'll open a draft PR as soon as I get into "tested" territory.

**Comment by jonaslagoni** [comment]
Feel free to do it before hand as well, you can mark it as a draft, so its WIP, but of course entirely up to you ✌️

Looking forward to it!

**Comment by LouisXhaferi** [comment]
@jonaslagoni should the bot have picked this up and closed it?

**Comment by jonaslagoni** [comment]
Technically the bot dont close it before released on `master`, I just manually close them to stay sane 😅
