### ISSUE TITLE
Java Generator can't generate typed arrays

### ISSUE THREAD

**Issue by LouisXhaferi** [asyncapi/modelina#1076]
#### Describe the bug
When generating Java models from a schema containing an array of a certain type, like for example 'number' or 'string', the generated model shows type of `Object[]` or `List<Object>`.

#### How to Reproduce
Generate Java Model from schema containing any typed array.

```js
const trainingSchema = {
  $schema: 'http://json-schema.org/draft-07/schema#',
  $id: 'Trainings',
  type: 'object',
  additionalProperties: false,
  properties: {
    trainingMinutes: {
      type: 'array',
      items: {
        type: 'number'
      }
    }
  }
};

const generator = new JavaGenerator();
export async function generate() : Promise<void> {
  const models = await generator.generate(trainingSchema);
  for (const model of models) {
    console.log(model.result);
  }
}
if (require.main === module) {
  generate();
}
```
Returns 

```java
public class Trainings {
  private Object[] trainingMinutes;

  public Object[] getTrainingMinutes() { return this.trainingMinutes; }
  public void setTrainingMinutes(Object[] trainingMinutes) { this.trainingMinutes = trainingMinutes; }
}

```

#### Expected behavior
Generated Java code should map the type of the array and generate a proper Array or List-Type where possible.
For the example above the proper outputs would have been: `int[]` and `List<Integer`,

so there correct output here would have been

```java
public class Trainings {
  private int[] trainingMinutes;

  public int[] getTrainingMinutes() { return this.trainingMinutes; }
  public void setTrainingMinutes(int[] trainingMinutes) { this.trainingMinutes = trainingMinutes; }
}
```

**Comment by LouisXhaferi** [comment]
I ran into the same problem when testing my Kotlin Generator.
When testing the type mapping directly, it of course works well, when you provide the unit test with a `ConstrainedArrayModel` that already has the correct Kotlin/Java/etc type in it's `valueModel.type`.

While debugging `ConstraintHelpers.constrainArrayModel` I noticed that with a context looking like this:
![image](https://user-images.githubusercontent.com/52397677/211038880-ef86cf68-23f4-4f47-beb9-44f0be24c776.png)

We get a constrained model looking like this:
![image](https://user-images.githubusercontent.com/52397677/211039093-c97a905d-63ab-4af4-8433-0d2e342c1ff7.png)

You can see that in `context.metamodel.originalInput` it's still the correct type. An `array` with `integer` items.
If you compare this to the `DictionaryModel`, which already has additional `MetaModel`-S `key`and `value`, this makes me think that `ArrayModel` has got to be extended by another property describing a parsed/resolved type.

This should be done in `CommonModelToMetaModel` and can be done analogously `CommonModelToMetaModel.convertToDictionaryModel`
https://github.com/asyncapi/modelina/blob/9e3a823dd7ccd5f206f1028277189291a51f56b3/src/helpers/CommonModelToMetaModel.ts#L235-L243

Since there already is an implementation for `convertToArrayModel`, I suspect the bug is in that method.

**Comment by jonaslagoni** [comment]
There is some other issues where this is also discussed, i am just on my phone and cant search and find it. 

This is related to additionalItems being true by default in json schema 😄 If you set this to false for your array, you should no longer have this problem.

**Comment by LouisXhaferi** [comment]
Thanks for the feedback!

If this is how it is supposed to be, it's fine for now.
However it is still somewhat counter-intuitive to have set a specific single specific type in your schema and to receive a practically untyped equivalent in response.

**Comment by jonaslagoni** [comment]
Its not thats its entirely unrelated type, its just a union type, of the type you defined and what is allowed by the additionalItems. 

However in Java we dont have a union type (yet).. so you only get this generic type, because its the best possible outcome.

**Comment by jonaslagoni** [comment]
But i think we need better docs for this as well as options to disable it.

**Comment by LouisXhaferi** [comment]
Yeah I understood that it wasn't really a "problem" with the Java generator when I debugged it back to the `Interpreter.ts` file. At that point it would have helped to have read the JSON Schema docs. 🤣

The whole union thing is a weird one for Java for sure, but thankfully there are good solutions for it, now that we have sealed interfaces. 

But since this is a relatively new feature, the following questions comes to mind: 
Are there any plans on supporting different versions of the same language?
If so: cool
If not: I'm sure that somebody thought about it already, but trying to use newer/idiotmatic langauge features and support the newest versions of languages is going to get harder without breaking clients using older language versions.

**Comment by jonaslagoni** [comment]
Union issue for Java can be found here: https://github.com/asyncapi/modelina/issues/391

> Are there any plans on supporting different versions of the same language?
> If so: cool

There are definitely no restrictions to not supporting it 👍 It can also be conditional rendering of unions as sealed interfaces or custom class as the issue highlight. The same way we have for class and interface in TypeScript https://github.com/asyncapi/modelina/blob/9e3a823dd7ccd5f206f1028277189291a51f56b3/src/generators/typescript/TypeScriptGenerator.ts#L126
