### ISSUE TITLE
Kotlin Blackbox tests don't run on Github Windows Runner

### ISSUE THREAD

**Issue by LouisXhaferi** [asyncapi/modelina#1080]
#### Describe the bug
The Kotlin blackbox tests for windows currently don't run as part of the pipeline. This is due to the windows runner image using the  Kotlin Native compiler, instead of the Kotlin JVM compiler.

#### Expected behavior
Find out and fix the runner, so that it uses Kotlin JVM, so that we can reactivate the blackbox tests for windows.

**Comment by AnimeshKumar923** [comment]
@jonaslagoni is this still valid?
many issues are being closed...not enough contributors @jonaslagoni ? :eyes: 
_PS: I'm serving as a reminder 😁_
