### ISSUE TITLE
JSON Schema interpreter opens up closed structures

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#1086]
#### Describe the bug

This issue originates from https://github.com/asyncapi/modelina/issues/248, but this is a rewrite of what was figured out.

Given a JSON Schema such as the following:
```
{
  "type": "object",
  "properties": {
    "name": { "type": "string", "enum": ["test"] },
    "credit_card": { "type": "number" }
  },
  "dependencies": {
    "credit_card": {
      "properties": {
        "name": { "enum": ["test", "test2"] }
      },
    }
  }
}
```

Currently opens up the enum types of the property `name`. Meaning that an enum value for both `test` and `test2` will be present.

For example for typescript this will be:
```
enum ReservedName {
  TEST = "test",
  TEST2 = "test2",
}
```

But the thing is that only the following data is allowed:
```
{
  "name": "test",
  "credit_card": 2
}
```
`test2` will never be an accepted value based on that JSON Schema.

That means that nested interpretations cannot open up a current restricted structure (i.e. include the new `test2`) - but it can restrict it further in some cases, i.e. add structure such as if this was the case, that the property `name` was by default an arbitrary string:
```
{
  "type": "object",
  "properties": {
    "name": { "type": "string" },
    "credit_card": { "type": "number" }
  },
  "dependencies": {
    "credit_card": {
      "properties": {
        "name": { "enum": ["test", "test2"] }
      },
    }
  }
}
```

Should generate a union of types for `name` to be both `string` or one of the enum values.

**Comment by AnimeshKumar923** [comment]
@jonaslagoni is this still valid?

_PS: I'm serving as a reminder 😁_
