### ISSUE TITLE
[📑 Docs]: How to use modelina could be clearer

### ISSUE THREAD

**Issue by lcc** [asyncapi/modelina#1089]
### What Dev Docs changes are you proposing?

First of all, thanks for the amazing project. IMHO modelina should provide a CLI-like interface which accepts, at least, two arguments (1) the filepath for the input documentation and (2) the desired language as IMO it would make adoption of the tool much easier. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jonaslagoni** [comment]
Thanks for the issue @lcc, we actually do have it, but I see we don't have it specified anywhere in Modelina 🧐 

You can use the [AsyncAPI CLI](https://github.com/asyncapi/cli#usage) `asyncapi generate models typescript ./asyncapi.json`.

Would you like to provide the improved documentation for it?

**Comment by lcc** [comment]
@jonaslagoni no need for a separate tool! Great I am going to take a look at it!

> Would you like to provide the improved documentation for it?

Sure, I will take a look at this later in the day, thanks for the prompt response.

**Comment by rukundob451** [comment]
@jonaslagoni anything to this yet?

**Comment by jonaslagoni** [comment]
This has been improved a bit since this issue, unless @lcc gets back with more specifics what is missing, nothing else to do here I think 🙂 

Closing as I am cleaning up issues.

Feel free to re-open if new information come to light.
