### ISSUE TITLE
Major version release cadense

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#1107]
#### Reason/Context
How often should we aim to release a major version? 

I would suggest we do it quarterly, the same as the specification, January, April, June, and September.

it doesn't necessarily mean we will release a major version, but that's the window to keep the `next` branch alive before syncing with `master`.

Of course, major versions are still released slowly as PRs are merged, using the `next` pre-release tags.

**Comment by jonaslagoni** [comment]
Tagging code owners for visibility and in-case you have an opinion about it 🙂 

@magicmatatjahu @ron-debajyoti @Samridhi-98 @leigh-johnson @LouisXhaferi

**Comment by magicmatatjahu** [comment]
We can do majors every quarter, but only if there are breaking changes (like in spec) :)

**Comment by jonaslagoni** [comment]
@magicmatatjahu yea exactly, its just to bundle multiple breaking changes together within a decent timeframe.

**Comment by LouisXhaferi** [comment]
> We can do majors every quarter, but only if there are breaking changes (like in spec) :)

Sounds like a good idea!

**Comment by jonaslagoni** [comment]
Alright with no objections for two weeks, lets just go with it for the time being and re-access if necessary later on 🙂
