### ISSUE TITLE
Typescript generate to files: no auto dependancy import

### ISSUE THREAD

**Issue by tbilbe** [asyncapi/modelina#1122]
#### Describe the bug
When generating typescript model files from the generateToFiles method. The output-model files do not include an import statement for dependant types.

`import X from './X' // this is missing in the types file causing errors`

The bug is present when using the property `additionalItems: boolean` on an array, which I would expect to constrain the array to only the specified type. Without this property the import statement appears however the generated type definition includes `any` and looses the type safety seen in the image below:

<img width="382" alt="image" src="https://user-images.githubusercontent.com/26323783/216631069-6e5cea2c-e9e0-4866-ba1d-751489bbb943.png">

#### Github repo To Reproduce Bug
https://github.com/tbilbe/modelina-test

#### How to Reproduce
1. create model schema in json files - using the `$ref` to use external schemas inside type
2. model schema includes type array of 1 type and has `additionalItems: false` to constrain array to that specific type
3. run modelina generateToFiles and output them in seperate files using `pnpx tsx generate-types.ts`

#### Expected behaviour

I would expect that including the additionalItems flag with false would constrain the array type and the generator would understand how to append the dependancy in the type.

**Comment by jonaslagoni** [comment]
Yea, definitely seem like a bug, taking a look at it.

**Comment by jonaslagoni** [comment]
@tbilbe take it for a spin, otherwise feel free to reopen the issue 🙂

**Comment by tbilbe** [comment]
World class 🎖️! thanks for the rapid response and update 👍🏽
