### ISSUE TITLE
Add Python JSON serialization preset

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#1130]
> **fair warning**! As a good first issue this is a bit beefy, but it's "well" described and we have quite a comprehensive documentation and reference implementations, and we are always ready to help!

#### Reason/Context
Modelina often dont render the properties how they are expected to be rendered in JSON. Therefore, it needs a preset that adds support for it in, some libraries, or custom implementations, there is no preference here.

For example, I am looking for something similar to a `to_json` function, similar to this:

```python
    def to_json(self):
        to_return = {"version": self.version, "type": self.type}
        image_boxes = {}
        for key, boxes in self.bboxes.items():
            jboxes = []
            for box in boxes:
                jboxes.append(box.__dict__)
            image_boxes[key] = jboxes

        to_return["boundingBoxes"] = image_boxes
        return to_return
```

> Method 5, from https://changsin.medium.com/how-to-serialize-a-class-object-to-json-in-python-849697a0cd3

That will map the class properties to its JSON representation. The same is needed for a `from_json` function. Although I don't have much information here.

#### Description

You can find information about how to add presets here: https://github.com/asyncapi/modelina/blob/master/docs/contributing.md#adding-a-new-preset

And you can read more about presets here: https://github.com/asyncapi/modelina/blob/master/docs/presets.md

See other examples here:
- C# Newtonsoft: https://github.com/asyncapi/modelina/blob/master/docs/languages/Csharp.md#using-newtonsoftjsonnet
- Java Jackson: https://github.com/asyncapi/modelina/blob/master/docs/languages/Java.md#jackson-annotation
- Java custom serializer: https://github.com/asyncapi/modelina/blob/master/docs/languages/Java.md#jackson-annotation
- TypeScript custom serializer: https://github.com/asyncapi/modelina/blob/master/docs/languages/TypeScript.md#generate-marshalling-and-unmarshalling-functions

**Comment by sambhavgupta0705** [comment]
hey @jonaslagoni I would like to work on this one:)

**Comment by jonaslagoni** [comment]
Go for it @sambhavgupta0705! Let me know if you get stuck 🙂

**Comment by sambhavgupta0705** [comment]
Hey @jonaslagoni I need some more clarification for this issue:)

**Comment by jonaslagoni** [comment]
@sambhavgupta0705 sure! What would you like to know? 🙂

**Comment by sambhavgupta0705** [comment]
Hey @jonaslagoni what does serialisation preset do

**Comment by jonaslagoni** [comment]
The preset is what alters the core generated models to our liking, for example in this case adds two functions, one for serializing and one for deserializing the model 🙂 

Read more about the presets and how they work here: https://github.com/asyncapi/modelina/blob/master/docs/contributing.md#adding-a-new-preset

I also listed existing presets you can for reference.

The general things that has to change are the following:
1. Add a new Python preset.
2. Make the preset add two function `to_json` and `from_json` that converts a model to and from json.
3. Add tests for the preset
4. Add an example for the preset
5. Adapt the documentation for Python to show the new feature

And that's it 🎉

**Comment by sambhavgupta0705** [comment]
ohkk @jonaslagoni ,thanks for the clarification.:)

**Comment by prayutsu** [comment]
working on this!
