### ISSUE TITLE
More accurate tuple types

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#1139]
#### Reason/Context
Say we have this:
```
    "tags": {
      "type": "array",
      "items": [{type: string}, {type: boolean}],
      "additionalItems": true
    },
```

It would currently generate this:
```
private _tags?: (string | boolean | any)[];
```

But the more accurate type would be this:
```
private _tags?: [string, boolean, ...any[]];
```

I think we should be able to define tuple models with additionalItems, so that each output can decide the most accurate representation it can do. For example, in most languages, it would probably be just a generic array type, but in others where possible, they can be as precise as possible.

**Comment by janachinna** [comment]
Hey @jonaslagoni , Currently when i try to generate the List<T> using KotlinFileGenerator it always generates with List<Any>. Does this enhancement fixes that issue?

**Comment by jonaslagoni** [comment]
What types are you expecting for tuples in Kotlin?

**Comment by janachinna** [comment]
@jonaslagoni  Instead of Any, it should use the type mentioned in the async spec file. Eventhough the items spec is referring to a schema object it always generates List<Any> Where as It should generate List<T> Where T is the type of object mentioned in the spec file.

```
        Foo:
          type: array
          items:
            $ref: '#/components/schemas/Bar'
         Bar:
          type: object
          properties:
             id:
               type: number
             name:
               type: string
```
This should generate List<Bar> inside Foo. But it generates List<Any> inside Foo.

**Comment by jonaslagoni** [comment]
@janachinna ahh, yea that's a bug that https://github.com/asyncapi/modelina/pull/1140 is fixing.

To work around this bug you could do this:
```
        Foo:
          type: array
          additionalItems: false
          items:
            $ref: '#/components/schemas/Bar'
```
