### ISSUE TITLE
Add support to Kotlin.Serialziation to Kotlin Generator

### ISSUE THREAD

**Issue by kelvin-lima** [asyncapi/modelina#1143]
#### Description

Kotlin serialization is growing in adoption and will be very nice to support it. In my context, it is used as the main choice to handle Json serialization and Deserialization.

A nice library that converts existing Jsons(not the specification) and can help with the implementation is the [JsonToKotlinClass](https://github.com/wuseal/JsonToKotlinClass)

I'm not sure if it's a complete specification of the request but I will be very glad to provide some extra information if needed.

**Comment by LouisXhaferi** [comment]
Definitely a good idea to also support `kotlinx.serialization`!

This feature request is somewhat related to https://github.com/asyncapi/modelina/issues/1128, as we also need to support JSON (de-)serialization using Jackson, with it being the most used library in the JVM world.

**Comment by jonaslagoni** [comment]
That is the great thing about presets, you can have one for each library you want to support i.e. one for Jackson and one for kotlinx.serialization 😄 

@kelvin-lima if you want to contribute it we have documentation for how to add it here: https://github.com/asyncapi/modelina/blob/master/docs/contributing.md#adding-a-new-preset

And you can read more about presets here: https://github.com/asyncapi/modelina/blob/master/docs/presets.md

Happy to help you get started or guide you through it 🙂

**Comment by kelvin-lima** [comment]
Thanks for the answer :)
Right now I'm a little bit busy but in a few days I will take a look and try to create an implementation :)
