### ISSUE TITLE
Improve navbar of modelina website

### ISSUE THREAD

**Issue by sambhavgupta0705** [asyncapi/modelina#1152]
#### Description

The navbar of tentative website of modelina need some improvement.Currently the logo is of AsyncAPI main website ,we can change it to Modelina and also hyperlink it to modelina website.
![image](https://user-images.githubusercontent.com/81870866/224690860-ffdb34dd-02ff-4e4e-9e78-5e711ef46af2.png)

You can checkout the website here: [Modelina](https://modelina.org/) and the PR here: #1117

**Comment by sambhavgupta0705** [comment]
hey @jonaslagoni should we pick the logo from [here](https://github.com/asyncapi/brand/tree/master/brand-guidelines/branded-tools#light-version-1)

**Comment by jonaslagoni** [comment]
I think so yes 👍

**Comment by sambhavgupta0705** [comment]
I think currently we should make word changes in this [file](https://github.com/asyncapi/modelina/blob/master/modelina-website/src/components/icons/AsyncAPILogo.tsx) for navbar

**Comment by Mayaleeeee** [comment]
![Mark (1)](https://user-images.githubusercontent.com/105395613/227174743-c11ae1e3-79a6-4062-af53-40cf8bcdba80.svg)

**Comment by ishaan812** [comment]
Can I be assigned this issue?

**Comment by jonaslagoni** [comment]
@ishaan812 think you can go ahead and do the issue, we dont assign issues :)

**Comment by ishaan812** [comment]
![image](https://user-images.githubusercontent.com/70190533/227703576-36a32cd4-ff9a-42fb-b972-cdf335b44d9a.png)
Hey if we want to replace this we would want a bigger logo with some text right?
This is what it looks like now
![image](https://user-images.githubusercontent.com/70190533/227703687-207af392-77b0-4059-80f5-d6b7572094e4.png)

**Comment by sambhavgupta0705** [comment]
hey @ishaan812 ,currently I am in contact with @Mayaleeeee and we are thinking of adding the `modelina` name beside of logo .

**Comment by sambhavgupta0705** [comment]
>his is what it looks like now ![image](https://user-images.githubusercontent.com/70190533/227703687-207af392-77b0-4059-80f5-d6b7572094e4.png)

The image can be resized I think

**Comment by ishaan812** [comment]
> hey @ishaan812 ,currently I am in contact with @Mayaleeeee and we are thinking of adding the `modelina` name beside of logo .



> > this is what it looks like now ![image](https://user-images.githubusercontent.com/70190533/227703687-207af392-77b0-4059-80f5-d6b7572094e4.png)
> 
> The image can be resized I think
Yep, I can reduce the whitespace. We can also change the title icon along with the navbar change.

**Comment by sambhavgupta0705** [comment]
Hey @ishaan812 I have already made the changes on my local fork and will raise the PR soon.

**Comment by ishaan812** [comment]
Alright

**Comment by jonaslagoni** [comment]
@ishaan812 as it seems @sambhavgupta0705 is moving forward with this issue, maybe one of these spark an interest?

- https://github.com/asyncapi/modelina/issues/1173
- https://github.com/asyncapi/modelina/issues/1171

**Comment by Mayaleeeee** [comment]
Hi @sambhavgupta0705, here you go.
![Modelina](https://user-images.githubusercontent.com/105395613/227801334-0efa95ef-b318-4e91-ad0a-0d49a2781ae6.svg)
