### ISSUE TITLE
Add enum type selection in the playground

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#1162]
#### Reason/Context
For the TypeScript generator, you can [select between enum or union](https://github.com/asyncapi/modelina/blob/master/docs/languages/TypeScript.md#generate-union-types-instead-of-enums), this should be possible in the playground as well.

To achieve this the following needs to change:
- Add the option `tsEnumType` to [the list of options](https://github.com/asyncapi/modelina/blob/c12c56ad705de89e1d0f80d0ec5706fe7b648139/modelina-website/src/types/index.ts#L12), where the type is `'union' | 'enum' | undefined`
- Make sure we show the options being provided in [the generator code output of the playground](https://github.com/asyncapi/modelina/blob/c12c56ad705de89e1d0f80d0ec5706fe7b648139/modelina-website/src/helpers/GeneratorCode/TypeScriptGenerator.ts#L4).
- Adapt the UI to include a dropdown to [choose between the enum types](https://github.com/asyncapi/modelina/blob/c12c56ad705de89e1d0f80d0ec5706fe7b648139/modelina-website/src/components/playground/options/TypeScriptGeneratorOptions.tsx#L44)
- Add a react handler to handle when the [enum type selection changes value](https://github.com/asyncapi/modelina/blob/c12c56ad705de89e1d0f80d0ec5706fe7b648139/modelina-website/src/components/playground/options/TypeScriptGeneratorOptions.tsx#L32)
- Adapt the backend serverless function to use the [new option during the generation phase](https://github.com/asyncapi/modelina/blob/c12c56ad705de89e1d0f80d0ec5706fe7b648139/modelina-website/src/pages/api/functions/TypeScriptGenerator.ts#L21)

Happy to help even further in case you need it! Ping me here in the issue or in the AsyncAPI slack channel 👋

**Comment by prayutsu** [comment]
working on this.

**Comment by prayutsu** [comment]
@jonaslagoni Getting error while running `npm run build` in modelina website in master branch
<img width="1208" alt="Screenshot 2023-03-21 at 9 59 28 PM" src="https://user-images.githubusercontent.com/54636525/226676887-fca72aa6-8f1a-4032-98d9-15aba4a1d493.png">

**Comment by jonaslagoni** [comment]
@prayutsu make sure you follow the [readme](https://github.com/asyncapi/modelina/tree/master/modelina-website#how-to-run-it) 🙂

**Comment by prayutsu** [comment]
> @prayutsu make sure you follow the [readme](https://github.com/asyncapi/modelina/tree/master/modelina-website#how-to-run-it) 🙂

Ah, missed it. Thanks @jonaslagoni
