### ISSUE TITLE
Show generation errors in Playground 

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#1167]
#### Reason/Context
Currently, if Modelina fails to generate your models there is no error displayed to the user, it just silently fails.

To solve this issue the following need to change:
- Adapt the UI to have a place to show the error.
- Adapt the request code in the Playground component, so when the request fails, we display this error.
- You probably need to adapt the serverless function to return more factual errors instead of just "Error", see `/src/pages/api/generate`.

Feel free to reach out if you want to pick this up or need guidance or have questions 🙂

**Comment by Samridhi-98** [comment]
Hi @jonaslagoni, I would like to work on this. 🙂
