### ISSUE TITLE
Add description and example support in the Playground

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#1174]
#### Reason/Context
For the TypeScript generator, you can [choose to make the model generate documentation and examples for the properties and models](https://github.com/asyncapi/modelina/blob/master/docs/languages/TypeScript.md#rendering-comments-from-description-and-example-fields), this should be possible in the playground as well.

To achieve this the following needs to change:
- Add the option `tsIncludeDescriptions` to [the list of options](https://github.com/asyncapi/modelina/blob/c12c56ad705de89e1d0f80d0ec5706fe7b648139/modelina-website/src/types/index.ts#L12), where the type is `boolean`
- Make sure we show the options being provided in [the generator code output of the playground](https://github.com/asyncapi/modelina/blob/c12c56ad705de89e1d0f80d0ec5706fe7b648139/modelina-website/src/helpers/GeneratorCode/TypeScriptGenerator.ts#L4).
- Adapt the UI to include a checkbox to [to include the description](https://github.com/asyncapi/modelina/blob/c12c56ad705de89e1d0f80d0ec5706fe7b648139/modelina-website/src/components/playground/options/TypeScriptGeneratorOptions.tsx#L44)
- Add a react handler to handle when the [checkbox changes](https://github.com/asyncapi/modelina/blob/c12c56ad705de89e1d0f80d0ec5706fe7b648139/modelina-website/src/components/playground/options/TypeScriptGeneratorOptions.tsx#L32)
- Adapt the backend serverless function to use the [new option during the generation phase](https://github.com/asyncapi/modelina/blob/c12c56ad705de89e1d0f80d0ec5706fe7b648139/modelina-website/src/pages/api/functions/TypeScriptGenerator.ts#L21)

Happy to help even further in case you need it! Ping me here in the issue or in the AsyncAPI slack channel 👋

**Comment by prayutsu** [comment]
working on this.
