### ISSUE TITLE
Add Newtonsoft serialization support in the Playground

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#1176]
#### Reason/Context
For the C# generator, you can [choose to make the model generate serialization support for the Newtonsoft library](https://github.com/asyncapi/modelina/blob/master/docs/languages/Csharp.md#using-newtonsoftjsonnet), this should be possible in the playground as well.

To achieve this the following needs to change:
- Add the option `csharpIncludeNewtonsoft` to [the list of options](https://github.com/asyncapi/modelina/blob/c12c56ad705de89e1d0f80d0ec5706fe7b648139/modelina-website/src/types/index.ts#L19) where the type is `boolean`
- Make sure we show the options being provided in [the generator code output of the playground](https://github.com/asyncapi/modelina/blob/c12c56ad705de89e1d0f80d0ec5706fe7b648139/modelina-website/src/helpers/GeneratorCode/CSharpGenerator.ts#L4).
- Adapt the UI to [include a checkbox](https://github.com/asyncapi/modelina/blob/c12c56ad705de89e1d0f80d0ec5706fe7b648139/modelina-website/src/components/playground/options/CSharpGeneratorOptions.tsx), you can use the [following code as baseline](https://github.com/asyncapi/modelina/blob/c12c56ad705de89e1d0f80d0ec5706fe7b648139/modelina-website/src/components/playground/options/TypeScriptGeneratorOptions.tsx#L61)
- Add a react handler to handle when the [checkbox changes](https://github.com/asyncapi/modelina/blob/c12c56ad705de89e1d0f80d0ec5706fe7b648139/modelina-website/src/components/playground/options/CSharpGeneratorOptions.tsx), you can use [following code as a baseline](https://github.com/asyncapi/modelina/blob/c12c56ad705de89e1d0f80d0ec5706fe7b648139/modelina-website/src/components/playground/options/TypeScriptGeneratorOptions.tsx#L26).
- Adapt the backend serverless function to use the [new option during the generation phase](https://github.com/asyncapi/modelina/blob/c12c56ad705de89e1d0f80d0ec5706fe7b648139/modelina-website/src/pages/api/functions/CSharpGenerator.ts#L13)

Happy to help even further in case you need it! Ping me here in the issue or in the AsyncAPI slack channel 👋

**Comment by kaushik-rishi** [comment]
@jonaslagoni can you please review ?
Also, if there are multiple similar and small issues would you suggest creating multiple PR's one for each of those and then go ahead and resolve each conflict ? or would you rather suggest to solve 2-3 small issues in a single PR and mention the PR under multiple issues ?

**Comment by jonaslagoni** [comment]
If it's related changes, you can freely bundle stuff together 👍 But be careful, because the larger the PR the more changes needs to be reviewed, and potential problems 🙂 

So find your own balance, and I will for sure also let you know if they contain too much 🙂
