### ISSUE TITLE
Add overwriting Equal method support in the Playground

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#1177]
#### Reason/Context
For the C# generator, you can [choose to make the model overwrite the Equal method](https://github.com/asyncapi/modelina/blob/master/docs/languages/Csharp.md#generate-models-with-equals-and-gethashcode-methods), this should be possible in the playground as well.

To achieve this the following needs to change:
- Add the option `csharpOverwriteEqual` to [the list of options](https://github.com/asyncapi/modelina/blob/c12c56ad705de89e1d0f80d0ec5706fe7b648139/modelina-website/src/types/index.ts#L19) where the type is `boolean`
- Make sure we show the options being provided in [the generator code output of the playground](https://github.com/asyncapi/modelina/blob/c12c56ad705de89e1d0f80d0ec5706fe7b648139/modelina-website/src/helpers/GeneratorCode/CSharpGenerator.ts#L4).
- Adapt the UI to [include a checkbox](https://github.com/asyncapi/modelina/blob/c12c56ad705de89e1d0f80d0ec5706fe7b648139/modelina-website/src/components/playground/options/CSharpGeneratorOptions.tsx), you can use the [following code as baseline](https://github.com/asyncapi/modelina/blob/c12c56ad705de89e1d0f80d0ec5706fe7b648139/modelina-website/src/components/playground/options/TypeScriptGeneratorOptions.tsx#L61)
- Add a react handler to handle when the [checkbox changes](https://github.com/asyncapi/modelina/blob/c12c56ad705de89e1d0f80d0ec5706fe7b648139/modelina-website/src/components/playground/options/CSharpGeneratorOptions.tsx), you can use [following code as a baseline](https://github.com/asyncapi/modelina/blob/c12c56ad705de89e1d0f80d0ec5706fe7b648139/modelina-website/src/components/playground/options/TypeScriptGeneratorOptions.tsx#L26).
- Adapt the backend serverless function to use the [new option during the generation phase](https://github.com/asyncapi/modelina/blob/c12c56ad705de89e1d0f80d0ec5706fe7b648139/modelina-website/src/pages/api/functions/CSharpGenerator.ts#L13)

Happy to help even further in case you need it! Ping me here in the issue or in the AsyncAPI slack channel 👋

**Comment by kaushik-rishi** [comment]
Hey guys, it's a very good issue to take up, if you want to learn about the amazing type system used, component structure, context providers and next js api routes. :slightly_smiling_face: 

I've linked some notes for your reference.
https://github.com/asyncapi/modelina/pull/1325#issuecomment-1567368014

I don't want to pick it up, because someone could greatly benefit from solving this.
Or do you think i should make a PR ? @jonaslagoni :slightly_smiling_face:

**Comment by jonaslagoni** [comment]
@kaushik-rishi I will create more good first issues when they are gone, so dont hold back 😄

**Comment by kaushik-rishi** [comment]
Sure @jonaslagoni 
I'll make a pr after merging the #1337 
Or most of the time will be spent on resolving the merge conflicts :smile:
