### ISSUE TITLE
Add auto-implemented support in the Playground

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#1179]
#### Reason/Context
For the C# generator, you can [choose to make the model have auto-implemented accessors](https://github.com/asyncapi/modelina/blob/master/docs/languages/Csharp.md#generate-models-with-auto-implemented-properties), this should be possible in the playground as well.

To achieve this the following needs to change:
- Add the option `csharpUseAutoImplemented` to [the list of options](https://github.com/asyncapi/modelina/blob/c12c56ad705de89e1d0f80d0ec5706fe7b648139/modelina-website/src/types/index.ts#L19) where the type is `boolean`
- Make sure we show the options being provided in [the generator code output of the playground](https://github.com/asyncapi/modelina/blob/c12c56ad705de89e1d0f80d0ec5706fe7b648139/modelina-website/src/helpers/GeneratorCode/CSharpGenerator.ts#L4).
- Adapt the UI to [include a checkbox](https://github.com/asyncapi/modelina/blob/c12c56ad705de89e1d0f80d0ec5706fe7b648139/modelina-website/src/components/playground/options/CSharpGeneratorOptions.tsx), you can use the [following code as baseline](https://github.com/asyncapi/modelina/blob/c12c56ad705de89e1d0f80d0ec5706fe7b648139/modelina-website/src/components/playground/options/TypeScriptGeneratorOptions.tsx#L61)
- Add a react handler to handle when the [checkbox changes](https://github.com/asyncapi/modelina/blob/c12c56ad705de89e1d0f80d0ec5706fe7b648139/modelina-website/src/components/playground/options/CSharpGeneratorOptions.tsx), you can use [following code as a baseline](https://github.com/asyncapi/modelina/blob/c12c56ad705de89e1d0f80d0ec5706fe7b648139/modelina-website/src/components/playground/options/TypeScriptGeneratorOptions.tsx#L26).
- Adapt the backend serverless function to use the [new option during the generation phase](https://github.com/asyncapi/modelina/blob/c12c56ad705de89e1d0f80d0ec5706fe7b648139/modelina-website/src/pages/api/functions/CSharpGenerator.ts#L13)

Happy to help even further in case you need it! Ping me here in the issue or in the AsyncAPI slack channel 👋

**Comment by prayutsu** [comment]
working on this.
