### ISSUE TITLE
[📑 Docs]: Use code to represent the internal models

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#1182]
### What Dev Docs changes are you proposing?

Currently, it's not easy to update the [internal model images](https://github.com/asyncapi/modelina/blob/master/docs/internal-model.md) and keeping them up to date, as I have the draw.io file...

Instead, we should add them as code through something like Mermaid: https://mermaid.js.org/syntax/classDiagram.html

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jonaslagoni** [comment]
Still relevant.

**Comment by DRACrY0** [comment]
I'll try to look into it.

**Comment by jonaslagoni** [comment]
Thanks @DRACrY0 👍
