### ISSUE TITLE
TypeScript uses Location as reserved keyword

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#1206]
#### Describe the bug
I dont think that `location` is a reserved keyword 🧐 Or at least it seems like its fine to use, we should double check it.

**Comment by codingmickey** [comment]
Hmm I didn't understand what this issue is about from the description @jonaslagoni any more specifics?

**Comment by sujalcodes3** [comment]
Hey, I am a new comer, i would like to contribute to this issue. But the description doesn't tell a lot of about the issue. Can you please elaborate on the issue.
