### ISSUE TITLE
Remove duplicate navigation from navbar

### ISSUE THREAD

**Issue by sambhavgupta0705** [asyncapi/modelina#1238]
#### Describe the bug
Currently in navbar there is a navitem named `modelina` which is doing the same thing as the logo 
#### How to Reproduce
Steps to reproduce the issue. Attach all resources that can help us understand the issue:
Just go to modelina.org and you will see it in navbar
- Screenshots
![image](https://user-images.githubusercontent.com/81870866/232024475-7a32ac8c-6b19-487e-be1d-0441cba5e9b3.png)

#### Expected behavior
We can remove the navitem modelina for now

**Comment by sambhavgupta0705** [comment]
@jonaslagoni we can remove it for now until we bring docs to the website.
WDUT?

**Comment by jonaslagoni** [comment]
Even with #1161, having both the logo and the headline item don't make much sense 😄 Lets just remove it 🙂

**Comment by sambhavgupta0705** [comment]
Ok we can make it a good first issue for new contributors.
