### ISSUE TITLE
Kotlin generator makes all properties required

### ISSUE THREAD

**Issue by micro-jumbo** [asyncapi/modelina#1273]
#### Describe the bug
Kotlin generator makes all properties required, even those which are not in `required` list in Async API definition.

#### How to Reproduce
For given component:
```json
      "Success": {
        "type": "object",
        "title": "Success",
        "properties": {
          "result": {
            "title": "SuccessMessageResult",
            "type": "string",
            "const": "SUCCESS"
          },
          "message": {
            "type": "string",
            "title": "SuccessMessageMessage"
          }
        },
        "required": [
          "result"
        ],
        "additionalProperties": false
      },
```

generated Kotlin code is following:
```kotlin
data class SuccessMessage(
  val result: SuccessMessageResult,
  val message: String
)
```

which makes `message` a required, non-nullable field.

#### Expected behavior
Generate kotlin class with nullable property if propety is not required in AsyncAPI definition

**Comment by LouisXhaferi** [comment]
Thanks for the issue. Probably a good idea to change this.

**Comment by LouisXhaferi** [comment]
One note though: Since this fix is going to change the output of the renderer, it is considered a breaking change. Breaking changes are handled differently from "normal" changes.

@jonaslagoni could you pls elaborate on how and where to commit this fix?

**Comment by jonaslagoni** [comment]
I commented on the PR 🙂
