### ISSUE TITLE
Redesigning Modelina’s website while keeping the UI/UX in mind.

### ISSUE THREAD

**Issue by prajjwalkapoor** [asyncapi/modelina#1293]
### Why do we need this improvement?

The current website of Modelina is not as appealing as Async API's main website. It is not mobile-responsive and does not have all the features and information that users need. The website should be improved to make it more user-friendly and informative. Also, the Docs of Modelina should be integrated with keeping UX in mind.

These are some of the few things that we can improve.

![image](https://github.com/asyncapi/modelina/assets/68912239/179efd16-b124-4327-8798-94012282166b)

### How will this change help?

Redesigning the website will make the information more easily accessible in a visually appealing manner. Also, by integrating the docs directly into the website will reduce the time of searching things on GitHub.

### Expected Flow

- Designing the Figma mockups for complete websites (Including Docs)
- Building the UI for the design.
- Integrating the docs.

### What is the motivation?

The **People** and the **Product** :slightly_smiling_face:

**Comment by jonaslagoni** [comment]
Definitely could use a design uplift 😆 

My only concern is the Figma mockups, and this depends on how far you want to take it, but as long as it's just for your convenience for you to contribute that's perfectly fine 🙂

**Comment by jonaslagoni** [comment]
> Regarding the Figma mockups, it gives the idea of where the design is heading. Also, it's easier to take feedback with design mockups. If you have any suggestions or specific considerations in mind, I would love to take your input.

It's a nice idea, but not everyone will have Figma, use it, or even know how to use it (me included). So requiring Figma to be updated each time before the website changes will be almost impossible to enforce, or not make any sense IMO. 

It sounds perfect for a product team, in the same company, that has the possibility to enforce it, but in open source, not so much.

That's why I am saying that as long as it's not a requirement to change Figma when doing any changes to the website, then it's cool with me 👍

**Comment by jonaslagoni** [comment]
How does that sound @prajjwalkapoor?

**Comment by prajjwalkapoor** [comment]
Yeah, @jonaslagoni, it's okay if we proceed that way also. I am starting the work on the website then.

**Comment by sambhavgupta0705** [comment]
IMO it would be good if we open several issues as then we will be able to divide task and I guess there will be no need of figma also

**Comment by prajjwalkapoor** [comment]
Nice idea @sambhavgupta0705, we can do this

**Comment by jonaslagoni** [comment]
Hey folks, any update here? Anything you need help with? 🙂

**Comment by Mayaleeeee** [comment]
I'll include this in the design issues that @fmvilas, and I are compiling for our new design contributors. I appreciate you bringing it to my attention, @sambhavgupta0705. Thank you!

**Comment by Mayaleeeee** [comment]
Hi @prajjwalkapoor I'm interested in working on this issue.

**Comment by Mayaleeeee** [comment]
Please check this out.
![Modelina Homepage](https://github.com/asyncapi/modelina/assets/105395613/08838556-2aeb-45cd-972e-d0df70ddc653)

**Comment by sambhavgupta0705** [comment]
Hey @Mayaleeeee @prajjwalkapoor won't be working on this issue.
If you agree @jonaslagoni we can work on this design

**Comment by jonaslagoni** [comment]
cc @devilkiller-ag incase you find any of this interesting ✌️

**Comment by devilkiller-ag** [comment]
Hi, @jonaslagoni This issue seems to be a perfect fit for me. I am interested in working on this. So will we follow the above [figma design](https://www.figma.com/file/SExfZmoLPFZdOiZPkyvj9j/Modelina?type=design&node-id=0-1&mode=design) shared by @Mayaleeeee as a base? Also, can I include issue #1715 in this?

**Comment by jonaslagoni** [comment]
I would probably split it up into multiple PRs but you have free use to do what you want 😄

**Comment by devilkiller-ag** [comment]
That too seems to be a good option. I will access the website in detail and start working on this my creating multiple PRs. By the way, can this work be eligible for Bounty?

**Comment by devilkiller-ag** [comment]
@jonaslagoni After carefully comparing the AsyncAPI website and the Modelina website, I think we can divide this work into the following PRs:

1) Redesign Navbar
2) Redesign Hero Section
3) Redesign Usage Section
4) Make Playground Mobile Responsive

Let me know if there is something else that I forgot.

**Comment by jonaslagoni** [comment]
Sounds good 👍 

Feel free to re-organize the issues as you see fit 😄

**Comment by devilkiller-ag** [comment]
Okay Great, I will start with Navbar!

**Comment by Min2who** [comment]
> @jonaslagoni After carefully comparing the AsyncAPI website and the Modelina website, I think we can divide this work into the following PRs:
> 
> 1. Redesign Navbar
> 2. Redesign Hero Section
> 3. Redesign Usage Section
> 4. Make Playground Mobile Responsive
> 
> Let me know if there is something else that I forgot.

can i help you make some components here?

cc @jonaslagoni @devilkiller-ag

**Comment by devilkiller-ag** [comment]
Hi @Min2who Thanks for asking. However, I would like to work on all of these parts. I would appreciate it if you can solve some [stale](https://github.com/asyncapi/modelina/issues?q=is%3Aopen+is%3Aissue+label%3Astale) issues.

**Comment by devilkiller-ag** [comment]
Hey @jonaslagoni, now I will move forward with working on responsive layout of playground.

**Comment by jonaslagoni** [comment]
@devilkiller-ag does it make sense to close this issue down and open smaller issues as needed for the website?

**Comment by devilkiller-ag** [comment]
Hi @jonaslagoni, yes the work on this issue was completed in PR #1732 and #1733. So we can close this issue. However, I feel we can make the hero section styling for the mobile view better. Should I  open an issue for this today?

**Comment by jonaslagoni** [comment]
For sure 🤙
