### ISSUE TITLE
Add runtime testing for Rust

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#1295]
#### Reason/Context
In https://github.com/asyncapi/modelina/pull/1272 we added the initial runtime setup for Java, now it's time to replicate it for Rust.

The reason we add these is to ensure that the code that is generated is semantically and syntactically correct, and the only way to achieve this is by testing the models at runtime.

This initial setup should be as simple as possible, just a Rust project, with a single test and a single generated model, and that's it.

Here is the general task list:

- [ ] Create a Rust project under; `test/runtime/runtime-rust`
- [ ] Add a simple test code generation script here: `test/runtime/runtime-rust.ts`. Check out the Java variant as an example https://github.com/asyncapi/modelina/blob/master/test/runtime/runtime-java.ts
- [ ]  Add the generation script to the package file: https://github.com/asyncapi/modelina/blob/ba0bd41e9803394f56872c5ec92f8e335a4d687a/package.json#L98
- [ ] Run the generation script
- [ ] Manually add a simple test for the generated models, could be as simple as just creating an instance of it.
- [ ] Add a simple Jest script, which just execute the Rust test: https://github.com/asyncapi/modelina/blob/master/test/runtime/runtime-java.spec.ts
- [ ] Add a simple script that will run the test: https://github.com/asyncapi/modelina/blob/ba0bd41e9803394f56872c5ec92f8e335a4d687a/package.json#L97
- [ ] Create a CI workflow that runs the runtime tests: https://github.com/asyncapi/modelina/blob/master/.github/workflows/runtime-java-testing.yml

And that's it 🎉

**Comment by Shurtu-gal** [comment]
Hey @jonaslagoni can I work on this?

**Comment by jonaslagoni** [comment]
Please do 👍

**Comment by Shurtu-gal** [comment]
Hey @jonaslagoni the generated rust code is having errors.

>   thrown: "Error: Command failed: cd /home/shurtu-gal/Projects/asyncAPI/modelina/test/runtime/runtime-rust && cargo test
       Compiling proc-macro2 v1.0.58
       Compiling quote v1.0.27
       Compiling unicode-ident v1.0.9
       Compiling serde v1.0.163
       Compiling serde_json v1.0.96
       Compiling ryu v1.0.13
       Compiling itoa v1.0.6
       Compiling syn v2.0.16
       Compiling serde_derive v1.0.163
       Compiling asyncapi-rs-example v1.0.0 (/home/shurtu-gal/Projects/asyncAPI/modelina/test/runtime/runtime-rust)
    error[E0369]: binary operation `==` cannot be applied to type `Vec<union::Union>`
      --> src/address.rs:13:5
       |
    2  | #[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
       |                                     --------- in this derive macro expansion
    ...
    13 |     pub array_type: Vec<crate::Union>,
       |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       |
       = note: this error originates in the derive macro `PartialEq` (in Nightly builds, run with -Z macro-backtrace for more info)

    error[E0369]: binary operation `==` cannot be applied to type `std::option::Option<Box<nested_object::NestedObject>>`
      --> src/address.rs:15:5
       |
    2  | #[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
       |                                     --------- in this derive macro expansion
    ...
    15 |     pub nested_object: Option<Box<crate::NestedObject>>,
       |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       |
    note: an implementation of `PartialEq` might be missing for `nested_object::NestedObject`
    
    
Could you please help me out?

**Comment by jonaslagoni** [comment]
@Shurtu-gal I am no Rust expert, and without seeing the test and the code you use, I have no idea what's wrong 😄 

Try adding the changes to a draft PR 🙂

**Comment by Shurtu-gal** [comment]
> @Shurtu-gal I am no Rust expert, and without seeing the test and the code you use, I have no idea what's wrong smile
> 
> Try adding the changes to a draft PR slightly_smiling_face

I have done it.
