### ISSUE TITLE
When schemas are in another file, they require additional fields.

### ISSUE THREAD

**Issue by JFCote** [asyncapi/modelina#1297]
#### Describe the bug

It was suggested to me by a user in the Slack community to create a bug here: https://asyncapi.slack.com/archives/CQVJXFNQL/p1684436870155959

The problem is that when you separate the main spec from the schema, Modelina creates "anonymous" class by default.
The solution is to add either `$id` or `x-parser-schema-id` to each schema and it will work as expected

#### How to Reproduce

Let's say we split our spec in 2 parts:
Main: https://app.swaggerhub.com/apis/JEANFRANCOISCOTE/MainSpec/1.0.0
Models: https://app.swaggerhub.com/apis/JEANFRANCOISCOTE/SharedMessages/1.0.0

Create the models with Modelina in C# and notice the class will be named Anonymous_X

#### Expected behavior

Modelina should be able to find the name of the class since they are in the SharedMessages specification.
We should not need to add a "vendor" field for this to be supported. Coming from an OpenAPI background and this is supported.

At least, there should be documentation about it how to get around this problem because putting the model in a shared place is a very common thing in AsyncAPI.

Thanks!

**Comment by AnimeshKumar923** [comment]
still valid? @jonaslagoni

**Comment by jonaslagoni** [comment]
Right now I dont have time to look into the underlying cause to make this a good first issue. If someone wants to dive into it please go ahead!
