### ISSUE TITLE
docs: add website setup commands in readme

### ISSUE THREAD

**Issue by sambhavgupta0705** [asyncapi/modelina#1299]
#### Reason/Context
Please try answering few of those questions
- Why we need this improvement?
  As now Modelina has its own website so we should mention it in the readme and also the steps how to locally run it
- How will this change help?
 It will help new contributor in contributing to the project.

 
#### Description
Please try answering few of those questions
- What changes have to be introduced?
   - Some changes in readme
   - steps of hosting modelina website locally
- Will this be a breaking change?
   No

**Comment by jonaslagoni** [comment]
I dont think we should guides in the [main readme](https://github.com/asyncapi/modelina) for how to run the website locally, that should be in the website readme.

But agree we should probably add a section about the website in the main readme 🤔

**Comment by sambhavgupta0705** [comment]
Yeahh, we can add a link for the website setup which will redirect to website readme.
Good idea👍

**Comment by kaushik-rishi** [comment]
@sambhavgupta0705 are you planning to work on it ?

**Comment by rukundob451** [comment]
@sambhavgupta0705 and @jonaslagoni is this open?

**Comment by jonaslagoni** [comment]
Yep 👍

**Comment by rukundob451** [comment]
@jonaslagoni and @sambhavgupta0705 I have linked a [PR](https://github.com/asyncapi/modelina/pull/1395) for this, kindly check out!
