### ISSUE TITLE
Simplify metadata fields in combined schemas

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/modelina#130]
We don't support simplification for metadata fields like `minItems`, `minimum`, `maxLength` etc. in combined schemas like `anyOf`, `oneOf`, `allOf`. This issue is a tracker for each missed field.

- Number/Integer:
  - [ ] minimum
  - [ ] exclusiveMinimum
  - [ ] maximum
  - [ ] exclusiveMaximum
  - [ ] multipleOf
- String:
  - [ ] minLength
  - [ ] maxLength
  - [ ] pattern
- Array:
  - [ ] minItems
  - [ ] maxItems
  - [ ] uniqueItems
- Object:
  - [ ] minProperties
  - [ ] maxProperties
- All
  - [ ] examples
  
> Please update if something was not included.

**Comment by jonaslagoni** [comment]
Still relevant

**Comment by AnimeshKumar923** [comment]
still valid? @jonaslagoni
