### ISSUE TITLE
Is it possible to implement unions (e.g `oneOf`) with `sealed` classes in dart generator?

### ISSUE THREAD

**Issue by rubenferreira97** [asyncapi/modelina#1300]
#### Reason/Context
Currently `Object` is used for a unions (like `oneOf`), making type safety not really useful.

#### Description
Unfortunately dart still does not have unions, but in dart 3.0 `sealed` classes were introduced.

An example with `oneOf` pseudocode:
- Object `Teacher` with properties: `required string school, required int[] classIds`
- Object `Student` with properties: `required string school, required int grade`

Would generate:

```dart
sealed class SchoolPerson {}

class Teacher extends SchoolPerson {
  Teacher(this.school, this.classIds);

  String school;
  List<int> classIds;
  Map<String, Object>? additionalProperties;
}

class Student extends SchoolPerson {
  Teacher(this.school, this.grade);

  String school;
  int grade;
  Map<String, Object>? additionalProperties;
}
```

Now we can safely write another schema like `School` that has a list of `SchoolPerson`:

- Object `School` with properties: `required SchoolPerson[] attendees`

```dart
class School {
  School (this.attendees);

  List<SchoolPerson> attendees;
  Map<String, Object>? additionalProperties;
}
```

**Comment by jonaslagoni** [comment]
Sorry for the late reply @rubenferreira97.

The absolute easiest way to achieve unions (because remember you can also have union of simple types such as boolean + string, not just classes) is to generate a class with properties for each model in the union.
