### ISSUE TITLE
Make sidebar responsive and collapsible

### ISSUE THREAD

**Issue by Bhavik-ag** [asyncapi/modelina#1315]
#### Reason/Context
Please try answering few of those questions
- Why we need this improvement?
To make the site readable in mobile view,

![Screenshot from 2023-05-24 11-14-05](https://github.com/asyncapi/modelina/assets/73033511/d9d4a9e5-e507-4deb-ae7f-e4ff622f4a28)

#### Description
Please try answering few of those questions
- What changes have to be introduced?
Add responsiveness to the sidebar by making it collapsable

**Comment by kaushik-rishi** [comment]
@Bhavik-ag We also need to add a bit of responsiveness in regards to the side-by-side code panels i guess. What do you think ?

**Comment by Shurtu-gal** [comment]
@kaushik-rishi @Bhavik-ag Can I work upon this?

**Comment by kaushik-rishi** [comment]
@Shurtu-gal :wave: I was thinking of working on this issue. 
Irrespective of it, we need to wait till the issue get's accepted i think.
We can work together on this as well if need be.

**Comment by jonaslagoni** [comment]
Anything that improves stuff or fixes something that's broken dont need to get accepted 🙂 Feel free to jump straight into it 💪

**Comment by Shurtu-gal** [comment]
> @Shurtu-gal wave I was thinking of working on this issue. Irrespective of it, we need to wait till the issue get's accepted i think. We can work together on this as well if need be.
> 
> It could also be that @Bhavik-ag has already thought of working on it.

Sure, thing. 😸

**Comment by sambhavgupta0705** [comment]
Hey,you all may improve it for the desktop view also and may add bullet indentation and search feature.
May take inspiration from https://www.asyncapi.com/docs
