### ISSUE TITLE
Add PHP Generator to Modelina Playground

### ISSUE THREAD

**Issue by Ferror** [asyncapi/modelina#1328]
Next step of making PHP Generator great should be enabling it in playground, so users can test it out: https://modelina.org/playground

**Comment by kaushik-rishi** [comment]
I'll work on it. 🙂
As far as I remember there are no options for PHP generator as of now right ?

**Comment by jonaslagoni** [comment]
I actually added it here 😄 https://github.com/asyncapi/modelina/pull/1306/
