### ISSUE TITLE
Add runtime testing for Kotlin

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#1334]
#### Reason/Context
In https://github.com/asyncapi/modelina/pull/1272 we added the initial runtime setup for Java, now it's time to replicate it for Kotlin.

The reason we add these is to ensure that the code that is generated is semantically and syntactically correct, and the only way to achieve this is by testing the models at runtime.

This initial setup should be as simple as possible, just a Kotlin project, with a single test and a single generated model, and that's it.

Here is the general task list:

- [ ] Create a Kotlin project under; `test/runtime/runtime-kotlin`
- [ ] Add a simple test code generation script here: `test/runtime/runtime-kotlin.ts`. Check out the Java variant as an example https://github.com/asyncapi/modelina/blob/master/test/runtime/runtime-java.ts
- [ ] Add the generation script to the package file: https://github.com/asyncapi/modelina/blob/ba0bd41e9803394f56872c5ec92f8e335a4d687a/package.json#L98
- [ ] Run the generation script
- [ ] Manually add a simple test for the generated models, could be as simple as just creating an instance of it.
- [ ] Add a simple Jest script, which just execute the Kotlin test: https://github.com/asyncapi/modelina/blob/master/test/runtime/runtime-java.spec.ts
- [ ] Add a simple script that will run the test: https://github.com/asyncapi/modelina/blob/ba0bd41e9803394f56872c5ec92f8e335a4d687a/package.json#L97
- [ ] Create a CI workflow that runs the runtime tests: https://github.com/asyncapi/modelina/blob/master/.github/workflows/runtime-java-testing.yml

And that's it 🎉

**Comment by SumantxD** [comment]
@jonaslagoni I would like to work on this issue.

**Comment by SumantxD** [comment]
@jonaslagoni i tried solving this issue in the PR https://github.com/asyncapi/modelina/pull/1357 , can you take a look !! :smiley:

**Comment by HimanshuMahto** [comment]
hey would like to work on this issue
