### ISSUE TITLE
Add runtime testing for C++

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#1335]
#### Reason/Context
In https://github.com/asyncapi/modelina/pull/1272 we added the initial runtime setup for Java, now it's time to replicate it for C++.

The reason we add these is to ensure that the code that is generated is semantically and syntactically correct, and the only way to achieve this is by testing the models at runtime.

This initial setup should be as simple as possible, just a C++ project, with a single test and a single generated model, and that's it.

Here is the general task list:

- [ ] Create a C++ project under; `test/runtime/runtime-cplusplus`
- [ ] Add a simple test code generation script here: `test/runtime/runtime-cplusplus.ts`. Check out the Java variant as an example https://github.com/asyncapi/modelina/blob/master/test/runtime/runtime-java.ts
- [ ] Add the generation script to the package file: https://github.com/asyncapi/modelina/blob/ba0bd41e9803394f56872c5ec92f8e335a4d687a/package.json#L98
- [ ] Run the generation script
- [ ] Manually add a simple test for the generated models, could be as simple as just creating an instance of it.
- [ ] Add a simple Jest script, which just execute the C++ test: https://github.com/asyncapi/modelina/blob/master/test/runtime/runtime-java.spec.ts
- [ ] Add a simple script that will run the test: https://github.com/asyncapi/modelina/blob/ba0bd41e9803394f56872c5ec92f8e335a4d687a/package.json#L97
- [ ] Create a CI workflow that runs the runtime tests: https://github.com/asyncapi/modelina/blob/master/.github/workflows/runtime-java-testing.yml

And that's it 🎉

**Comment by kaushik-rishi** [comment]
I would like to work on this issue.

**Comment by DanielXing1103** [comment]
Hi, in AddressTest.Java line 18, where is the Address variable imported from?

**Comment by jonaslagoni** [comment]
It is the auto generated models from Modelina 🙂

**Comment by codingmickey** [comment]
Hi @jonaslagoni I would like to work on this issue but would need some time and help(if required), as it's the first time I'm contributing to this repo and Async API in general!

**Comment by jonaslagoni** [comment]
Happy to help @codingmickey, shoot any question if you get stuck or want additional guidance 🙂

**Comment by codingmickey** [comment]
Hi @jonaslagoni, I'm almost done with the testing part do you have any idea about c++ json usage?

I'm getting this error while parsing the optional properties into the json library that I imported into c++

Any clues?

![image](https://github.com/asyncapi/modelina/assets/42518907/ddd5afc5-4100-46e2-8ea5-a32961f54ba4)

![image](https://github.com/asyncapi/modelina/assets/42518907/284e68d6-3d44-4b56-a8f1-2587bbe36244)

**Comment by jonaslagoni** [comment]
I have no idea @codingmickey 😆 Try create a draft PR that shows the error, then it's easier to get feedback and ask people for help on the issue 🙂
