### ISSUE TITLE
Add runtime testing for PHP

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#1336]
#### Reason/Context
In https://github.com/asyncapi/modelina/pull/1272 we added the initial runtime setup for Java, now it's time to replicate it for PHP.

The reason we add these is to ensure that the code that is generated is semantically and syntactically correct, and the only way to achieve this is by testing the models at runtime.

This initial setup should be as simple as possible, just a PHP project, with a single test and a single generated model, and that's it.

Here is the general task list:

- [ ] Create a PHP project under; `test/runtime/runtime-php`
- [ ] Add a simple test code generation script here: `test/runtime/runtime-php.ts`. Check out the Java variant as an example https://github.com/asyncapi/modelina/blob/master/test/runtime/runtime-java.ts
- [ ] Add the generation script to the package file: https://github.com/asyncapi/modelina/blob/ba0bd41e9803394f56872c5ec92f8e335a4d687a/package.json#L98
- [ ] Run the generation script
- [ ] Manually add a simple test for the generated models, could be as simple as just creating an instance of it.
- [ ] Add a simple Jest script, which just execute the PHP test: https://github.com/asyncapi/modelina/blob/master/test/runtime/runtime-java.spec.ts
- [ ] Add a simple script that will run the test: https://github.com/asyncapi/modelina/blob/ba0bd41e9803394f56872c5ec92f8e335a4d687a/package.json#L97
- [ ] Create a CI workflow that runs the runtime tests: https://github.com/asyncapi/modelina/blob/master/.github/workflows/runtime-java-testing.yml

And that's it 🎉

**Comment by jonaslagoni** [comment]
@ferror anything you can help with?

**Comment by Ferror** [comment]
@jonaslagoni I think I can take over it. I think I did something similar here:


https://github.com/asyncapi/modelina/pull/1289/files#diff-02706382835cf595160af53888f2ef8e37779ffa35e5a8ebb59c95e547b1e79dR72

the `php -l` lints the php file and ensures that is semantically correct and will at least run 😄
