### ISSUE TITLE
Improve the code generator functions

### ISSUE THREAD

**Issue by kaushik-rishi** [asyncapi/modelina#1338]
#### Reason/Context
The current code generators we have under 
https://github.com/asyncapi/modelina/tree/master/modelina-website/src/helpers/GeneratorCode are working based on template literals, they donot update the imports of presets, using regular expressions to replace new lines, joining presets using ',' and performing logics based on length of presets array IMHO is degrading the quality and understandability of the code (although it's very readable).

#### Description
Please try answering few of those questions
- What changes have to be introduced?
     - We must update the imports as well
     - Use a better methodology to generate the javascript generator code which could eliminate the usage of regular expressions and ad-hoc array length based logic and worry about tab spacing and new line characters.
- Will this be a breaking change? No
- How could it be implemented/designed?
     - Add imports as well to the code generator
     - We can use a [JS formatter API](https://prettier.io/docs/en/api.html#prettierformatsource-options) and make the code generation more cleaner
In place of [this](https://gist.github.com/kaushik-rishi/98d89c493cd06c7dc5a47210f96daae6), we could have better code looking like this

```js
import { ModelinaCSharpOptions } from '../../types';
import { format } from 'prettier/standalone';
import parserBabel from 'prettier/parser-babel';

export function getCSharpGeneratorCode(
  generatorOptions: ModelinaCSharpOptions
) {
  const optionString: string[] = [];
  const optionStringPresets: string[] = [];
  const importsString: string[] = [];

  if (generatorOptions.csharpArrayType) {
    optionString.push(`collectionType: '${generatorOptions.csharpArrayType}'`);
  }
  if (generatorOptions.csharpAutoImplemented) {
    optionString.push(`autoImplementedProperties: ${generatorOptions.csharpAutoImplemented}`);
  }
  if (generatorOptions.csharpOverwriteHashcode) {
    importsString.push('CSHARP_COMMON_PRESET')
    optionStringPresets.push(`{
      preset: CSHARP_COMMON_PRESET,
      options: {
        equal: false,
        hashCode: true
      }
    }`)
  }

  if (generatorOptions.csharpIncludeJson) {
    importsString.push('CSHARP_JSON_SERIALIZER_PRESET')
    optionStringPresets.push('CSHARP_JSON_SERIALIZER_PRESET')
  }
  if (generatorOptions.csharpIncludeNewtonsoft) {
    importsString.push('CSHARP_NEWTONSOFT_SERIALIZER_PRESET')
    optionStringPresets.push('CSHARP_NEWTONSOFT_SERIALIZER_PRESET')
  }

  const presetOptions = optionStringPresets.length > 0 ? `presets: [${optionStringPresets.join(',')}]` : '';
  let fullOptions = '';
  if (optionStringPresets.length > 0 || optionString.length > 0) {
    fullOptions = `{ ${optionString.join(',')} , ${presetOptions} }`;
  }

  return format(`// Use the following code as starting point
    // To generate the models exactly as displayed in the playground
    import { CSharpGenerator, ${importsString.length ? importsString.join(',') : ''} } from '@asyncapi/modelina';

    const generator = new CSharpGenerator(${fullOptions});`, 
    {
      semi: true,
      trailingComma: "none",
      parser: "babel",
      plugins: [parserBabel],
    }
  );
}

``` 
- where the imports are working, as well as the formatting is taken care of without using tab spaces, new lines and regular expressions replace functions

**Comment by kaushik-rishi** [comment]
I specifically took the example of csharp because it has a lot of options and i've worked on adding a couple of them.

**Comment by kaushik-rishi** [comment]
@jonaslagoni Please let me know if this is a bad idea :slightly_smiling_face: 
Happy to take constructive criticism.

**Comment by kaushik-rishi** [comment]
Can find the working code here. https://github.com/kaushik-rishi/modelina/blob/feat-prettier-code-generation/modelina-website/src/helpers/GeneratorCode/CSharpGenerator.ts :slightly_smiling_face:

**Comment by jonaslagoni** [comment]
https://github.com/asyncapi/modelina/pull/1309 actually clean up a lot of the duplicate code and structure.

Generally, this code never changes so adding a new library just to replace 20 lines of code that rarely changes, does not seem that relevant IMO 🙂  

But it's also hard to see the full extent that it would simplify, so feel free to create a draft PR proposing the change if you feel it's a needed change 👍

**Comment by kaushik-rishi** [comment]
Pretty Hefty PR :smile: 
Gained some knowledge by reading the code changes.

I'll brainstorm again, i'm thinking if it's a neccessary change or not :thinking: 

Also, I'll probably open another issue, regarding adding the imports in Code generator, they're missing right there.

**Comment by jonaslagoni** [comment]
Closing as no further followup 🙂
