### ISSUE TITLE
Improve layout of playground

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#1346]
#### Reason/Context
It's starting to get a bit tight when it comes to how the playground layout is and I think it can be improved. 

I think can focus on these two areas:

1. With more and more options, it's taking up a lot of space.

![image](https://github.com/asyncapi/modelina/assets/13396189/9b9d3798-46cf-4a7c-8fa7-32c163859b85)

2. You can never fully see the generated models nor the input making it a weird experience. 
 
![image](https://github.com/asyncapi/modelina/assets/13396189/daf7861d-7791-44b6-abd9-2ce7193a19fa)

**Comment by codingmickey** [comment]
hi @jonaslagoni, I'm interested in this issue but have some questions before I can try it. Would it look good for 1 to create collapsing headers for the options that way we can save up the space once the user has configured their required options?

For the 2nd part will have to think of some ideas or just can we shift 2nd column to make it a tab switching just above the editor?

**Comment by jonaslagoni** [comment]
> Would it look good for 1 to create collapsing headers for the options that way we can save up the space once the user has configured their required options?

Might be 🤔 Just remember you quite often change between options and looking for the result i.e. how the options changed the outcome.

Not sure if this hinders the user experience? 

> For the 2nd part will have to think of some ideas or just can we shift 2nd column to make it a tab switching just above the editor?

Not sure i entirely get your suggestion 🤔 Can you clarify a bit more?

**Comment by codingmickey** [comment]
> Might be 🤔 Just remember you quite often change between options and looking for the result i.e. how the options changed the outcome.

Hmm yea, that is there but somewhat similar to [this](https://www.liquid-technologies.com/online-json-to-schema-converter) where the user can if needed open the options if not this will have to think about it

> Not sure i entirely get your suggestion 🤔 Can you clarify a bit more?

When using VSCode we have different files in tabs, likewise rather than the option can we configure such a thing?

![image](https://github.com/asyncapi/modelina/assets/42518907/389cbbe1-c0e7-432b-99c8-13cd6c767428)

**Comment by sambhavgupta0705** [comment]
[Screencast from 02-06-23 02:36:01 PM IST.webm](https://github.com/asyncapi/modelina/assets/81870866/7555c561-1584-4b3b-8a83-f28750ffefa7)

@jonaslagoni for the lower section we can have it like this

**Comment by jonaslagoni** [comment]
@sambhavgupta0705 I dont think this improves the layout 🤔 

My problems with this solution is that, 1) I can no longer edit the input and directly see the output, 2) it's hard to change the options and easily see the output.

I think we have to keep the input + output side by side, however in full-screen mode instead (mobile it's gonna suck regardless). Options might need to be a popup in someway, that you can open and close on the output model side 🤔 Not sure whats best here.

Any ideas?

**Comment by codingmickey** [comment]
> I think we have to keep the input + output side by side, however in full-screen mode instead (mobile it's gonna suck regardless). Options might need to be a popup in someway, that you can open and close on the output model side 🤔 Not sure whats best here.

Maybe just a simple modal just above the Generated Models title with a button? and lowering the font size on the editors also disabling mini map as it's (in my opinion) not needed because if needed to scroll would use just the mouse or the slider

**Comment by codingmickey** [comment]
Sure, would like to work on this!

**Comment by sambhavgupta0705** [comment]
@jonaslagoni ,we can implement something like this 
![image](https://github.com/asyncapi/modelina/assets/81870866/c812872a-80a7-4ddc-b816-e61fa15310f5)

**Comment by jonaslagoni** [comment]
> Sure, would like to work on this! How should we start?

Like any other contribution tbh 😄 Nothing special about this one.

**Comment by jonaslagoni** [comment]
@sambhavgupta0705 that unfortunately does not solve the layout problem with input and output not being next to each other.

**Comment by jonaslagoni** [comment]
I would 100% focus on that change first, and then we can figure out how to place the options

**Comment by sambhavgupta0705** [comment]
@jonaslagoni I think I am missing something here.
Can you please specify what's the input here??
\

**Comment by jonaslagoni** [comment]
@sambhavgupta0705 the input is what you see now in the playground on the left hand side. Where you can edit what is used to generate models

**Comment by sambhavgupta0705** [comment]
we can do something to use the whole screen,the white left and right space also??

**Comment by codingmickey** [comment]
Thought of the same but would lose the consistency of the website right? Of the left right spacing

**Comment by jonaslagoni** [comment]
To me it does not matter about consistency as the playground should be seen as an app in similar fashion as studio is.

**Comment by sambhavgupta0705** [comment]
okay @jonaslagoni so I think we should implement it as asyncapi.studio.com

**Comment by codingmickey** [comment]
> okay @jonaslagoni so I think we should implement it as asyncapi.studio.com

yea was also thinking something similar to Leetcode's layout. Having a Split view and adjusting the width along with it should do the job

**Comment by jonaslagoni** [comment]
@codingmickey more or less yea 😅

**Comment by sambhavgupta0705** [comment]
@jonaslagoni I asked the maintainers of the main website about how can we redesign it and it seems that we need to make a lot of changes in the layout as it has been fixed by a css file that it cannot go beyond the `star on github` button.

**Comment by jonaslagoni** [comment]
I think it's a oneliner fix @sambhavgupta0705 https://github.com/asyncapi/modelina/blob/c0e0268996126ca65caeaa6d4c3d4fbcef1767bc/modelina-website/src/pages/playground.tsx#L9

By passing `full`

**Comment by sambhavgupta0705** [comment]
> I think it's a oneliner fix @sambhavgupta0705
> 
> https://github.com/asyncapi/modelina/blob/c0e0268996126ca65caeaa6d4c3d4fbcef1767bc/modelina-website/src/pages/playground.tsx#L9
> 
> By passing `full`

ohhh yess it worked 😅

**Comment by sambhavgupta0705** [comment]
@jonaslagoni 

> @jonaslagoni what about this type of design ,the input and output side by side and the generate model option above them !

**Comment by codingmickey** [comment]
I was thinking something exactly same like the studio.. which has the options on the side to adjust the options and can show/hide the layouts.

Shall we work on this together? @sambhavgupta0705

**Comment by sambhavgupta0705** [comment]
> @sambhavgupta0705 yep thats look like the right direction

Thanks Jonas

> Shall we work on this together? @sambhavgupta0705

Yes we can

**Comment by sambhavgupta0705** [comment]
@jonaslagoni ,for the design proposed by me we need to import the `models to render` function https://github.com/asyncapi/modelina/blob/05210ba88b933baa67340ea11c57cd1a6a4be960/modelina-website/src/components/playground/GeneratedModels.tsx#L113
to `Playground.tsx ` file.
for which I need your suggestion that we should do this or not?

**Comment by sambhavgupta0705** [comment]
Other than that we can have this layout  where generated models will be a dropdown menu
![image](https://github.com/asyncapi/modelina/assets/81870866/21a94d3d-985d-491f-9ae5-6c69e1b4509e)

**Comment by sambhavgupta0705** [comment]
@jonaslagoni

**Comment by jonaslagoni** [comment]
Looks fine yea

**Comment by sambhavgupta0705** [comment]
@jonaslagoni does this look good??
![image](https://github.com/asyncapi/modelina/assets/81870866/1fa5a69f-4985-4485-921e-5f30070bc950)

**Comment by jonaslagoni** [comment]
@sambhavgupta0705 I think it's time that we force the full screen editor completely, and remove the options and stretch the editor on the left and models on the right all the way to the top navbar, i.e. we get something close to studio layout.

The options I think should be something that is hidden/shown from something like a sidebar? Maybe?

**Comment by sambhavgupta0705** [comment]
So far I have understand that we should replicate something like [studio.asyncapi.com](studio.asyncapi.com)
Have a sidebar which has items -> option,editor and more???

**Comment by sambhavgupta0705** [comment]
@jonaslagoni 😄

**Comment by jonaslagoni** [comment]
That would be nice yea, or at least options to start with 😄

**Comment by sambhavgupta0705** [comment]
Still relevant

**Comment by devilkiller-ag** [comment]
Hi, Can I also help in this issue?

**Comment by jonaslagoni** [comment]
Definitely @devilkiller-ag 👍

**Comment by devilkiller-ag** [comment]
Thanks @jonaslagoni, I read the above thread. What's the current status of the work? And from where should I start?

**Comment by jonaslagoni** [comment]
Have not seen any code yet, so I would assume that you are starting from scratch 🙂 

Where you should start? Depends on how you like to work I guess 😄 The way I would do it was to copy the current playground and then make changes in that file by slowly introducing a new layout before changing the logic 🙂

**Comment by devilkiller-ag** [comment]
Thanks @jonaslagoni. The plan seems great I will share a design wireframe and open a draft PR soon.

**Comment by devilkiller-ag** [comment]
One more question, should we keep the layout similar to Async Api Studio (https://studio.asyncapi.com/)

**Comment by jonaslagoni** [comment]
As described above, https://studio.asyncapi.com/ would probably be a better layout for showing models, input and options yea 😄

**Comment by devilkiller-ag** [comment]
Great, now I am ready to start 😁

**Comment by devilkiller-ag** [comment]
Hi @jonaslagoni, this is the rough wireframe that I have created for Modelina Studio, after studying the components of Modelina Playground and AsyncAPI Studio. 

![Screenshot from 2023-11-20 09-12-58](https://github.com/asyncapi/modelina/assets/43639341/3e9e0d1c-2fce-4228-946d-0b6c31a1a1d1)

The Options and Output Navigation will be in the same position which the user can switch using the buttons on the side panel. What's your opinion on this?

**Comment by jonaslagoni** [comment]
I think you can skip the outline completely, the input is only there for you to copy/paste an example to see the output fast. Not to edit inputs as Studio offers 🙂

**Comment by devilkiller-ag** [comment]
Okay, I will start coding now.

**Comment by devilkiller-ag** [comment]
While I run `npm run dev` to run the modelina-website locally. I got this error:

```
./src/pages/api/functions/CSharpGenerator.ts:2:0
Module not found: Can't resolve '../../../../../'
  1 | /* eslint-disable @typescript-eslint/no-unused-vars */
> 2 | import { CSharpGenerator, CSharpOptions, csharpDefaultEnumKeyConstraints, csharpDefaultModelNameConstraints, csharpDefaultPropertyKeyConstraints, CSHARP_COMMON_PRESET, CSHARP_JSON_SERIALIZER_PRESET, CSHARP_NEWTONSOFT_SERIALIZER_PRESET } from '../../../../../';
  3 | import { applyGeneralOptions, convertModelsToProps } from './Helpers';
  4 | import { ModelinaCSharpOptions, ModelProps } from '../../../types';
  5 | import { DeepPartial } from '../../../../../lib/types/utils';

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./src/pages/api/generate.ts
```

The error suggest that it can't find `import { CSharpGenerator, CSharpOptions, csharpDefaultEnumKeyConstraints, csharpDefaultModelNameConstraints, csharpDefaultPropertyKeyConstraints, CSHARP_COMMON_PRESET, CSHARP_JSON_SERIALIZER_PRESET, CSHARP_NEWTONSOFT_SERIALIZER_PRESET } from '../../../../../';`  The same error is for all the files in the `modelina-website/src/api/functions` folder. 

Do I need to generate or get these files from somewhere else?

Also I can't findthe "lib" containing tpyes folder for `import { DeepPartial } from '../../../../../lib/types/utils';`

**Comment by jonaslagoni** [comment]
@devilkiller-ag You have to build the library itself as well, before the website 🙂

**Comment by devilkiller-ag** [comment]
Hi @jonaslagoni, I am sorry, I am having a little trouble setting up this. I installed all packages for the library and website using 'npm i'. Did you mean building the library with the docker file with `npm run docker:build`? I did that too. Still facing the same issue. ( I followed all the steps mentioned in the doc [here](https://modelina.org/docs/development).)

I searched for the same error on Slack but didn't find it. 

Can you kindly guide me elaborately on where I am making mistakes and how I can build the library? Again sorry for asking silly questions.

**Comment by codingmickey** [comment]
Hey @devilkiller-ag did you read this https://github.com/asyncapi/modelina/tree/master/modelina-website#how-to-run-it before starting? run `npm run build:modelina` before running `npm run dev` to build the actual library which is powering the website.

My one advice would be to please go through any `README.md` in the project scope you're trying to contribute next time :)

(Also apologies @jonaslagoni, I wasn't able to help on this issue before.. as I caught up with some other work..)

**Comment by devilkiller-ag** [comment]
Thanks @codingmickey Now It's running successfully. Somehow I missed that command. I'll be sure to keep your suggestions in mind.

**Comment by devilkiller-ag** [comment]
I have created the draft PR and will start working on it now.
