### ISSUE TITLE
Add descriptions for options in playground

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#1347]
#### Reason/Context
Sometimes it would be great to provide a little information about the options and what they do because it's not self explanatory for example what this does: 

![image](https://github.com/asyncapi/modelina/assets/13396189/84b2b402-b1f1-4fc6-9d86-a110bd715820)

Maybe a tooltip, or just a simple label below the title of the option, not sure 🤔 Any ideas?

Think we can start with just getting the design down, apply it to a single option (i.e. adding a PR and getting it merged), and then subsequently go through each language and their options.

**Comment by sambhavgupta0705** [comment]
@jonaslagoni let's first do it for  `typescript` 

> Maybe a tooltip, or just a simple label below the title of the option, not sure thinking Any ideas?

IMO tooltip must be there

**Comment by SumantxD** [comment]
![Screenshot from 2023-06-01 23-52-50](https://github.com/asyncapi/modelina/assets/65810424/78fcb5a1-e6d0-41d7-b040-7fd7b9c29758)

**Comment by SumantxD** [comment]
we can also use a lightbulb icon instead , i can start working once the design is approved :smiley: 
cc: @jonaslagoni

**Comment by jonaslagoni** [comment]
Is the info icon a better user experience or worse than just displaying the description directly? Or having a on hover effect on the title 🤔? 

Feel free to make an educated guess and take a decision after that, I by no means have a preference here as long as it's a good user experience 😄

**Comment by SumantxD** [comment]
@jonaslagoni i think we should have both the options 
1) when the user hovers over it slightly longer than normal then the info should appear
    1.1) this will ensure that the info dialogue  box does not get annoying by appearing even on the slightest hover
2)  we should use light bulb icon instead of info icon as info icons might get interpreted as some sort of warning, which is usually displayed while filling forms , when the input format is not valid
3) when a user quickly want to display info about the option (without hovering) , he can click on the icon
    3.1) having a bulb icon  will remove the ambiguity as to whether there is additional information available or not and thus will provide a better user experience :smiley:

**Comment by jonaslagoni** [comment]
Sounds like a plan 👌

**Comment by jonaslagoni** [comment]
Done in https://github.com/asyncapi/modelina/issues/1392
