### ISSUE TITLE
Add package name option for playground

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#1352]
#### Reason/Context
In some generators, it's possible to define `packageName` as an option, and it should be possible to change the value in the playground.

It applies to the following generators:
- PythonGenerator
- KotlinGenerator
- JavaGenerator
- GoGenerator

You can read more about how the playground works here: https://github.com/asyncapi/modelina/blob/master/modelina-website/README.md#playground

**Comment by kaushik-rishi** [comment]
I'll pick it up @jonaslagoni

**Comment by kaushik-rishi** [comment]
@jonaslagoni Do you think we should have the package name option included in the query parameters ?

**Comment by jonaslagoni** [comment]
Definitely, same as all the other options 👍

**Comment by kaushik-rishi** [comment]
Working on it.

**Comment by kaushik-rishi** [comment]
@jonaslagoni do you suggest we have different variables for different `packageName` for each language in the context config ?

**Comment by jonaslagoni** [comment]
Yep,  I think it should be the same as namespace 🙂
