### ISSUE TITLE
Next + Netlify 404 page not showing

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#1360]
#### Describe the bug
In #1323 we added a 404 page that works locally, however with netlify integration, it does not work and gives us this error: 

<img width="1344" alt="image" src="https://github.com/asyncapi/modelina/assets/13396189/1da4669c-7883-48f3-971f-45710eaa375d">

**Comment by sambhavgupta0705** [comment]
@jonaslagoni well I tried many ways to resolve this but none worked.I think it is an deployment error or netlofy function error.

**Comment by Shurtu-gal** [comment]
Yeah, same bro @sambhavgupta0705

**Comment by Shurtu-gal** [comment]
> I guess this is a problem with integration regarding serverless functions in api directory of next js and the netlify next.js runtimes.

**Comment by sambhavgupta0705** [comment]
Yess the redirects command are also not working.

**Comment by sambhavgupta0705** [comment]
still relevant

**Comment by sambhavgupta0705** [comment]
still relevant

**Comment by Shurtu-gal** [comment]
Still relevant.

**Comment by Shurtu-gal** [comment]
Still Relevant

**Comment by devilkiller-ag** [comment]
> Hey @devilkiller-ag  !  I would like to work on this issue. 

Sure, Go ahead!!

**Comment by devilkiller-ag** [comment]
Hi @Shurtu-gal @jonaslagoni @sambhavgupta0705, do we still need to work on this I noticed that the 404 page is working properly now.

**Comment by sambhavgupta0705** [comment]
We can close this one then

**Comment by Shurtu-gal** [comment]
I don't know how this got fixed but good job netlify 👍🏻 .
I guess this can be closed then @jonaslagoni
