### ISSUE TITLE
Roadmap for C++ support

### ISSUE THREAD

**Issue by robinchrist** [asyncapi/modelina#1384]
Hey,

I would like to use Modelina for C++ and I'm getting ready to contribute to the C++ support.

But before I really get into it, I'd like to hear whether there's already some kind of roadmap?

I think the most important feature, which I'll be mainly working on, is (de)serialisation to and from JSON. I'd like to use the yyjson library for that, because it is fast (to the level of SIMDJSON, but without the SIMD hassles), powerful and MIT licensed.

**Comment by jonaslagoni** [comment]
There is not, so you can see it as a blank slate, your own drawing board 😄 

If you want a specific library for serialization go for it, if others want a different one, they can contribute a different preset, so no worries 👍

**Comment by oavitzur** [comment]
Hi
Im looking for a way to generate from asyncapi yml, message payloads in json format, similar to what is done for programming languages using modelina.
I saw above that @robinchrist  might have some information on this issue. Is this correct ?

Thanks!

**Comment by jonaslagoni** [comment]
Closing as no further involvement 🙂
