### ISSUE TITLE
Add descriptions for options in playground continued..

### ISSUE THREAD

**Issue by SumantxD** [asyncapi/modelina#1392]
Continuing from issue #1347, where the design and implementation details were discussed 
and finalized, let's now outline the following tasks at hand:
- [X] discuss and finalize what needs to be added as info for the [general options](https://modelina.org/playground)
- [X] TypeScript Specific options
- [ ] CSharp Specific options
- [ ] PHP Specific options
- [ ] C++ Specific options
- [ ] Info about package name option for (Java, go , kotlin)

**Comment by SumantxD** [comment]
> @SumantxD @jonaslagoni Can I help out some way?

sure you can take TypeScript Specific options.

**Comment by jonaslagoni** [comment]
Just a "pro" tip, you can use the examples and documentation to find the description of each option.

If you are in doubt about a specific one, just use a placeholder and raise the PR, then we can help narrow it down 🙂

**Comment by SumantxD** [comment]
# General Options

- Include change type mapping example
    - In code generation, a common task is to map the data types from the input model to the output code. One approach to accomplish this is by using type mapping. Type mapping is the process of mapping a data type in the input model to a corresponding data type in the output code.
    - Change type mapping refers to the process of transforming one data type to another data type. This is a common technique in programming when data types need to be converted to make them compatible with another system or process
- Change indentation type
    - The indentation type option allows you to choose between using tabs or spaces for indentation in the generated code.
- Change property naming format
    - This option allows you to customize the naming style for properties in your code. It provides several options to choose from:
        - Default: This option refers to the default naming format for properties, which may vary depending on the programming language or coding convention being used.

        - Snake case: Property names are written in lowercase letters, and words are separated by underscores. (e.g: property_name)

        - Pascal case: Property names start with an uppercase letter, and subsequent words are also capitalized. (e.g: PropertyName)

        - Camel case: Property names start with a lowercase letter, and subsequent words are capitalized. (e.g: propertyName)

        - Param case: Property names use hyphens to separate words, and all letters are in lowercase. (e.g: property-name)

        - Constant case: Property names are written in uppercase letters, and words are separated by underscores. (e.g: PROPERTY_NAME)
- Change model naming format
    - This option allows you to modify the naming style for models in your code. It includes the following options
        - Default: This option refers to the default naming format for models, which may vary depending on the programming language or coding convention being used. 

        - Snake case: Model names are written in lowercase letters, and words are separated by underscores. (e.g: model_name)

        - Pascal case: Model names start with an uppercase letter, and subsequent words are also capitalized. (e.g: ModelName)

        - Camel case: Model names start with a lowercase letter, and subsequent words are capitalized. (e.g: modelName)

        - Param case: Model names use hyphens to separate words, and all letters are in lowercase. (e.g: model-name)

        - Constant case: Model names are written in uppercase letters, and words are separated by underscores. (e.g: MODEL_NAME)
- Change enum key naming format
    - This option allows you to customize the naming style for keys within your enum declarations. It provides several options to choose from:
        - Default: This option refers to the default naming format for enum keys, which may vary depending on the programming language or coding convention being used.

        - Snake case: Enum key names are written in lowercase letters, and words are separated by underscores. (e.g: enum_key)

        - Pascal case: Enum key names start with an uppercase letter, and subsequent words are also capitalized. (e.g: EnumKey)

        - Camel case: Enum key names start with a lowercase letter, and subsequent words are capitalized. (e.g: enumKey)

        - Param case: Enum key names use hyphens to separate words, and all letters are in lowercase. (e.g: enum-key)

        - Constant case: Enum key names are written in uppercase letters, and words are separated by underscores. (e.g: ENUM_KEY)
        
        cc: @jonaslagoni  @Shurtu-gal  any suggestions or changes on this !! :slightly_smiling_face:

**Comment by codingmickey** [comment]
I can also help with this @jonaslagoni @SumantxD

**Comment by jonaslagoni** [comment]
@SumantxD please go ahead and start the PR, it is much easier reviewing it there then discussing it here 🙂

**Comment by jonaslagoni** [comment]
@codingmickey feel free to grab C# or PHP, I think those are the main ones with options atm 👍

**Comment by SumantxD** [comment]
> @codingmickey feel free to grab C# or PHP, I think those are the main ones with options atm +1

@codingmickey :+1:

**Comment by Shurtu-gal** [comment]
Hey @codingmickey, could you tell which ones you are currently working on?

**Comment by codingmickey** [comment]
> Hey @codingmickey, could you tell which ones you are currently working on?

Sorry for the late reply, I was on vacation.. I can work on C# haven't started any

**Comment by Shurtu-gal** [comment]
Okay, I will do the PHP then.
@SumantxD If you are free could you take up the c++ ones.

**Comment by jonaslagoni** [comment]
Still relevant 🙂

**Comment by jonaslagoni** [comment]
As I see this issue is done 🙂 Thank you all for helping make this happen 💪
