### ISSUE TITLE
Add Java options to the playground

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#1396]
#### Reason/Context
There is a bunch of Java options currently not available in the playground when they should be.

We are talking about all the options here: https://github.com/asyncapi/modelina/blob/master/docs/languages/Java.md

We have multiple issues highlighting how to add options to the playground, only difference is that now it's for Java, instead of here C#: https://github.com/asyncapi/modelina/issues/1375

**Comment by SumantxD** [comment]
@jonaslagoni i would like to take this issue !! :slightly_smiling_face:
