### ISSUE TITLE
Should offical presets should be added as include options?

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#1397]
#### Reason/Context
I am starting to be annoyed with having to do:
```
new TypeScriptFileGenerator({
    presets: [
      {
        preset: TS_COMMON_PRESET,
        options: {
          marshalling: true
        }
      }
    ]
  });
```
each time I want to include marshaling functions (general pain point across all presets and output languages, not specifically for TS ad marshalling).

I think it makes sense that we start to hide the underlying preset architecture, to improve the developer experience at least where possible. That would mean we reduce the code above to:
```
new TypeScriptFileGenerator({
    includeMarshalling: true
  });
```
What do you think? would that improve the overall experience? Or is it better to force the user to use presets and get familiar with them?

**Comment by kaushik-rishi** [comment]
Yes, it makes complete sense to hide the internal preset architecture.

**Comment by jonaslagoni** [comment]
@kaushik-rishi because presets are such a central peace of functionality, hiding it away behind simple options means fewer people will know about it.

On the other side, it simplifies the UX a lot.

**Comment by rukundob451** [comment]
@jonaslagoni @kaushik-rishi what about introducing a more concise syntax, such as `includeMarshalling: true`, can certainly enhance the overall experience for developers the complexity and allows developers to focus on the specific functionality they need without having to navigate preset configurations.

**Comment by jonaslagoni** [comment]
Closing, as unless there is an overwhelming need for it to not add too many abstractions.
