### ISSUE TITLE
Improve navbar for the mobile view

### ISSUE THREAD

**Issue by SumantxD** [asyncapi/modelina#1402]
As of now if the user is in the mobile view of the modelina website and wants to switch form 'examples' to 'playground' or vice-versa through navbar, then he will have to click on top of the word, which is bad in terms of UX as it is located on the left side of the view , and the options to operate the view is located on the right side ('the burger menu icon and the cross button')

* in order to fix that i have made it clickable through it's entire length and also added a grey background to make the clickable are more obvious
* on top of that i have also added the feature of words getting highlighted on hover.

**Comment by sambhavgupta0705** [comment]
@SumantxD Please close this issue
