### ISSUE TITLE
Improve the example display name

### ISSUE THREAD

**Issue by sambhavgupta0705** [asyncapi/modelina#1417]
#### Reason/Context
Please try answering few of those questions
- Why we need this improvement?
  To improve the UI of the examples page
- How will this change help?
  It will improve the UI

#### Description
Please try answering few of those questions
- What changes have to be introduced?
 A small changes of docs 
- Will this be a breaking change?
  No

![image](https://github.com/asyncapi/modelina/assets/81870866/867c19ca-8d02-4ba2-9e4a-1bef5b9e66d9)

In this we can remove dash and make the first letter capital

![image](https://github.com/asyncapi/modelina/assets/81870866/72be3d34-893d-469f-9885-5fdbd39e763c)

**Comment by jonaslagoni** [comment]
These names are directly taken from the directory names, so this task is coding related.
