### ISSUE TITLE
Nullable types in golang

### ISSUE THREAD

**Issue by wiegell** [asyncapi/modelina#1418]
#### Reason/Context
Please try answering few of those questions
- Why we need this improvement?
Nullable strings are vital in many languages, also in go! In our current project we have put a lot of effort to support nullability between frontend and bff (graphql) - if it cannot be kept between services (asyncapi), it's a dealbreaker!
Currently `type: ["integer", "null"]` is translated to `interface{}` which is not typesafe. Other generators, e.g. https://github.com/99designs/gqlgen solves the problem by converting optional primitives to pointers, which are nullable. E.g. a type `string` becomes type `*string`.

https://github.com/asyncapi/modelina/commit/53edd32fcbc2dde8f9f36a0d344e2abc45b1fec2
This change addresses nullable types in typescript - could it be expanded to go?

#### Description
Please try answering few of those questions
- Will this be a breaking change?
Yes

**Comment by jonaslagoni** [comment]
@wiegell thanks for opening the issue!

As I am not that well versed in Go, hope you don't mind answering some questions 😅 Is it ALL types that just need `*type` for it to be nullable?

v2 actually can handle this, we just need to alter a few lines of code for the type generation 🙂

**Comment by wiegell** [comment]
Yes all pointers (*) are nullable, but some value types can also be nil.

See this proposal: https://github.com/golang/go/issues/30177

_Motivation -> 2nd bullet_ explains using a pointer to simulate nullable.
_Proposal -> first bullet list_ is a list of types that cannot be nil.

So it would be needed to add * to the golang type corresponding to a nullable version of the following asyncapi types:
string
number
integer
boolean
object

I presume asyncapi _array_ type is translated to golang _slice_ (which is nullable in contrast to a golang _array_ of fixed length), so in that case a value type without * will suffice.

I'm not with my computer the next couple of days, but i would like to check if my reasoning here checks out with the graphql generator mentioned above, and i'll get back to you!

**Comment by zekth** [comment]
As a really good example you can check this project for struct generation: https://github.com/deepmap/oapi-codegen

But we also need to take care of non required with the `omitempty` struct tag:  https://pkg.go.dev/encoding/json#Marshal

**Comment by wiegell** [comment]
So i just checked with openapi - they use string pointers for non-required fields as well and then value types when the string is required.

**Comment by arthurspa** [comment]
I started using AsyncAPI generation for Go and found this current limitation, which is a deal breaker for me as well.

**Comment by arthurspa** [comment]
Thanks @jonaslagoni for pointing out the file. I'll take a look at that some time this week.

**Comment by arthurspa** [comment]
Just an update: I ended up writing my own template and made a quick fix for the nullable types I needed, which is not worth sharing since it's more a hack than a proper solution. So I won't spend time with this ticket, unfortunately.
