### ISSUE TITLE
TypeScript: marshalling of `additionalProperties` properties is naive

### ISSUE THREAD

**Issue by moltar** [asyncapi/modelina#1435]
#### Describe the bug

It looks like nested models get a simple `JSON.stringify` treatment and thus result in stringifying the internal/private (`_foo`) props, rather than public names.

#### How to Reproduce

1. Use a JSON Schema with a `additionalProperties` option. I am using a JSON Schema for [GitHub Actions Workflows](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/github-workflow.json).
2. Create a TS generator with `modelType: 'class'` and `marshalling: true` options
3. Run generator
4. Observe that nested marhsalling code simply looks like:

```ts
export class SgJobs {
  private _additionalProperties?: Map<string, SgNormalJob | SgReusableWorkflowCallJob>;

  constructor(input: {
    // ⚠️ ➡️                           👇🏻 type is known
    additionalProperties?: Map<string, SgNormalJob | SgReusableWorkflowCallJob>,
  }) {
    this._additionalProperties = input.additionalProperties;
  }

  get additionalProperties(): Map<string, SgNormalJob | SgReusableWorkflowCallJob> | undefined { return this._additionalProperties; }
  set additionalProperties(additionalProperties: Map<string, SgNormalJob | SgReusableWorkflowCallJob> | undefined) { this._additionalProperties = additionalProperties; }

  public marshal() : string {
    let json = '{'
    if(this.additionalProperties !== undefined) { 
    for (const [key, value] of this.additionalProperties.entries()) {
      //Only unwrap those who are not already a property in the JSON object
      if(Object.keys(this).includes(String(key))) continue;
        // ⚠️ ➡️                                                                               👇🏻 calls JSON.stringify naively
        json += `"${key}": ${typeof value === 'number' || typeof value === 'boolean' ? value : JSON.stringify(value)},`;
      }
    }

    //Remove potential last comma 
    return `${json.charAt(json.length-1) === ',' ? json.slice(0, json.length-1) : json}}`;
  }
```

#### Expected behavior

Probably needs to call `.marhsal()` if it is a known model object

**Comment by jonaslagoni** [comment]
Sorry for the delay in response @moltar, currently on Holiday 😄 

I think https://github.com/asyncapi/modelina/pull/1197 should have solved this, what version of Modelina are you using? `1.3.1` and `next` should contain the fix 🤔

**Comment by moltar** [comment]
I was using `2.0.0-next.14`, and on the PR, it says that the fix was included in `2.0.0-next.6`.

**Comment by jonaslagoni** [comment]
Might be an issue with the additional properties then 🤔

**Comment by jonaslagoni** [comment]
Ill have a look once I get back next week 🙂

**Comment by jonaslagoni** [comment]
@duckling69 maybe you wanna have a go at this issue?

**Comment by jonaslagoni** [comment]
Tracing this back to dictionary types, all dictionary types actually regardless of whether its for additionalProperties or something else.

Working on a fix
