### ISSUE TITLE
Java: enable nullable models doesn't support double

### ISSUE THREAD

**Issue by dlkj** [asyncapi/modelina#1438]
#### Describe the bug
Nullable models, implemented by #1141 doesn't support doubles correctly

#### How to Reproduce

Properties that are non-nullable and of type `float` should create a property of `double` not `Double` when rendering java models.

This can be seen on multiple tests including `test/generators/java/__snapshots__/JavaGenerator.spec.ts`

#### Expected behavior

`double` should be used for non-nullable floats

**Comment by jonaslagoni** [comment]
@dlkj I guess this have been fixed right?

**Comment by dlkj** [comment]
Yes, fixed by #1439
