### ISSUE TITLE
api docs page error

### ISSUE THREAD

**Issue by sambhavgupta0705** [asyncapi/modelina#1445]
#### Describe the bug
So when I go to dos/api and click on `asyncapi modelin` image present in the front page it redirects to the main page but it stays in the api docs url only 
You can see it clearly in screenshot

#### How to Reproduce
Steps to reproduce the issue. Attach all resources that can help us understand the issue:

- Screenshots
![image](https://github.com/asyncapi/modelina/assets/81870866/821ce33a-405b-466b-8713-a95eb314678d)

**Comment by aryanas159** [comment]
@sambhavgupta0705  Any idea how to manipulate the generated index.html file from the command "npm run docs:api"

**Comment by jonaslagoni** [comment]
I think the only way to solve this is by adopting a custom readme frontpage for the API docs with no external links instead of using the default README.md file 🤔 It's because of the iframe it's embedded in, no way for it to escape it.

Technically it should not contain much I think
