### ISSUE TITLE
TypeScript generator doesn't work with inheritance

### ISSUE THREAD

**Issue by Fyzu** [asyncapi/modelina#1446]
#### Describe the bug
When I turn inheritance to enabled, the TypeScript generator turns the type into `any` type. 

```ts
type KeepaliveMessage = any;
export { KeepaliveMessage };
```

#### How to Reproduce
Generator settings:
```js
const generator = new TypeScriptFileGenerator({
  modelType: 'interface',
  enumType: 'union',
  presets: [
    TS_DESCRIPTION_PRESET,
  ],
  processorOptions: {
    interpreter: {
      allowInheritance: true,
      ignoreAdditionalProperties: true,
    },
  },
})
```

Async API schema:
```yml
components:
  schemas:
    Message: 
      description: "Supertype message."
      type: object
      required: [type, channel]
      properties:
        type:
          type: string
        channel:
          type: number

messages:
  KeepaliveMessage:
    payload:
      $id: KeepaliveMessage
      allOf:
        - $ref: "#/components/schemas/Message"
        - type: object
          required: [type, channel]
          properties:
            type:
              const: KEEPALIVE
            channel:
              type: number
              const: 0
```

#### Expected behavior
I expect there to be an inheritance:
```ts
interface KeepaliveMessage extends Message {
  type: "KEEPALIVE";
  channel: 0;
};
export { KeepaliveMessage };
```

**Comment by jonaslagoni** [comment]
Yea, the option is a relic from the beginning that should be removed as inheritance is yet to be supported.

**Comment by jonaslagoni** [comment]
As of the `next` branch, this should be solved as part of https://github.com/asyncapi/modelina/pull/1613 by @kennethaasan 

@Fyzu feel free to re-open if it's not the case!

**Comment by kennethaasan** [comment]
I don't think it will work as expected in the `next` branch because I was focusing on Java as part of #1593, but the preparation I did in #1613 should make it quite easy to support inheritance in TS. @Fyzu, please consider making a PR to support inheritance in TS 🙏
