### ISSUE TITLE
Constants are compiled as enums

### ISSUE THREAD

**Issue by Ksisa** [asyncapi/modelina#1471]
#### Describe the bug
If I have a value that's a constant on an object, it will get compiled into an anonymous schema. This overcomplicates things by a lot.

Input:
```yaml
    TradeMessageClient:
      name: Trade Message (client)
      title: Trade Message (client)
      description: A message containing trade data
      payload:
        title: TradePayloadClient
        type: object
        properties:
          operation:
            type: string
            const: Trade
          data:
            $ref: '#/components/schemas/TradeClient'
        additionalProperties: false
        required:
          - operation
          - data
```

Expected TypeScript output:
```typescript
interface TradePayloadClient {
  operation: "Trade"
  data: TradeClient;
}
```

Actual Typescript Output:
```typescript
interface TradePayloadClient {
  operation: AnonymousSchema_11;
  data: TradeClient;
}
enum AnonymousSchema_11 {
  TRADE = "Trade",
}
```

Expected C# output:
```c#
public class TradePayloadClient
{
    public const string Operation = "Trade";
    public TradeClient? Data { get; set; }
}
```

Actual C# output:
```c#

public class TradePayloadClient
  {
    public AnonymousSchema_11? Operation { get; set; }
    public TradeClient? Data { get; set; }
  }

public enum AnonymousSchema_11
  {
    TRADE
  }

  public static class AnonymousSchema_11Extensions
  {
    public static string? GetValue(this AnonymousSchema_11 enumValue)
    {
      switch (enumValue)
      {
        case AnonymousSchema_11.TRADE: return "Trade";
      }
      return null;
    }

    public static AnonymousSchema_11? ToAnonymousSchema_11(string? value)
    {
      switch (value)
      {
        case "Trade": return AnonymousSchema_11.TRADE;
      }
      return null;
    }
  }
```

**Comment by jonaslagoni** [comment]
@Ksisa try and switch over to the `next` version, it has this updated 🙂

**Comment by Ksisa** [comment]
@jonaslagoni I get this now, which is invalid

```typescript
interface TradePayloadClient {
  operation: 'Trade' = 'Trade';
  data: TradeClient;
}
```

**Comment by jonaslagoni** [comment]
> @jonaslagoni for Typescript, I get this, which is invalid

How is that input invalid? 🤔 

> And for C#, it doesn't retain the constant's value
Yea C# still need a few things

**Comment by Ksisa** [comment]
@jonaslagoni It's an interface, variables can't be initialized like that. 
![image](https://github.com/asyncapi/modelina/assets/53404771/33d5d479-e301-4bb8-9ec4-01f8f1291151)

**Comment by Ksisa** [comment]
Yeah, I can take a look tomorrow evening.

**Comment by jonaslagoni** [comment]
@Ksisa wanna have a look at the c# generator as well?

It is slightly more complicated than your last PR.

First part is implementing the constant constrainer for C#: https://github.com/asyncapi/modelina/blob/next/src/generators/csharp/constrainer/ConstantConstrainer.ts you can use the [TypeScript constant constrainer as a guideline](https://github.com/asyncapi/modelina/blob/next/src/generators/typescript/constrainer/ConstantConstrainer.ts).

Then in the generator, you just need to adapt the property rendering using the `.options.const.value` value, by altering it here: https://github.com/asyncapi/modelina/blob/33c66a4b2ea99bbcbfd8d2c8155be3cb9c746547/src/generators/csharp/renderers/ClassRenderer.ts#L123

**Comment by Ksisa** [comment]
@jonaslagoni what is the constant constrainer used for? I can see the Java ConstantConstrainer is identical to the TypeScript one, so I'm tempted to just copy paste it, especially since Java is syntactically very similar to C#.

**Comment by jonaslagoni** [comment]
> @jonaslagoni what is the constant constrainer used for? I can see the Java ConstantConstrainer is identical to the TypeScript one, so I'm tempted to just copy paste it, especially since Java is syntactically very similar to C#.

It renders the constant value in language at hand. Some languages will overlap in that others will be unique. So it's vary possible that the implementation is gonna be the same or very similar between them 🙂

**Comment by moritzkalwa** [comment]
@jonaslagoni Is const only implemented for strings? 🤔 If so, should there be a check on the property type in the generator so we don't generate junk (e.g. `private const double property = undefined`)?
