### ISSUE TITLE
It should be possible to generate TypeScript interfaces without "reserved" prefix for special keywords

### ISSUE THREAD

**Issue by trevordixon** [asyncapi/modelina#1475]
Instead of generating, for example `reservedStatic`, it could simply quote the property name:

```
interface PayloadFoo {
  'static': string;
  'status': string;
}
```

How hard is it to get this behavior right now?

**Comment by jonaslagoni** [comment]
Super easy, There two ways, this one is probably the best approach, overwriting constraint logic (ignoring reserved keywords) and then overwriting the default rendering of interfaces and the property to follow your syntax `'static': string;`

```ts
const generator = new TypeScriptGenerator({
  constraints: {
    propertyKey: typeScriptDefaultPropertyKeyConstraints({
      // Ignore reserved keywords for properties entirely
      NO_RESERVED_KEYWORDS: (name) => { return name; }
    })
  },
  modelType: 'interface',
  defaultPreset: {
    interface: {
      property: ({property}) => {
        return `'${property.propertyName}': ${property.property.type};`
      }
    }
  }
});
```

Alternatively, a smaller but a little more hacky approach is just using the unconstrained property name as such:

```ts
const generator = new TypeScriptGenerator({
  modelType: 'interface',
  defaultPreset: {
    interface: {
      property: ({property}) => {
        return `'${property.unconstrainedPropertyName}': ${property.property.type};`
      }
    }
  }
});
```

And that's it 🙂 

I wonder if it makes sense to make this the default outcome for interfaces? 🤔 Is there any downside you see @trevordixon?

**Comment by trevordixon** [comment]
Thank you so much! That helps a ton. No downside to doing this by default
as far as I know. It seems possible to do with classes too by the way.

```
class Foo {
  get 'static'() { return 1; }
}
(new Foo).static;
```

I think this would be preferable as well for classes, though not as huge a
deal with generated marshal/unmarshal. But with interfaces, it's critical
for me that the interface describes what's actually coming down the wire.

**Comment by jonaslagoni** [comment]
Solved in https://github.com/asyncapi/modelina/pull/1729
