### ISSUE TITLE
[v3] Support multiple parser-api versions for AsyncAPI inputs 

### ISSUE THREAD

**Issue by smoya** [asyncapi/modelina#1493]
#### Reason/Context
In order to maximize compatibility, we need to accept AsyncAPI inputs in ""any"" of the Parser-API versions. See https://github.com/asyncapi/parser-js/issues/848.

#### Description
Use https://github.com/smoya/multi-parser-js in order to convert AsyncAPI inputs that are not compatible with the parser-api version in use in the installed parser-js package.

**Comment by jonaslagoni** [comment]
Solved 🙂
