### ISSUE TITLE
TypeScript: attribute mapping in generated interface is incorrect

### ISSUE THREAD

**Issue by dansiemens1** [asyncapi/modelina#1503]
#### Describe the bug
I have attributes in my AsyncApi file that are of the format:
`aa_00_fooBar`

After using `TypeScriptGenerator` to generate the interfaces, the outputs in the generated interface are of the format:
`aa_00FooBar`

As visible, the second `_` is missing, with the following string title-cased instead of camel-cased. 

#### How to Reproduce

Version `1.9.0`

##### Code to generate a typescript file with the generated interfaces:

```
import { TypeScriptGenerator } from "@asyncapi/modelina";
import { createWriteStream, readFileSync, unlinkSync } from "fs";

const OUTPUT_FILE = "output.ts";

const generator = new TypeScriptGenerator({ modelType: "interface" });
const contractJsonString = readFileSync("contract.json", { encoding: "utf-8" });
const contract = JSON.parse(contractJsonString);

export async function generate(): Promise<void> {
  const models = await generator.generate(contract);
  unlinkSync(OUTPUT_FILE);
  var stream = createWriteStream(OUTPUT_FILE, { flags: "a" });
  for (const model of models) {
    stream.write(model.result + "\n");
  }
  stream.end();
}

if (require.main === module) {
  generate();
}
```

##### contract.json
```
{
  "asyncapi": "2.6.0",
  "info": {
    "title": "Test",
    "version": "0.0.1"
  },
  "channels": {
    "test/test": {
      "publish": {
        "message": {
          "$ref": "#/components/messages/test"
        }
      }
    }
  },
  "components": {
    "messages": {
      "test": {
        "payload": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "aa_00_testAttribute": {
              "type": "string"
            },
            "aa_01_testAttribute": {
              "type": "string"
            },
            "aa_02_testAttribute": {
              "type": "string"
            }
          }
        }
      }
    }
  }
}
```

##### output.ts
```
interface AnonymousSchema_1 {
  aa_00TestAttribute?: string;
  aa_01TestAttribute?: string;
  aa_02TestAttribute?: string;
}
```

#### Expected behavior
Attributes in `AnonymousSchema_1` should be as such:
```
interface AnonymousSchema_1 {
  aa_00_testAttribute?: string;
  aa_01_testAttribute?: string;
  aa_02_testAttribute?: string;
}
```

**Comment by jonaslagoni** [comment]
hey @dansiemens1, yea this does indeed seem like a bug 🤔 

Property name's are constrained here: https://github.com/asyncapi/modelina/blob/d7f38e42f3fcef480b2c462b0d88de188c2c66a8/src/generators/typescript/constrainer/PropertyKeyConstrainer.ts#L37C21-L37C46

Would appreciate any help fixing it 🙏

**Comment by danielslalom** [comment]
@jonaslagoni Do you see this as just a problem with underscore or wider than that? If it's just an underscore issue we could change `FormatHelpers.toCamelCase` to something like:

```
  static toCamelCase(renderName: string): string {
    return renderName
      .split('_')
      .map((word) => camelCase(word))
      .join('_');
  }
```

**Comment by jonaslagoni** [comment]
All for it @danielslalom  👍 

I dont know of any other problems.

**Comment by jonaslagoni** [comment]
When proposing the change, please target the `next` branch as this is a breaking change.

**Comment by jonaslagoni** [comment]
Hey @danielslalom let me know if you need any help 🙂
