### ISSUE TITLE
The object passed as the value prop to the Context provider changes every render. To fix this consider wrapping it in a useMemo hook.

### ISSUE THREAD

**Issue by AceTheCreator** [asyncapi/modelina#1526]
## Why this issue?
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=asyncapi_generator-model-sdk&open=AYbwH5-yxKyPQbw46W-V&tab=why

## Where's the issue? 
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=asyncapi_generator-model-sdk&open=AYbwH5-yxKyPQbw46W-V&tab=code

**Comment by AnishKacham** [comment]
Hi, I'd like to work on this.

**Comment by AnishKacham** [comment]
Hey, I don't think we can use Hooks here as it is a React Class component. So useMemo is a no go

**Comment by jonaslagoni** [comment]
Yea, too much of a haggle to change probably. Thanks @AnishKacham, closing 🙂 

Feel free to grab one of the other open issues 🙇
