### ISSUE TITLE
Unnecessary use of boolean literals in conditional expression.

### ISSUE THREAD

**Issue by AceTheCreator** [asyncapi/modelina#1528]
## Why this issue?
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=asyncapi_generator-model-sdk&open=AYmG-_9kC_s3gwvwlOr_&tab=why

## Where's the issue? 
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=asyncapi_generator-model-sdk&open=AYmG-_9kC_s3gwvwlOr_&tab=code

**Comment by sivasuriyankumarasamy** [comment]
Hi @AceTheCreator, 
I would like to work on this. can you assign this to me?
