### ISSUE TITLE
The object passed as the value prop to the Context provider changes every render. To fix this consider wrapping it in a useMemo hook.

### ISSUE THREAD

**Issue by AceTheCreator** [asyncapi/modelina#1529]
## Why this issue?
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=asyncapi_generator-model-sdk&open=AYbwH6BTxKyPQbw46W-m&tab=why

## Where's the issue? 
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=asyncapi_generator-model-sdk&open=AYbwH6BTxKyPQbw46W-m&tab=code

**Comment by harshit-senpai** [comment]
hey I would like to work on this, as it does not show assigned to anyone

**Comment by Samridhi-98** [comment]
> hey I would like to work on this, as it does not show assigned to anyone

Please go ahead and feel free to ask your doubt on slack :)

**Comment by harshit-senpai** [comment]
i have few doubts regarding the PR in which channel should i ask those
