### ISSUE TITLE
'../../helpers' import is duplicated.

### ISSUE THREAD

**Issue by AceTheCreator** [asyncapi/modelina#1534]
## Why this issue?
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=asyncapi_generator-model-sdk&open=AYXfK942-0g9lMaA1TxE&tab=why

## Where's the issue? 
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=asyncapi_generator-model-sdk&open=AYXfK942-0g9lMaA1TxE&tab=code

**Comment by harshit-senpai** [comment]
hey can I go ahead on this one? as it does not shows assigned to anyone
