### ISSUE TITLE
Remove this unused import of 'JAVA_COMMON_PRESET'.

### ISSUE THREAD

**Issue by AceTheCreator** [asyncapi/modelina#1536]
## Why this issue?
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=asyncapi_generator-model-sdk&open=AYjaFwr-XBcnZgI4LLXu&tab=why

## Where's the issue? 
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=asyncapi_generator-model-sdk&open=AYjaFwr-XBcnZgI4LLXu&tab=code

**Comment by sivasuriyankumarasamy** [comment]
Hi @AceTheCreator,
Can I work on this issue?

**Comment by Samridhi-98** [comment]
> Hi @AceTheCreator, Can I work on this issue?

Please go ahead. Feel free to ask any doubt here or on slack 🙂
Happy Coding 🎉
