### ISSUE TITLE
File path as input to the generator

### ISSUE THREAD

**Issue by nilkanth987** [asyncapi/modelina#1591]
#### Reason/Context
I am implementing AsyncAPI for the project that has huge set of REST APIs and Socket Events. To make things modularised and easy to read I have divided a single documentation into multiple files. Here is a reference to the file structure
```
/docs
  - asyncapi.yml
  - servers.yml
  /components
      - component1.yml
      - component2.yml
 /schemas
      - schema1.yml
      - schema2.yml 
```
These files are internally referenced so the modules are easy to read and edit.

Now when I try to create models using `@asyncapi/modelina` it accepts only parsed input. *_Even if I import a file and parse it to proved to the generated it will mess up the references in the file_*

#### Description
- What changes have to be introduced?
Let the `generateToFiles` method of the generator accept the file path as input. And process and parse the file before supplying it to the Renderer.
- Will this be a breaking change?
Yes
- How could it be implemented/designed?
I propose a new method `generateFromFile` which will accept file as input and can output models to multiple files.

**Comment by jonaslagoni** [comment]
> I propose a new method generateFromFile which will accept file as input and can output models to multiple files.

Makes sense to me 👍 

Want to contribute it @nilkanth987 ?

**Comment by nilkanth987** [comment]
@jonaslagoni , Yes I want to contribute.

**Comment by jonaslagoni** [comment]
Let me know if you need any help 😄

**Comment by jonaslagoni** [comment]
Hmm, yea might not be as easy to implement as first thought 😄 Cause we need to try and preserve the current architecture with processors and generators.

One generator preferably should not know about the input (how to handle it) but just give it to the processor.

Dilemma is, right now processors are interpreting the input entirely on their own, which makes it hard to know if its an url for an AsyncAPI document, or JSON Schema for example. 

I think the best cause of action is to add a input processor type called `inputType` with each input processor as value, that forces the input processor to process the input. 

Then the input in these cases are just an url, thats it. Now you should be able to pass `generator.generate(url, {processors:{inputType: 'asyncapi'}})`

That way all generators already understand this new input and all you have to change is 2 files.

Does that make sense @nilkanth987 ?

**Comment by nilkanth987** [comment]
@jonaslagoni , Yes. Thanks for the guidance. I will implement it and let you know if I face any issues.
