### ISSUE TITLE
Playground 502 http status `generate.handler is undefined or not exported`

### ISSUE THREAD

**Issue by Ferror** [asyncapi/modelina#1595]
#### Describe the bug
Seems like Modelina Playground fails to load https://modelina.org/playground

#### How to Reproduce
<img width="1512" alt="Screenshot 2023-11-05 at 14 30 19" src="https://github.com/asyncapi/modelina/assets/17534504/c31ef549-1b12-4e18-9ded-4c5310f192c0">
<img width="757" alt="Screenshot 2023-11-05 at 14 31 59" src="https://github.com/asyncapi/modelina/assets/17534504/67f88419-2276-43a6-a5c4-41171644e5dc">

**Comment by jonaslagoni** [comment]
I tried to fix it last week, but was unsuccessful, still trying to figure it out why it all of the sudden broke 🙃
