### ISSUE TITLE
CSharp generator does not generate DateTime properties

### ISSUE THREAD

**Issue by jano-petras** [asyncapi/modelina#1607]
#### Describe the bug
CSharp code generation is not respecting 'format' hints when generating C# code, specifically date-time format. On the other hand, java generation does.

#### How to Reproduce
`npm install @asyncapi/modelina`
`npm install @asyncapi/cli`

Versions installed were:
* @asyncapi/modelina@2.0.2
* @asyncapi/cli@0.60.1

Yaml file with AsyncAPI:

```
asyncapi: 2.5.0
info:
  title: Streetlights API
  version: 1.0.0
  description: |
    The Smartylighting Streetlights API allows you
    to remotely manage the city lights.
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'
channels:
  light/measured:
    publish:
      message:
        $ref: '#/components/messages/LightMeasuredMessage'
components:
  messages:
    LightMeasuredMessage:
      title: "LightMeasured"
      messageId: "LightMeasured"
      payload:
        $ref: '#/components/schemas/LightMeasured'    
  schemas:
    LightMeasured:
      additionalProperties: false
      type: object
      properties:
        id:
          type: integer
          minimum: 0
          description: Id of the streetlight.
        lumens:
          type: integer
          minimum: 0
          description: Light intensity measured in lumens.
        sentAt:
          type: string
          format: date-time
          description: Date and time when the message was sent.
```

Execute:
`npx asyncapi generate models csharp ./sample1.yml --namespace=Test`

Output:
```
## Model name: LightMeasured
namespace Test
{
  public class LightMeasured
  {
    private int? id;
    private int? lumens;
    private string? sentAt;

    public int? Id
    {
      get { return id; }
      set { id = value; }
    }

    public int? Lumens
    {
      get { return lumens; }
      set { lumens = value; }
    }

    public string? SentAt
    {
      get { return sentAt; }
      set { sentAt = value; }
    }
  }
}
```

Execute:
`npx asyncapi generate models java ./sample1.yml --packageName=Test`

Output:
```
public class LightMeasured {
  private Integer id;
  private Integer lumens;
  private java.time.OffsetDateTime sentAt;

  public Integer getId() { return this.id; }
  public void setId(Integer id) { this.id = id; }

  public Integer getLumens() { return this.lumens; }
  public void setLumens(Integer lumens) { this.lumens = lumens; }

  public java.time.OffsetDateTime getSentAt() { return this.sentAt; }
  public void setSentAt(java.time.OffsetDateTime sentAt) { this.sentAt = sentAt; }
}
```

#### Expected behavior
`sentAt` should be rendered with `DateTime` .net type, similar to how java renders `OffsetDateTime`

**Comment by jonaslagoni** [comment]
Hey @jano-petras, thanks for the issue!

Here is where the type is being determined for C#: https://github.com/asyncapi/modelina/blob/e53c2af1095e020667ee2a14d4f0aa09f5546796/src/generators/csharp/CSharpConstrainer.ts#L59

So we just have to do something similar as we do in Java: https://github.com/asyncapi/modelina/blob/e53c2af1095e020667ee2a14d4f0aa09f5546796/src/generators/java/JavaConstrainer.ts#L173

Would be awesome if you would help contribute this :v:

Make sure to base the changes on the `next` branch as this will be a breaking change 🙂

**Comment by jano-petras** [comment]
Sounds all right, will see what I can come up with
