### ISSUE TITLE
PythonGenerator with Pydantic  If a property is Optional not required the json expected a key None

### ISSUE THREAD

**Issue by tornabene** [asyncapi/modelina#1644]
#### Describe the bug
PythonGenerator with Pydantic

#### How to Reproduce
If a property is Optional not required the json expected a key None

it is possible change the Class Python pydantic generator and add a default value =None for not required properties
from:
optionalkey: Optional[str] = Field( )
to:
optionalkey: Optional[str] = Field( default= None )

**Comment by jonaslagoni** [comment]
Thanks for the issue @tornabene 👍 

This should be an easy fix, it's rendered as part of the preset located here: https://github.com/asyncapi/modelina/blob/091f3a815728538da6e498cd0e414ccc28661308/src/generators/python/presets/Pydantic.ts#L28

Happy to review a PR and answer questions to fix this 🙂
