### ISSUE TITLE
Rewrite Class-Based React Components to Functional Components in Modelina Website


### ISSUE THREAD

**Issue by devilkiller-ag** [asyncapi/modelina#1648]
The current codebase of the Playground Generator Options, Docs, and Examples Components of the Modelina Website contains class-based react components. We should update the code base to use functional components and hooks at all places. This will result in cleaner, easier-to-understand components compared to class components. This issue is to track my work on this.

**Comment by asv018** [comment]
Can you assign this issue to me? 
I can start contributing

**Comment by devilkiller-ag** [comment]
Hi @asv018, I Have already started working on this. If you are interested in contributing, I can recommend you some other issues.

**Comment by asv018** [comment]
> Hi @asv018, I Have already started working on this. If you are interested in contributing, I can recommend you some other issues.

Yeah sure

**Comment by asv018** [comment]
I can also work upon this issue.

**Comment by devilkiller-ag** [comment]
@asv018 You can checkout these issues: [issue 1](https://github.com/asyncapi/modelina/issues/1577), [issue 2](https://github.com/asyncapi/modelina/issues/1206), and [issue 3](https://github.com/asyncapi/modelina/issues/1644). There are many other good-first and stale issues which you can check in the issues section. All the best ✨

**Comment by asv018** [comment]
It will be good if you can assign this issue to me. I am also starting contributing to it.

**Comment by devilkiller-ag** [comment]
Hi @asv018, Sorry I can't assign as I have been working on this issue for a while and I am done with much of the work. This issue is continuous with another [issue](https://github.com/asyncapi/modelina/issues/1346#event-11205105890) for upgrading the layout of the Modelina playground.
