### ISSUE TITLE
[website bug]: update the link to async api Shop in the footer section of website

### ISSUE THREAD

**Issue by devilkiller-ag** [asyncapi/modelina#1666]
#### Describe the bug
Currently, AsyncAPI Shop links to the old [shop website](https://asyncapi.threadless.com/). We should update the link to the [new shop website](https://www.store.asyncapi.com/collections/all-products).
#### How to Reproduce
- Visit the footer section on the [Modelina Website](https://modelina.org/).

#### Expected behavior
The updated link should be: https://www.store.asyncapi.com/collections/all-products

cc @AceTheCreator

**Comment by mrkirthi-24** [comment]
Hey @devilkiller-ag can i work on this issue?

**Comment by devilkiller-ag** [comment]
@mrkirthi-24 Sure go for it!

**Comment by anchalpanwar17** [comment]
Hey, it's been a week and there is no update on this issue yet, are you still working on this @mrkirthi-24. If not, I would like to work on this.
@devilkiller-ag , can i work on this?

**Comment by mrkirthi-24** [comment]
> Hey, it's been a week and there is no update on this issue yet, are you still working on this @mrkirthi-24. If not, I would like to work on this. @devilkiller-ag , can i work on this?

Hey you can work on it

**Comment by devilkiller-ag** [comment]
@anchalpanwar17 you can work on this issue

**Comment by devilkiller-ag** [comment]
Fixed by #1705
