### ISSUE TITLE
Add Python constraint tests

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#1669]
#### Reason/Context
Right now the Python constraints are not getting tested explicitly when they should. 

TODO:
- Create a new test file for each constraint logic in: https://github.com/asyncapi/modelina/tree/master/src/generators/python/constrainer

You can read more about constraints here: https://modelina.org/docs/constraints

Use the following TypeScript constraints as a guideline: https://github.com/asyncapi/modelina/tree/master/test/generators/typescript/constrainer

**Comment by devilkiller-ag** [comment]
Hi @jonaslagoni, can I try this one?

**Comment by jonaslagoni** [comment]
No need to ask, just state that you are doing it 👌

**Comment by devilkiller-ag** [comment]
Thanks @jonaslagoni, I will keep that in mind 😁

**Comment by Min2who** [comment]
@jonaslagoni can you check the PR.Should i make a new PR as this PR have some unwanted commits

**Comment by jonaslagoni** [comment]
@Min2who are you referring to https://github.com/asyncapi/modelina/pull/1689? Also as @devilkiller-ag already commented he wanted to work on this issue. If you are not already done with it, maybe https://github.com/asyncapi/modelina/issues/1668 could be better to work on?

**Comment by Min2who** [comment]
@devilkiller-ag are you still working on it ? if so drop a comment i will close this pr

**Comment by devilkiller-ag** [comment]
Hi @Min2who, yes I am working on it. And I will open a PR soon as the work is complete. I will suggest you to inform me of the issue before you start working on it. By the way you can check out a similar issue for adding tests for PHP constraints: #1668
