### ISSUE TITLE
Add C++ constraint tests

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#1670]
#### Reason/Context
Right now the C++ constraints are not getting tested explicitly when they should. 

TODO:
- Create a new test file for each constraint logic in: https://github.com/asyncapi/modelina/tree/master/src/generators/cplusplus/constrainer

You can read more about constraints here: https://modelina.org/docs/constraints

Use the following TypeScript constraints as a guideline: https://github.com/asyncapi/modelina/tree/master/test/generators/typescript/constrainer

**Comment by Min2who** [comment]
@jonaslagoni it should mostly be similar with the typescript constrainer test right?

**Comment by jonaslagoni** [comment]
A bit less, but yea @Min2who 😄
