### ISSUE TITLE
Add missing C++ constraint docs

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#1671]
#### Reason/Context
In the other languages, we have explicit documentation explaining the constraint rules such as for TypeScript: https://modelina.org/docs/constraints/typescript

However, we are missing one for C++.

TODO:
- Go over the constraint logic for C++ for constants: https://github.com/asyncapi/modelina/blob/master/src/generators/cplusplus/constrainer/ConstantConstrainer.ts
- Go over the constraint logic for C++ for enum value and key constraints: https://github.com/asyncapi/modelina/blob/master/src/generators/cplusplus/constrainer/EnumConstrainer.ts
- Go over the constraint logic for C++ for model naming constraints: https://github.com/asyncapi/modelina/blob/master/src/generators/cplusplus/constrainer/ModelNameConstrainer.ts
- Go over the constraint logic for C++ for property key constraints: https://github.com/asyncapi/modelina/blob/master/src/generators/cplusplus/constrainer/PropertyKeyConstrainer.ts

You could potentially copy-paste the TypeScript one: https://github.com/asyncapi/modelina/blob/master/docs/constraints/TypeScript.md and adapt it to C++

**Comment by ankur0904** [comment]
I want to work on this issue :)
