### ISSUE TITLE
Add missing Kotlin constraint docs

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#1672]
#### Reason/Context
In the other languages, we have explicit documentation explaining the constraint rules such as for TypeScript: https://modelina.org/docs/constraints/typescript

However, we are missing one for Kotlin.

TODO:
- Go over the constraint logic for Kotlin for constants: https://github.com/asyncapi/modelina/blob/master/src/generators/kotlin/constrainer/ConstantConstrainer.ts
- Go over the constraint logic for Kotlinfor enum value and key constraints: https://github.com/asyncapi/modelina/blob/master/src/generators/kotlin/constrainer/EnumConstrainer.ts
- Go over the constraint logic for Kotlin for model naming constraints: https://github.com/asyncapi/modelina/blob/master/src/generators/kotlin/constrainer/ModelNameConstrainer.ts
- Go over the constraint logic for Kotlin for property key constraints: https://github.com/asyncapi/modelina/blob/master/src/generators/kotlin/constrainer/PropertyKeyConstrainer.ts

You could potentially copy-paste the TypeScript one: https://github.com/asyncapi/modelina/blob/master/docs/constraints/TypeScript.md and adapt it to Kotlin

**Comment by devilkiller-ag** [comment]
Hi @jonaslagoni, I am going to work on this issue.
