### ISSUE TITLE
Add missing Python constraint docs

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#1674]
#### Reason/Context
In the other languages, we have explicit documentation explaining the constraint rules such as for TypeScript: https://modelina.org/docs/constraints/typescript

However, we are missing one for Python.

TODO:
- Go over the constraint logic for Python for constants: https://github.com/asyncapi/modelina/blob/master/src/generators/python/constrainer/ConstantConstrainer.ts
- Go over the constraint logic for Python for enum value and key constraints: https://github.com/asyncapi/modelina/blob/master/src/generators/python/constrainer/EnumConstrainer.ts
- Go over the constraint logic for Python for model naming constraints: https://github.com/asyncapi/modelina/blob/master/src/generators/python/constrainer/ModelNameConstrainer.ts
- Go over the constraint logic for Python for property key constraints: https://github.com/asyncapi/modelina/blob/master/src/generators/python/constrainer/PropertyKeyConstrainer.ts

You could potentially copy-paste the TypeScript one: https://github.com/asyncapi/modelina/blob/master/docs/constraints/TypeScript.md and adapt it to Python

**Comment by devilkiller-ag** [comment]
Hi @jonaslagoni, Can I work on this issue? It will help me to understand more about Async API Docs.

**Comment by jonaslagoni** [comment]
Of course @devilkiller-ag 🤙
