### ISSUE TITLE
Add Scala generator to playground

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#1690]
#### Reason/Context
With the new Scala generator, we need to add it to the playground so people can play around with it. It should be fairly straightforward;

TODO;
- Add the generator API function: https://github.com/asyncapi/modelina/tree/master/modelina-website/src/pages/api/functions
- Integrate it into the main generate function; https://github.com/asyncapi/modelina/blob/master/modelina-website/src/pages/api/generate.ts
- Adapt the playground to call the new generator code (use the existing generator code as guideline): https://github.com/asyncapi/modelina/tree/master/modelina-website/src/components/playground

**Comment by Min2who** [comment]
@jonaslagoni can I try this one?

**Comment by jonaslagoni** [comment]
Go for it @Min2who 👍

**Comment by AkhilJ321** [comment]
@jonaslagoni .hey , I worked on this issue and I implemented mostly all the steps. But when I am changing property name format,modal naming format,enum naming format. It fails to do so and gives 500.

**Comment by Min2who** [comment]
@AkhilJ321 i was already working on it for 4days

**Comment by AkhilJ321** [comment]
I thought you haven't responded from 4 days so it will be free. So if you have completed it then its okay otherwise i am also mostly done.Just need a little help and it will be done

**Comment by Min2who** [comment]
i am putting up a pr

i was working with the frontend part of it

**Comment by AkhilJ321** [comment]
@Min2who are you still working on this issue?

**Comment by Min2who** [comment]
@AkhilJ321 if yu have working solution feel free to make a PR
PS: i was a bit occupied with college stuff and now have got some time

**Comment by Min2who** [comment]
@jonaslagoni can you assign this to @AkhilJ321 i am not working on it
