### ISSUE TITLE
Add missing Scala constraint docs

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#1692]
#### Reason/Context
In the other languages, we have explicit documentation explaining the constraint rules such as for TypeScript: https://modelina.org/docs/constraints/typescript

However, we are missing one for Scala.

TODO:
- Go over the constraint logic for Scala for constants: https://github.com/asyncapi/modelina/blob/master/src/generators/scala/constrainer/ConstantConstrainer.ts
- Go over the constraint logic for Scala for enum value and key constraints: https://github.com/asyncapi/modelina/blob/master/src/generators/scala/constrainer/EnumConstrainer.ts
- Go over the constraint logic for Scala for model naming constraints: https://github.com/asyncapi/modelina/blob/master/src/generators/scala/constrainer/ModelNameConstrainer.ts
- Go over the constraint logic for Scala for property key constraints: https://github.com/asyncapi/modelina/blob/master/src/generators/scala/constrainer/PropertyKeyConstrainer.ts

You could potentially copy-paste the TypeScript one: https://github.com/asyncapi/modelina/blob/master/docs/constraints/TypeScript.md and adapt it to Scala

**Comment by officialasishkumar** [comment]
I would like to work on this. Will open a PR soon!
