### ISSUE TITLE
[Docs Bug 🐞 report]: Missing emoji in the `Contributing` page

### ISSUE THREAD

**Issue by ankur0904** [asyncapi/modelina#1697]
### Describe the bug you found in AsyncAPI Docs.

The `:tada:` must be :tada:  

There are 3 `:tada:` and 1 `:smile:`

[URL](https://modelina.org/docs/contributing)

### Attach any resources that can help us understand the issue.

![WhatsApp Image 2023-12-26 at 23 07 32](https://github.com/asyncapi/modelina/assets/98346896/cdcbf544-eb39-41f8-835e-043b63d03d87)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ankur0904** [comment]
I also want to submit the PR if the issue is approved.

**Comment by jonaslagoni** [comment]
Go for it @ankur0904

**Comment by ankur0904** [comment]
@jonaslagoni Submitted the [PR](https://github.com/asyncapi/modelina/pull/1698)

**Comment by devansh-m12** [comment]
@ankur0904 you left one ':fire:' in middle
