### ISSUE TITLE
[Docs Bug 🐞 report]: Transformation stages picture missing

### ISSUE THREAD

**Issue by devansh-m12** [asyncapi/modelina#1700]
### Describe the bug you found in AsyncAPI Docs.

I noticed that the transformation stages image is missing in the input-processing section of the documentation. This image is crucial for understanding the input processing flow, and its absence is causing confusion for users.

### Attach any resources that can help us understand the issue.

https://modelina.org/docs/input-processing link to docs

![isssue](https://github.com/asyncapi/modelina/assets/86195162/8e0dcc49-1786-4f21-933f-eb5d077c66d9)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by akkshitgupta** [comment]
> I can't reproduce the error in local build

@officialasishkumar perhaps image path is not configured in the production which is correct for the local setup

**Comment by jonaslagoni** [comment]
Yea, it is definitely a production problem... Probably has to do with the Netlify config https://github.com/asyncapi/modelina/blob/master/modelina-website/netlify.toml 🤔 But I am not sure!

You can try setup the site on a personal netlify account, and if you get it fixed apply the settings you used and let me know if any settings in netlify itself is needed.
