### ISSUE TITLE
Make Playground Mobile Responsive

### ISSUE THREAD

**Issue by devilkiller-ag** [asyncapi/modelina#1715]
#### Reason/Context
This will allow people visiting from small screens, especially tablets, to use Playground.

#### Description
We want to make Playground design Mobile Responsive and then implement it.

I will be working on this issue.

**Comment by devilkiller-ag** [comment]
@jonaslagoni Can I start working on this feature?

**Comment by jonaslagoni** [comment]
Makes sense to me to have this 👌

**Comment by devilkiller-ag** [comment]
@jonaslagoni Do you have any prior design suggestions in mind? To get started, I have thought about this design:
![Screenshot 2024-01-02 102333](https://github.com/asyncapi/modelina/assets/43639341/d660f821-ed6a-434b-b210-7a14b0d61bd2)
But this is just an option, I think we should discuss and decide on the design first before jumping into implementation.

**Comment by jonaslagoni** [comment]
I think having a single display that alternate between output, option and input (not shown at the same time), is the best option 👍

But yea, dont have any preference from my side, so all you ✌️

**Comment by devilkiller-ag** [comment]
Sounds good to me. I have the same design in mind too. I will start working on it soon.🚀

**Comment by devilkiller-ag** [comment]
This issue is still not resolved and up for grabs.

**Comment by jerensl** [comment]
Hi @devilkiller-ag , I'm new here can you assign this task to me? Quick question can I use this design as a reference or do you have a new design in mind? https://github.com/asyncapi/modelina/issues/1715#issuecomment-1873620477

**Comment by devilkiller-ag** [comment]
Hi @jerensl, yes you can work on this. Yes you can go ahead with the same design I made and explained earlier.

**Comment by devilkiller-ag** [comment]
Resolved in #2028
