### ISSUE TITLE
Create a CLI

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#172]
#### Reason/Context
Because this library should not be directly associated with the generator but a separate library we should introduce a CLI for the library.

#### Description
Be aware that this CLI might be part of a larger [CLI](https://github.com/asyncapi/cli/) and should be implemented with extensibility in mind.

#### Related issues
https://github.com/asyncapi/generator-model-sdk/issues/132

**Comment by magicmatatjahu** [comment]
It should be done in the [cli](https://github.com/asyncapi/cli) project :)

**Comment by derberg** [comment]
better create a new one as first we need a discussion on commands structure. 'asyncapi generate' should support generator and modelina as one feature, and depending on different flags you just get what you need

**Comment by voxpelli** [comment]
I kind of would like having a small CLI for just this module as well, but maybe it shouldn't live in this repo.

This module has potentials for use outside of the AsyncAPI ecosystem and would benefit everyone if it isn't too tightly coupled to the AsyncAPI ecosystem (I eg. created #360 now as the API:s I currently am consuming are Swagger API:s, though will eventually hopefully move to AsyncAPI API:s)

**Comment by jonaslagoni** [comment]
Gonna close this one down as it has now been integrated into the AsyncAPI CLI. If that is not enough and we need a small custom CLI for this library alone, then please create another issue 🙂
