### ISSUE TITLE
Add JSON Type definition support 

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#1740]
#### Reason/Context
It would be great to have support for JSON Type definition standard as supported inputs: https://jsontypedef.com/

To support it we need to add a new input processor, which you can read about how to add here: https://github.com/asyncapi/modelina/blob/master/docs/contributing.md#adding-a-new-input-processor

The TLDR; is that we want to convert their structure into our [Meta Models](https://modelina.org/docs/internal-model). Unless there are tooling available to handle references, the initial implementation might not support this. Feel free to document the limitations of the implementation as needed in an input document: https://github.com/asyncapi/modelina/tree/master/docs/inputs

Happy to help further if you get stuck on something :v:

**Comment by sagarkori143** [comment]
@jonaslagoni I would love to work on this.

**Comment by sagarkori143** [comment]
Hi @jonaslagoni I was going through the modelina .readme and I think in this code:

![image](https://github.com/asyncapi/modelina/assets/129517558/ad81c541-5212-4895-bea7-2ed9ecd5edbb)


```for (const model in models)``` should be this ```for (const generatedModel in models)```

else  the whole code should be this:
```const models = await generator.generate(input);
for (const model in models) { 
  const generatedCode = model.result;
  const dependencies = model.dependencies;
  const modeltype = model.type;
  const modelName = model.modelName;
  ...
}```

**Comment by jonaslagoni** [comment]
You are right @sagarkori143 👍

**Comment by moritzkalwa** [comment]
@jonaslagoni Is this still relevant? The website for jsontypedef is currently offline 😅

**Comment by jonaslagoni** [comment]
https://github.com/jsontypedef still gets updates, so I am sure it is just a fluke 😄 

So yea I would say it is 👍
