### ISSUE TITLE
Add Avro support

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#1741]
#### Reason/Context
It would be great to have support for the Avro standard as supported inputs: https://avro.apache.org/

To support it we need to add a new input processor, which you can read about how to add here: https://github.com/asyncapi/modelina/blob/master/docs/contributing.md#adding-a-new-input-processor

The TLDR; is that we want to convert [their structure](https://avro.apache.org/docs/1.11.1/specification/) into our [Meta Models](https://modelina.org/docs/internal-model). Feel free to document the limitations of the implementation as needed in an input document: https://github.com/asyncapi/modelina/tree/master/docs/inputs

You can use the following Avro input document for testing (or come up with your own):
```json
{
    "name": "Person",
    "namespace": "com.company",
    "type": "record",
    "fields": [
      {"name": "name", "type": "string", "example": "Donkey", "minLength": 0},
      {"name": "serialNo", "type": "string", "minLength": 0, "maxLength": 50},
      {"name": "email", "type": ["null","string"], "example": "donkey@asyncapi.com", "pattern": "^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$"},
      {"name": "age", "type": ["null", "int"], "default": null, "example": 123, "exclusiveMinimum": 0, "exclusiveMaximum": 200},
      {
        "name": "favoriteProgrammingLanguage",
        "type": {"name": "ProgrammingLanguage", "type": "enum", "symbols": ["JS", "Java", "Go", "Rust", "C"], "default": "JS"}
      },
      {"name": "certifications", "type": {"type": "array", "items": "string", "minItems": 1, "maxItems": 500, "uniqueItems": true}},
      {
        "name": "address",
        "type": {
          "name": "Address",
          "type": "record",
          "fields": [
            {"name": "zipcode", "type": "int", "example": 53003},
            {"name": "country", "type": ["null", "string"]}
          ]
        }
      },
      {"name": "weight", "type": "float", "example": 65.1, "minimum": 0, "maximum": 500},
      {"name": "height", "type": "double", "example": 1.85, "minimum": 0, "maximum": 3.0},
      {"name": "someid", "type": "string", "logicalType": "uuid"}
    ]
}
```

Happy to help further if you get stuck on something :v:

**Comment by akkshitgupta** [comment]
Hey @jonaslagoni since the avro schema is similar to JSON schema I wanna confirm if it would be great to make a model of avro schema just like [Draft 4 Schema](https://github.com/asyncapi/modelina/blob/master/src/models/Draft4Schema.ts) and implement it in the json schema input processor with an avro schema section

**Comment by jonaslagoni** [comment]
@akkshitgupta I would not add the Avro input processing as part of the JSON Schema input processor, you need to follow this guide: https://github.com/asyncapi/modelina/tree/master/docs/inputs
