### ISSUE TITLE
Add runtime tests for Python

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#1745]
#### Reason/Context

To properly test that the models that are generated are semantically correct, we need to test them in their specific runtime. This means that we need to add the setup for Python.

We already have a bunch of existing runtime tests for the other languages, that you can use as reference implementation: https://github.com/asyncapi/modelina/tree/master/test/runtime

Here is the TODO to solve this issue:
- Create a simple Python project under `runtime-python` that has a simple testing setup 
- Add a simple generation script called `runtime-python.ts` that generates the models: https://github.com/asyncapi/modelina/blob/master/test/runtime/runtime-kotlin.ts
- Add a simple TS test file that is used in the ecosystem to test the runtime: https://github.com/asyncapi/modelina/blob/master/test/runtime/runtime-kotlin.spec.ts
- Add [two scripts to the package.json](https://github.com/asyncapi/modelina/blob/c4b83f2d084add0c002325bc7a955a2cdc0e8c40/package.json#L110) file called `test:runtime:python` and `generate:runtime:python`
- Add a GitHub workflow file that spins up the test: https://github.com/asyncapi/modelina/blob/master/.github/workflows/runtime-kotlin-testing.yml
- Manually add a dart test that makes sure that the generated python model can be used as expected.

That should be it to add runtime testing.

If you encounter any problems just reach out :v:

**Comment by AkhilJ321** [comment]
@jonaslagoni , I would like to work on this issue, can you tell more about setting testing setup in runtime-python like which packages to use etc.

**Comment by jonaslagoni** [comment]
@AkhilJ321 what ever you usually use or want to use, I got no preference 😄

**Comment by Itssshikhar** [comment]
@jonaslagoni would like to ask, how can I go with Pytest as submodules for the Python-runtime tests, if that is ok with you?

**Comment by Itssshikhar** [comment]
@AkhilJ321 I think you are going in the right direction. I was doing it the same way.

**Comment by AkhilJ321** [comment]
Can you guide me about 4th and 5th steps?

**Comment by AkhilJ321** [comment]
@jonaslagoni can you explain about the last part i am not getting how to perform it.(About adding manual dart test)
