### ISSUE TITLE
Add OpenAPI 3.1 support

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#1749]
#### Reason/Context
Right now we already have support for [OpenAPI 3.0](https://github.com/asyncapi/modelina/blob/master/src/processors/OpenAPIInputProcessor.ts) and [Swagger 2.0](https://github.com/asyncapi/modelina/blob/master/src/processors/SwaggerInputProcessor.ts). But we should also support the newest 3.1 version: https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md

To support it we need to alter the existing OpenAPI input processor to also support the new 3.1 version: https://github.com/asyncapi/modelina/blob/master/src/processors/OpenAPIInputProcessor.ts

This does 

You can use the following OpenAPI 3.1 input document for testing (or come up with your own):
```json
{
  "openapi": "3.1.0",
  "info": {
    "version": "1.0.0",
    "title": "Swagger Petstore",
    "license": {
      "name": "MIT"
    }
  },
  "servers": [
    {
      "url": "http://petstore.swagger.io/v1"
    }
  ],
  "paths": {
    "/pets": {
      "get": {
        "summary": "List all pets",
        "operationId": "listPets",
        "tags": [
          "pets"
        ],
        "parameters": [
          {
            "name": "limit",
            "in": "query",
            "description": "How many items to return at one time (max 100)",
            "required": false,
            "schema": {
              "type": "integer",
              "maximum": 100,
              "format": "int32"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "A paged array of pets",
            "headers": {
              "x-next": {
                "description": "A link to the next page of responses",
                "schema": {
                  "type": "string"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Pets"
                }
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "Create a pet",
        "operationId": "createPets",
        "tags": [
          "pets"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Pet"
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "Null response"
          },
          "default": {
            "description": "unexpected error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      }
    },
    "/pets/{petId}": {
      "get": {
        "summary": "Info for a specific pet",
        "operationId": "showPetById",
        "tags": [
          "pets"
        ],
        "parameters": [
          {
            "name": "petId",
            "in": "path",
            "required": true,
            "description": "The id of the pet to retrieve",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Expected response to a valid request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Pet"
                }
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Pet": {
        "type": "object",
        "required": [
          "id",
          "name"
        ],
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64"
          },
          "name": {
            "type": "string"
          },
          "tag": {
            "type": "string"
          }
        }
      },
      "Pets": {
        "type": "array",
        "maxItems": 100,
        "items": {
          "$ref": "#/components/schemas/Pet"
        }
      },
      "Error": {
        "type": "object",
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "integer",
            "format": "int32"
          },
          "message": {
            "type": "string"
          }
        }
      }
    }
  }
}
```

Happy to help further if you get stuck on something :v:

**Comment by Min2who** [comment]
Hey @jonaslagoni after making changes i can test this in the playground right?

**Comment by jonaslagoni** [comment]
Cant remember if playground allows multiple inputs yet.

You can write unit tests for it 😄

**Comment by Tanay-Verma** [comment]
Hello,

I'm eager to contribute to this issue and excited to make my first open-source contribution. As a newcomer, I would greatly appreciate some guidance on the task.

Upon inspecting the [OpenAPIInputProcessor.ts file](https://github.com/asyncapi/modelina/blob/master/src/processors/OpenAPIInputProcessor.ts), it appears that the current parser used by the project lacks support for parsing and validating OpenAPI 3.1 specifications. After some research, I came across a repository based on [apidevtools/swagger-parser](https://github.com/APIDevTools/swagger-parser).

[readme/openapi-parser](https://github.com/readmeio/openapi-parser)

I believe integrating this alternative parser could address the gap in OpenAPI 3.1 support. I'm ready to explore and contribute to implementing this improvement. Any guidance or pointers you can provide would be immensely helpful.

**Comment by jonaslagoni** [comment]
Sounds like a good idea @Tanay-Verma 👍

**Comment by Athul0491** [comment]
We currently aren't using the latest version of the swagger-parser. The latest version of it has support for the OpenAPI 3.1 version as well.

**Comment by jonaslagoni** [comment]
Sounds even better @Athul0491, @Tanay-Verma 👍

**Comment by Tanay-Verma** [comment]
> We currently aren't using the latest version of the swagger-parser. The latest version of it has support for the OpenAPI 3.1 version as well.

Is this the one you are referring [swagger-parser](https://github.com/swagger-api/swagger-parser?tab=readme-ov-file)?
This is for java 😅.

**Comment by Athul0491** [comment]
I was referring to [swagger-parser](https://github.com/APIDevTools/swagger-parser ). [See this](https://github.com/APIDevTools/swagger-parser/pull/187), they have added support for OpenAPI 3.1 in version `10.1.0`

**Comment by jonaslagoni** [comment]
Either that or update the existing one for v3 with v3.1 changes as they should be non breaking
