### ISSUE TITLE
Add typescript `mapType` option to the playground

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#1756]
#### Reason/Context
There is an option for the TypeScript generator that is currently unsupported in the playground called `mapType`.

We need to create add it as an option for the playground.

@devilkiller-ag any chance you want to have a look at this or adapt the issue to good-first-issue so others can pick it up?

**Comment by devilkiller-ag** [comment]
@jonaslagoni I can work on this. I will create a PR soon.
