### ISSUE TITLE
Generate C# models with `partial` modifier

### ISSUE THREAD

**Issue by RowlandBanks** [asyncapi/modelina#1776]
#### Reason/Context
Please try answering few of those questions
- Why we need this improvement?

C# supports a `partial` modifier on all types (interfaces, classes, records and structs). This permits a type to be defined in multiple files in a single project.

This is particularly useful for generated code, as it allows programmers to easily add additional behaviours to generated code - for example:

```c#
// Generated by modelina
public partial class Person
{
    public string FirstName { get; set; }

    public string LastName { get; set; }
}
```

```c#
// Written by a developer - file must be created in the same project, with the same namespace, as the generated file.
public partial class Person
{
    public string FullName => FirstName + " " + LastName;
}
```

- How will this change help?
It will provide a well-understood extension point for generated code for C# developers to permit developers to add additional behaviours/implement interfaces on the generated models/etc.

- What is the motivation? 
It will provide a well-understood extension point for generated code for C# developers. This is a common pattern  when generating C# code.

#### Description
Please try answering few of those questions
- What changes have to be introduced?

- Will this be a breaking change?

No - adding the `partial` modifier is a compile-time concern, so should merely permit new behaviours, and have no impact on the built assembly.

However, if there was a concern, a new option could be introduced (`generatePartial`) for the C# generator, that would control this behaviour.

- How could it be implemented/designed?

This should be a very simple change - simply changing the [ClassRenderer](https://github.com/asyncapi/modelina/blob/3fa51d5c9b7f64d23ab4220977f8df9c527c916d/src/generators/csharp/renderers/ClassRenderer.ts#L33) and [RecordRenderer](https://github.com/asyncapi/modelina/blob/f632df79765f1c48c7558ae93eb64ffc47c31f85/src/generators/csharp/renderers/RecordRenderer.ts#L30) to return `public partial class ${this.model.name}` or `public partial record ${this.model.name}` respectively.

**Comment by jonaslagoni** [comment]
Makes sense to me @RowlandBanks 👍 want to contribute it?

**Comment by RowlandBanks** [comment]
Yep - will do. Just wanted to make sure there was agreement before I did 🙂.
