### ISSUE TITLE
Add "generated-code" XmlDoc and `[GeneratedCode]` attribute to C# models.

### ISSUE THREAD

**Issue by RowlandBanks** [asyncapi/modelina#1784]
It's very common in the C# generator world to add the [GeneratedCodeAttribute](https://learn.microsoft.com/en-us/dotnet/api/system.codedom.compiler.generatedcodeattribute?view=net-8.0) to generated code.

For example:

```c#
[GeneratedCode("some-code-generator", "1.2.3")]
public class SomeGeneratedModel
{
}
```

I would also suggest adding a documentation header to the generated code:

```c#
//----------------------
// <auto-generated>
//     Generated by the Modelina C# compiler. Do not edit - changes may be overwritten.
//     source: some-service.yaml
// </auto-generated>
//----------------------
public class SomeGeneratedModel
{
}
```

#### Reason/Context
Please try answering few of those questions
- Why we need this improvement?
These two methods of marking generated code are frequently used as part of a heuristic test to determine if code is generated. This may be done to, for example, exclude it from code coverage or static analysis checks, 

- How will this change help?
This change will clearly mark generated code as generated, in line with standard dotnet practices and customs.

- What is the motivation? 
Excluding generated code from static analysis tooling is the driving motivation.

#### Description
Please try answering few of those questions
- What changes have to be introduced?

- Will this be a breaking change?
No - the xmldoc comments are just comments, and thus compiled out. 

The `GeneratedCode` attribute is extremely unlikely to cause downstream issues - it would require a developer to be enabling a behaviour in the _absence_ of a `[GeneratedCode]` attribute _and_ to want that behaviour to apply to this generated code.

- How could it be implemented/designed?

This issue was initially discussed in [Slack](https://asyncapi.slack.com/archives/CQVJXFNQL/p1707255737568189).

@jonaslagoni suggested

>I would add this as a new preset, or maybe even add this functionality as part of the same preset for this:  https://github.com/asyncapi/modelina/issues/1330#issue-1725958978
> Call it description preset i.e. similar to https://github.com/asyncapi/modelina/blob/master/src%2Fgenerators%2Ftypescript%2Fpresets%2FDescriptionPreset.ts

Note that this issue is similar to #1330.

**Comment by xaviergxf** [comment]
This makes a lot of sense
Can this be reopened?
