### ISSUE TITLE
Support verbatimModuleSyntax in TypeScript Generator

### ISSUE THREAD

**Issue by moritzkalwa** [asyncapi/modelina#1793]
#### Reason/Context
Currently the typescript generator does not explicitly export/import interfaces as types. This is an issue when the typescript option 'verbatimModuleSyntax' is enabled and can potentially cause some other pitfalls.

#### Description
Add a new flag (or make this the default behaviour when using interfaces, afaik that should not cause any issues) that changes the behaviour of 'src/generators/typescript/TypeScriptDependencyManager.ts' so it imports and exports interfaces as types.

Before:
```typescript
import { PublicUser } from './PublicUser'
interface NewStatePayload {
  members: PublicUser[]
}
export { NewStatePayload }
```
After:
```typescript
import type { PublicUser } from './PublicUser'
interface NewStatePayload {
  members: PublicUser[]
}
export type { NewStatePayload }
```

**Comment by jonaslagoni** [comment]
I think it makes sense to just render it by default for interfaces (is there any other cases?) if it has no side effects of course :v:

All we need is to adapt the dependency manager: https://github.com/asyncapi/modelina/blob/master/src/generators/typescript/TypeScriptDependencyManager.ts#L48

**Comment by jonaslagoni** [comment]
@moritzkalwa not sure if you saw, but I unfortunately had to revert your PR because of breaking changes to the dependency functions and the bug it introduced. I am planning on fixing it at some point, but right now I have to spend time on something else.

If you got the time to help I would really appreciate it 🤙

**Comment by moritzkalwa** [comment]
> @moritzkalwa not sure if you saw, but I unfortunately had to revert your PR because of breaking changes to the dependency functions and the bug it introduced. I am planning on fixing it at some point, but right now I have to spend time on something else.
> 
> If you got the time to help I would really appreciate it 🤙

I saw and I'm planning on taking another look at it in the future. Haven't had the time to do so yet though, and probably won't until next week. Would love to fix that issue and get this done though, if that is early enough!

**Comment by peitschie** [comment]
Can we please re-open this? The upgrade and subsequent revert means this issue still remains, which is limiting my ability to use this on a Vue-based front end.
