### ISSUE TITLE
Allow literal types other than 'string' to be used and properly interpreted as const values

### ISSUE THREAD

**Issue by moritzkalwa** [asyncapi/modelina#1823]
#### Reason/Context
Please try answering few of those questions
- Why we need this improvement?
The behaviour of the const field is inconsistent without a reason (that im aware of)
- How will this change help?
The const field will support all literal types.
- What is the motivation? 

#### Description
Please try answering few of those questions
- What changes have to be introduced?
The constant constrainers for all languages need to be adapted to also work with `ConstrainedFloatModel` `ConstrainedIntegerModel` and `ConstrainedBooleanModel`.
- Will this be a breaking change?
Yes, the generated models will have different types and const properties will no longer have a setter.
- How could it be implemented/designed?
I am not sure yet if we should verify that the const values are valid and fit their type. Would really love some input on this.

**Comment by jonaslagoni** [comment]
From the input perspective, you only have valid JS values that it can be: https://www.w3schools.com/js/js_datatypes.asp

From that, you might need to force those values to different language values, i.e. in Java you could have `Double(value)` or in C# `Convert.ToDouble(int)` (are you only referring to C# for this issue, or all languages?)

And this is gonna be in conjunction with how each generator do their type mapping https://github.com/asyncapi/modelina/blob/6c87ed2967faeb9d9a5190455d40e97d80d7c3e4/src/generators/csharp/CSharpConstrainer.ts#L41

**Comment by moritzkalwa** [comment]
> From that, you might need to force those values to different language values, i.e. in Java you could have `Double(value)` or in C# `Convert.ToDouble(int)` (are you only referring to C# for this issue, or all languages?)
> 
So you're suggesting ensuring the types at runtime?

I would very much prefer keeping consistency, at least for those generators that already implement the constantConstrainer.

**Comment by jonaslagoni** [comment]
> So you're suggesting ensuring the types at runtime?

Can you clarify?

> I would very much prefer keeping consistency, at least for those generators that already implement the constantConstrainer.

Agree 👍

**Comment by moritzkalwa** [comment]
> > So you're suggesting ensuring the types at runtime?
> 
> Can you clarify?
> 
I am honestly just a little confused myself 😅 Those methods are part of Java/C# so we would could use them in our generated models, the real conversion would then only happen at runtime though, right?

**Comment by jonaslagoni** [comment]
Yes, for example, the const value might be `1208.2` from the input and the place you render it, you might do `Convert.ToDouble(${constValue})` which renders as `Convert.ToDouble(1208.2)` in the model, which of course then becomes at runtime they are converted, yes 🙂
