### ISSUE TITLE
Create a one for all input document for runtime to test all functionality

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#1825]
#### Reason/Context
Right now the runtime is mostly tested with https://github.com/asyncapi/modelina/blob/master/test/runtime/generic-input.json and C# https://github.com/asyncapi/modelina/blob/master/test/runtime/generic-input-csharp.json

However, it does not cover all supported formats such as date-time, big numbers, low numbers, enum with all possible values, etc.

So we need to form the `one for all` document we can use in the runtime to better test it.

The input should still be JSON Schema as it should be able to cover all cases.

**Comment by AKACHI-4** [comment]
hey @jonaslagoni .. I found it interesting to work with the issue.. as far I can understand that there should be one single test document rather then two separate for runtime testing... could you guide me what the document will include and how it will make impact `one for all` document to better test runtime .

**Comment by jonaslagoni** [comment]
The idea is that we try to map out the most possible variations of input, so when we test it in the runtime, we should with high likelihood be able to say `we support this`.

The easiest way I think is starting to write down the combinations of unions, arrays, tuples, dictionary type, object, enums, constants, date-time formats, circular references, etc.

Here is a list of all supported format in JSON Schema: https://json-schema.org/understanding-json-schema/reference/string#built-in-formats and the rest of the custom AsyncAPI specific formats: https://www.asyncapi.com/docs/reference/specification/v3.0.0#dataTypeFormat
