### ISSUE TITLE
Wrong model is getting generatred for asyncapi version object in v2 schema for golang

### ISSUE THREAD

**Issue by Souvikns** [asyncapi/modelina#1827]
#### Describe the bug
Golang is generating the wrong model for `AsyncApi_2Dot_6Dot_0SchemaDot`, it is creating the `Asyncapi` as `uint` instead of a string, which is why `json.Unmarshal` is also throwing an error. This does not exist in `v3` only happens with v2 schemas. 

Looking further the schema for `v2.6.0` is 

```json
  "asyncapi": {
      "type": "string",
      "enum": [
          "2.6.0"
      ],
      "description": "The AsyncAPI specification version of this document."
  }
```

scheme for v3 
```json
"asyncapi": {
    "type": "string",
    "const": "3.0.0",
    "description": "The AsyncAPI specification version of this document."
},
```

So, it looks like the golang generator for Modelina is unable to generate `enums` correctly. 

#### How to Reproduce

To reproduce this behavior we need to use `without-$id.json` [schemes](https://github.com/asyncapi/spec-json-schemas/tree/master/schemas) and use modelina to generate the models using these specifications. 

- Link to GitHub repository with project that has issues - https://github.com/Souvikns/parser-go
- Definitions to use golang to generate models - https://github.com/Souvikns/parser-go/tree/main/generator/definitions

#### Expected behavior
`Asyncapi` object should be of type `string` instead of `uint`. 

```go


package models

// AsyncApi_2Dot_6Dot_0SchemaDot represents a AsyncApi_2Dot_6Dot_0SchemaDot model.
type AsyncApi_2Dot_6Dot_0SchemaDot struct {
  Asyncapi *Asyncapi // should be of type string
  Id string
  Info *Info
  Servers map[string]interface{}
  DefaultContentType string
  Channels map[string]ChannelItem
  Components *Components
  Tags []Tag
  ExternalDocs *ExternalDocs
  AdditionalProperties map[string]interface{}
}
```

**Comment by jonaslagoni** [comment]
You can now use the following options to avoid this:

```
{
  processorOptions: {
    jsonSchema: {
      interpretSingleEnumAsConst: true
    }
  }
}
```
