### ISSUE TITLE
[BUG] C# setter for property named `value` prevents assignment.

### ISSUE THREAD

**Issue by RowlandBanks** [asyncapi/modelina#1862]
### Describe the bug.

A C# setter has a "magic" variable called `value` which contains the value being assigned.

If a model has a property called `Value`, then the generated setter is broken, as it will attempt to assign the magic variable, rather than the backing class field.

```c#
public partial class Duration
{
    private readonly decimal value;

    public decimal Value
    {
        get { return value; }
        // This setter is broken - it is assigning the setter-level value, not the class-level value.
        set { value = value; }
    }
}

### Expected behavior

The setter could be generated as `this.value = value`;

```c#
public decimal Value
{
    get { return value; }
    set { this.value = value; }
}
```

### Screenshots

N/A

### How to Reproduce

1. I opened the [online playground](https://modelina.org/playground?language=csharp).
2. I changed one of the field names to `value`.
3. I noted the C# setter was generated incorrectly, as described above.

### 🥦 Browser

Google Chrome

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by jonaslagoni** [comment]
Makes sense 👍
