### ISSUE TITLE
Generate enum and use it for values.

### ISSUE THREAD

**Issue by czlowiek488** [asyncapi/modelina#188]
#### Context
I have a function `saveProject` which save a asyncApiMessage as a document to a database.
This document is message wrapped in Envelope with additional properties.
A message looks like this:
```ts
export interface MessageProjectCreated { //this is what is generated from generator-model-sdk everything else is my code
   eventName: "tms.event.project.created";
};
export const message: MessageProjectCreated = {
   eventName: "tms.event.project.created",
};
```
My document look like this:
```ts
export enum EventName {
  ProjectCreated = "tms.event.project.created",
  ...
};
export interface Envelope<T> {
   name: EventName;
   payload: T;
};

export const document: Envelope<MessageProjectCreated> = {
   name: message.eventName,
   payload: event,
};
```
#### Reason#1
My problem with this is that typescript treat generated "tms.event.project.created" as a string not as part of EventName.
To make this work I had to replace Envelope with this.
```ts
export interface Envelope<T> {
   name: EventName | string; // a hacky way to make use of generated types
   payload: T;
};
```

#### Reason#2
I have to declare EventName enum by my own which can lead to unconsistency between event names from specification and enum written by me.

#### Description
I need a way to create enum in asyncapi and a way to specify field type as enum element.
So something like this: (I modified json below from [this answer](https://stackoverflow.com/a/63620260/9731304) in SO)
```json
{
  "$id":"MessageProjectCreated",
  "properties": {
    "eventName": {
      "$ref": "http://example.com/some_schema.json#/definitions/EventName/tms.event.project.created"
    }
  }
}
```
```json
{
  "$id": "http://example.com/some_schema.json",
  "definitions": {
    "EventName": {
      "enum": [ "tms.event.project.created"]
    }
  }
}
```
should generate something like this.
```ts
export enum EventName {
  ProjectCreated = "tms.event.project.created",
};
export interface MessageProjectCreated {
   eventName: EventName.ProjectCreated;
};

```

**Comment by czlowiek488** [comment]
For now it is the most important feature for me. If you can please prioritize it.

**Comment by jonaslagoni** [comment]
Thanks for the feature request @czlowiek488

This is a problem with the simplifier which does not split enum models into separate models as the generator expects. I will add this feature as soon as the new simplifier is merged.
