### ISSUE TITLE
[BUG] AsyncAPI generator for Java doesn't generate class correctly when there's reference to itself

### ISSUE THREAD

**Issue by xespirit** [asyncapi/modelina#1885]
### Describe the bug.

Modelina Async generator fails to generate Java class correctly in certain scenario: there's self-refence. Example:

```
{
  "asyncapi": "2.6.0",
  "info": {
    "title": "Case",
    "version": "1.0.0",
    "description": "AsyncAPI schema definition for Case"
  },
  "channels": {},
  "components": {
    "schemas": {
      "CaseSchema": {
        "$id": "CaseSchema",
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "label": {
            "type": "string"
          },
          "exceptForCase": {
            "type": "array",
            "items": {
              "type": "object",
              "$ref": "./Case.json#/components/schemas/CaseSchema"
            }
          }
        }
      }
    }
  }
}
```

### Expected behavior

Generated Java class should have 
`private List<CaseSchema> exceptForCase;`

instead it generates array of Map<String, Object>:

`private List<Map<String, Object>> exceptForCase;`

### Screenshots

Example:

<img width="590" alt="bug1" src="https://github.com/asyncapi/modelina/assets/15604818/c1bb16e5-fd55-4af3-b764-5537750bc218">

Generated class:

<img width="959" alt="bug2" src="https://github.com/asyncapi/modelina/assets/15604818/bd489116-7d84-4637-ba81-631957f3b59f">

### How to Reproduce

See screeshots above

### 🥦 Browser

None

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue ?

No, someone else can work on it

**Comment by jonaslagoni** [comment]
Hey @xespirit, which version are you using? 

I am pretty sure this is an old bug from Modelina v2

**Comment by jonaslagoni** [comment]
In v3 I get the following (https://modelina.org/playground?language=java):
```
{
  "asyncapi":"2.5.0",
  "info":{
     "title":"Streetlights API",
     "version":"1.0.0",
     "description":"The Smartylighting Streetlights API allows you\nto remotely manage the city lights.\n",
     "license":{
        "name":"Apache 2.0",
        "url":"https://www.apache.org/licenses/LICENSE-2.0"
     }
  },
  "servers":{
     "mosquitto":{
        "url":"mqtt://test.mosquitto.org",
        "protocol":"mqtt"
     }
  },
  "channels":{
     "lightmeasured":{
        "publish":{
           "summary":"Inform about environmental lighting conditions for a particular streetlight.",
           "operationId":"onLightMeasured",
           "message":{
              "name":"LightMeasured",
              "payload":{
                 "$id": "CaseSchema",
                 "type":"object",
                 "properties":{
                    "name":{
                       "type":"string"
                    },
                    "label":{
                       "type":"string"
                    },
                    "exceptForCase":{
                       "type":"array",
                       "items":{
                          "$ref":"#/channels/lightmeasured/publish/message/payload"
                       }
                    }
                 }
              }
           }
        }
     }
  }
}
``` 

```
package asyncapi.models;

import java.util.Map;
public class CaseSchema {
  private String name;
  private String label;
  private CaseSchema[] exceptForCase;
  private Map<String, Object> additionalProperties;

  public String getName() { return this.name; }
  public void setName(String name) { this.name = name; }

  public String getLabel() { return this.label; }
  public void setLabel(String label) { this.label = label; }

  public CaseSchema[] getExceptForCase() { return this.exceptForCase; }
  public void setExceptForCase(CaseSchema[] exceptForCase) { this.exceptForCase = exceptForCase; }

  public Map<String, Object> getAdditionalProperties() { return this.additionalProperties; }
  public void setAdditionalProperties(Map<String, Object> additionalProperties) { this.additionalProperties = additionalProperties; }
}
```

**Comment by xespirit** [comment]
> Hey @xespirit, which version are you using?
> 
> I am pretty sure this is an old bug from Modelina v2

I use 4.0.0-next.16 version of modelina:

```
"dependencies": {
    "@asyncapi/modelina": "^4.0.0-next.16",
    "ts-node": "^10.9.2",
    "typescript": "4.9.5"
  },
```

**Comment by jonaslagoni** [comment]
@xespirit even with next when I use the following AsyncAPI document it works fine (https://65f02a20166dac9eadcc846e--modelina.netlify.app/playground?language=java):

```
{
  "asyncapi":"2.5.0",
  "info":{
     "title":"Streetlights API",
     "version":"1.0.0",
     "description":"The Smartylighting Streetlights API allows you\nto remotely manage the city lights.\n",
     "license":{
        "name":"Apache 2.0",
        "url":"https://www.apache.org/licenses/LICENSE-2.0"
     }
  },
  "servers":{
     "mosquitto":{
        "url":"mqtt://test.mosquitto.org",
        "protocol":"mqtt"
     }
  },
  "channels":{
     "lightmeasured":{
        "publish":{
           "summary":"Inform about environmental lighting conditions for a particular streetlight.",
           "operationId":"onLightMeasured",
           "message":{
              "name":"LightMeasured",
              "payload":{
                 "$id": "CaseSchema",
                 "type":"object",
                 "properties":{
                    "name":{
                       "type":"string"
                    },
                    "label":{
                       "type":"string"
                    },
                    "exceptForCase":{
                       "type":"array",
                       "items":{
                          "$ref":"#/channels/lightmeasured/publish/message/payload"
                       }
                    }
                 }
              }
           }
        }
     }
  }
}
```

Might have something to do with your `$ref` pointing to the file itself 🤔 Is there a more complex setup in place that might cause this?

**Comment by xespirit** [comment]
> @xespirit even with next when I use the following AsyncAPI document it works fine (https://65f02a20166dac9eadcc846e--modelina.netlify.app/playground?language=java):
> 
> ```
> {
>   "asyncapi":"2.5.0",
>   "info":{
>      "title":"Streetlights API",
>      "version":"1.0.0",
>      "description":"The Smartylighting Streetlights API allows you\nto remotely manage the city lights.\n",
>      "license":{
>         "name":"Apache 2.0",
>         "url":"https://www.apache.org/licenses/LICENSE-2.0"
>      }
>   },
>   "servers":{
>      "mosquitto":{
>         "url":"mqtt://test.mosquitto.org",
>         "protocol":"mqtt"
>      }
>   },
>   "channels":{
>      "lightmeasured":{
>         "publish":{
>            "summary":"Inform about environmental lighting conditions for a particular streetlight.",
>            "operationId":"onLightMeasured",
>            "message":{
>               "name":"LightMeasured",
>               "payload":{
>                  "$id": "CaseSchema",
>                  "type":"object",
>                  "properties":{
>                     "name":{
>                        "type":"string"
>                     },
>                     "label":{
>                        "type":"string"
>                     },
>                     "exceptForCase":{
>                        "type":"array",
>                        "items":{
>                           "$ref":"#/channels/lightmeasured/publish/message/payload"
>                        }
>                     }
>                  }
>               }
>            }
>         }
>      }
>   }
> }
> ```
> 
> Might have something to do with your `$ref` pointing to the file itself 🤔 Is there a more complex setup in place that might cause this?

Yes, it has something to do with $ref pointing to itself. There's no any complex setup. I have tried Modelina generator with different json schemas, with different complexity. Everything works well except for case I mentioned above.

Is there any default behaviour of generator so It gneerates Map<String, Object> witjhout even including Java import for Map. My guess it happens when the generator gets confused so it somehow generates the map instead of correct object type.

**Comment by jonaslagoni** [comment]
Damn, yea thats a bug! https://github.com/asyncapi/modelina/blob/1239c9a03c1cccccd20ef9fd987219ee9d54107f/src/generators/java/JavaConstrainer.ts#L238

We need to add the dependency import like we do for Python here: https://github.com/asyncapi/modelina/blob/1239c9a03c1cccccd20ef9fd987219ee9d54107f/src/generators/python/PythonConstrainer.ts#L20

Do you mind helping to fix this?

**Comment by xespirit** [comment]
> Damn, yea thats a bug!
> 
> https://github.com/asyncapi/modelina/blob/1239c9a03c1cccccd20ef9fd987219ee9d54107f/src/generators/java/JavaConstrainer.ts#L238
> 
> We need to add the dependency import like we do for Python here:
> 
> https://github.com/asyncapi/modelina/blob/1239c9a03c1cccccd20ef9fd987219ee9d54107f/src/generators/python/PythonConstrainer.ts#L20
> 
> Do you mind helping to fix this?

I'm sorry but I'm Java/Kotlin Back-end developer, I don't think I have capacity right now to fix Typescript codebase

**Comment by jonaslagoni** [comment]
No worries, created a good first issue for it: https://github.com/asyncapi/modelina/issues/1892

> Yes, it has something to do with $ref pointing to itself. There's no any complex setup. I have tried Modelina generator with different json schemas, with different complexity. Everything works well except for case I mentioned above.

Regarding this problem, I simply cant reproduce your problem, unfortunately... Cause the example you gave generates the correct models.

Can you reproduce it yourself on the playground and post the example? https://65f02a20166dac9eadcc846e--modelina.netlify.app/playground?language=java

**Comment by AKACHI-4** [comment]
Hey @jonaslagoni I would love to work on it. 

However, Same stands for me as well; I am also unable to generate this problem in playground, I am still wondering why that

---

![image](https://github.com/asyncapi/modelina/assets/99159580/4e497e86-baac-4d3e-8de3-c33c7f05044a)

If the Change is this only, then why only this specific case isn't importing map. It's weird. 

```json
{
  "asyncapi": "2.6.0",
  "info": {
    "title": "Case",
    "version": "1.0.0",
    "description": "AsyncAPI schema definition for Case"
  },
  "channels": {},
  "components": {
    "schemas": {
      "CaseSchema": {
        "$id": "CaseSchema",
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "label": {
            "type": "string"
          },
          "exceptForCase": {
            "type": "array",
            "items": {
              "type": "object",
              "$ref": "#/components/schemas/CaseSchema"
            }
          }
        }
      }
    }
  }
}
```

**Comment by jonaslagoni** [comment]
> If the Change is this only, then why only this specific case isn't importing map. It's weird.

It's for every case, where there is a dictionary model 🙂

**Comment by xespirit** [comment]
> @xespirit even with next when I use the following AsyncAPI document it works fine (https://65f02a20166dac9eadcc846e--modelina.netlify.app/playground?language=java):
> 
> ```
> {
>   "asyncapi":"2.5.0",
>   "info":{
>      "title":"Streetlights API",
>      "version":"1.0.0",
>      "description":"The Smartylighting Streetlights API allows you\nto remotely manage the city lights.\n",
>      "license":{
>         "name":"Apache 2.0",
>         "url":"https://www.apache.org/licenses/LICENSE-2.0"
>      }
>   },
>   "servers":{
>      "mosquitto":{
>         "url":"mqtt://test.mosquitto.org",
>         "protocol":"mqtt"
>      }
>   },
>   "channels":{
>      "lightmeasured":{
>         "publish":{
>            "summary":"Inform about environmental lighting conditions for a particular streetlight.",
>            "operationId":"onLightMeasured",
>            "message":{
>               "name":"LightMeasured",
>               "payload":{
>                  "$id": "CaseSchema",
>                  "type":"object",
>                  "properties":{
>                     "name":{
>                        "type":"string"
>                     },
>                     "label":{
>                        "type":"string"
>                     },
>                     "exceptForCase":{
>                        "type":"array",
>                        "items":{
>                           "$ref":"#/channels/lightmeasured/publish/message/payload"
>                        }
>                     }
>                  }
>               }
>            }
>         }
>      }
>   }
> }
> ```
> 
> Might have something to do with your `$ref` pointing to the file itself 🤔 Is there a more complex setup in place that might cause this?

I'm providing full sets of files to reproduce the issue:

[Case.json](https://github.com/asyncapi/modelina/files/14635214/Case.json)
[DirectPolicy.json](https://github.com/asyncapi/modelina/files/14635215/DirectPolicy.json)
[Insurance.json](https://github.com/asyncapi/modelina/files/14635216/Insurance.json)
[Policy.json](https://github.com/asyncapi/modelina/files/14635217/Policy.json)
[Schemas.json](https://github.com/asyncapi/modelina/files/14635218/Schemas.json)

The generator is being called from Maven plug-in:

> generate
> ./node_modules/.bin/ts-node ./generate.ts com.test.asyncapi.model model/Schemas.json target/generated-sources/asyncapi/com/test/asyncapi/model

I've attached picture of generated files, representing the issue below:
[
![generated_files](https://github.com/asyncapi/modelina/assets/15604818/2aadd1eb-09b2-4b00-9834-a81e4eaa813f)
](url)
 
![case_schema_bug](https://github.com/asyncapi/modelina/assets/15604818/f3c29895-289f-40b9-9193-0a70e3844f8b)

@jonaslagoni could you try to reproduce the bug?

**Comment by jonaslagoni** [comment]
Just pinging that I have not forgotten about this, but have to work on some other fixes that I think will fix this along side it.
