### ISSUE TITLE
make arguments an object in CommonModel

### ISSUE THREAD

**Issue by czlowiek488** [asyncapi/modelina#191]
There is so many arguments here that I would consider passing them in a object. If you would do it this way, you dont have to care about order while developing. Also it may give you other benefits.

_Originally posted by @czlowiek488 in https://github.com/asyncapi/generator-model-sdk/pull/184#discussion_r632270789_

**Comment by jonaslagoni** [comment]
So I tried to refactor [mergeProperties](https://github.com/asyncapi/generator-model-sdk/blob/281036ec54bb333cec2d69f31fda7fcc36e04839/src/models/CommonModel.ts#L296):

```ts
private static mergeProperties({
    mergeTo, 
    mergeFrom, 
    originalSchema, 
    alreadyIteratedModels = new Map()
  }: {
    mergeTo: CommonModel, 
    mergeFrom: CommonModel, 
    originalSchema: Schema, 
    alreadyIteratedModels: Map<CommonModel, CommonModel>
  }) {
```

Of course, we can introduce a common parameter type between functions that share the same parameters, however, I am not sure I agree it improves the code 🤔

**Comment by czlowiek488** [comment]
I usually use one object as argument, for me it is just easier to work with if I do not have to care about order and also you are taking advantages of autosuggestion.
Sometimes I follow this pattern `(_Input_, _Settings_, _Settings2_, ...)` which make some sense if you are passing settings separetely to other independent functions.

**Comment by jonaslagoni** [comment]
I do not feel like the work that is needed to refactor this is worth it with the output it gives. Therefore I am gonna remove it from the milestone for now. 

> Sometimes I follow this pattern `(_Input_, _Settings_, _Settings2_, ...)` which make some sense if you are passing settings separetely to other independent functions.

I can see that would be useful at times 👍

**Comment by jonaslagoni** [comment]
I still don't see the value in refactoring it, gonna let it close on its own if no further actions are made.

**Comment by jonaslagoni** [comment]
Gonna close this as I dont think it will be changed. Feel free to reopen you or anyone else want to do it.
