### ISSUE TITLE
Merging two CommonModels can overwrite unwanted properties

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#193]
#### Describe issue
With the current implementation of the merging of CommonModels we hardcode that the CommonModel being merged into another overwrites the following properties:
- $id
- $ref
- extend
- originalSchema

#### How to solve
I am not entirely sure how to solve this unless we allow those properties to contain multiple values, but that does not make sense from the generator's perspective.

Could we maybe add an option for the user to decide the merge option they want? 🤔

**Comment by czlowiek488** [comment]
@jonaslagoni this is even more complex after I intruduced [this issue](https://github.com/asyncapi/generator-model-sdk/issues/194).

**Comment by jonaslagoni** [comment]
Still relevant, as #365 should solve this by providing both models, time will tell.

**Comment by jonaslagoni** [comment]
As I have yet to find an example that can be tested for where we don't see an expected behavior it's almost impossible to ponder in which scenarios it won't work...

Lets go by each use-case and see where it does not work.
