### ISSUE TITLE
generator should be able to generate generic types

### ISSUE THREAD

**Issue by czlowiek488** [asyncapi/modelina#194]
#### Context
I have specification written like below.
```yaml
components:
  schemas:
    Envelope:      
      $id: Envelope
      description: "Envelope shared between messages"
      type: object
      required: [event, eventId]
      properties:
        eventId:
          type: string
        event:
          $id: Event
          type: object
messages:
  project.Created:
    payload:
      $id: MessageProjectCreated
      allOf:
        - $ref: "#/components/schemas/Envelope"
        - type: object
          required: [event]
          properties:
            eventName:
              const: "tms.event.project.created"
            event:
              type: object
              $id: EventProjectCreated
              required: [project]
              properties:
                project:
                  type: object
```
this is generating interface like this
```ts
export interface MessageProjectCreated {
    eventId: string;
    event: EventProjectCreated;
    eventName: "tms.event.project.created";
}
```
#### Reason#1
I have few events on event bus which are not coming from specification, but they are using Envelope from specification. Specifcation tells what events are send by my client, but I sometimes send my own events to the same event bus.
For them I have to write my own Envelope and if Envelope will be changed in specification I will not be able to see differences.

#### Reason#2
In generic event handler I do not know which event is inside Envelope, it can be literally everything even an empty object in my test scenario.

#### Description
I would like to generate something like here for each $ref used in specs. 

```ts
export interface Envelope<T> {
    eventId: string;
    event: T;
}

export interface MessageProjectCreated extends Envelope<EventProjectCreated> {
   eventName: tms.event.project.created;
 };
```
and I would be able to do something like
```ts
export const genericEventHandler = (event: Envelope<any>) => {...};
```

**Comment by jonaslagoni** [comment]
Still relevant.

**Comment by AnimeshKumar923** [comment]
still relevant? @jonaslagoni
