### ISSUE TITLE
schemaMapping configuration to re-use existing model classes

### ISSUE THREAD

**Issue by rquinio1A** [asyncapi/modelina#1941]
### Why do we need this improvement?

With openapi-generator we're relying on the [schema-mapping feature](https://openapi-generator.tech/docs/customization/#schema-mapping).
Would it be possible to have a similar feature built-in modelina ?

### How will this change help?

schema-mapping allows to re-use some existing model objects instead of generating them.
This allows us to build helpers or utilities that can be shared across several APIs built around shared types.

### How could it be implemented/designed?

Maybe re-using the design from https://openapi-generator.tech/docs/customization/#schema-mapping

### 🚧 Breaking changes

No

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue?

No, someone else can work on it.

**Comment by jonaslagoni** [comment]
So basically, if the model is about to be generated, check it against `schemaMapping`, and if the names match use that mapping value instead? 

Would it need to handle dependencies, i.e. you would like to also import the type?

**Comment by rquinio1A** [comment]
> So basically, if the model is about to be generated, check it against `schemaMapping`, and if the names match use that mapping value instead?
> Would it need to handle dependencies, i.e. you would like to also import the type?

Exactly, if there's a schema mapping for a referenced type, do not generate it and reference the existing one instead.
In Java jaxrs-spec generator I know it uses the inline (fully qualified) type, without an import, but I guess it may be language/template-specific.

```xml
<schemaMappings>
    <schemaMapping>Error=com.acme.Error</schemaMapping>
</schemaMappings>
```

```java
private @Valid List<com.acme.Error> errors;
```

**Comment by jonaslagoni** [comment]
Alright, yea I think it makes sense to add something like this 👍
