### ISSUE TITLE
[FEATURE] export AbstractDependencyManager to allow overriding

### ISSUE THREAD

**Issue by kamaz** [asyncapi/modelina#2005]
### Why do we need this improvement?

Currently, while it is possible to configure a generator, there is no access to the `AbstractDependencyManager` types because they are not exported. This limits the ability to utilize existing abstract classes to create custom `AbstractDependencyManager` instances when developing generators. For reference, the [AbstractDependencyManager](https://github.com/asyncapi/modelina/blob/master/src/generators/AbstractDependencyManager.ts) types are not exported in the [index file](https://github.com/asyncapi/modelina/blob/master/src/generators/index.ts).

### How will this change help?

By exporting `AbstractDependencyManager`, developers will be able to create custom `DependencyManager` instances, enhancing the flexibility and extensibility of the generators.

### How could it be implemented/designed?

Add an export statement for `AbstractDependencyManager` in the `index.ts` file.

### 🚧 Breaking changes

No

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue?

Yes I am willing to submit a PR!

**Comment by jonaslagoni** [comment]
Go for it @kamaz :v:
