### ISSUE TITLE
Properties with type integer and format int64 generate properties of type int instead of type long using the C# generator

### ISSUE THREAD

**Issue by jespitae** [asyncapi/modelina#2053]
### Describe the bug.

The following piece of asyncapi specification:
![image](https://github.com/asyncapi/modelina/assets/23041146/3ec69c6e-7383-4d68-bc6b-087dfdcfaf0c)

Results in the following property:
![image](https://github.com/asyncapi/modelina/assets/23041146/6f5b05f2-d3c0-4045-900d-c65838d883aa)

### Expected behavior

We would expect that this asyncapi specification would have generated a property of type long. 
When using the Java generator it does result in Long properties.

### Screenshots

Screenshots provided earlier.

### How to Reproduce

We used version 2.0.2 of the asyncapi cli and version 3.5.3 of modelina and ran the following command:
`asyncapi generate models csharp ./asyncapi.json --namespace=Test --output=Models --csharpSystemJson`
Our async api specification is defined in version 2.4.0.

### 🥦 Browser

None

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by jonaslagoni** [comment]
We have something similar for Java: https://github.com/asyncapi/modelina/blob/0db19cc2e99ad0bdb09b961a91d5511d061077f0/src/generators/java/JavaConstrainer.ts#L155 we just need to adapt: https://github.com/asyncapi/modelina/blob/0db19cc2e99ad0bdb09b961a91d5511d061077f0/src/generators/csharp/CSharpConstrainer.ts#L55C12-L55C33 for C#

Happy to accept a PR @jespitae 🤙  Please target the `next` branch 🙂

**Comment by jespitae** [comment]
Hi,

I made a PR with the required change: https://github.com/asyncapi/modelina/pull/2054
Thanks for the quick response.
