### ISSUE TITLE
[BUG] Generated JsonConverter tries to Deserialize enums as dynamic in the C# generator

### ISSUE THREAD

**Issue by jespitae** [asyncapi/modelina#2063]
### Describe the bug.

The C# generator generates a JsonConverter using SystemTextJson, that tries to deserialize the enums as dynamic.
The enum looks like this: 
![image](https://github.com/asyncapi/modelina/assets/23041146/94915849-5c1d-403f-8bc5-6237e09cf4a0)
Next to the enum an extension method is generated:
![image](https://github.com/asyncapi/modelina/assets/23041146/8fb17f9d-44f4-4bff-b3f1-458861d3cb91)
The json converter tries to deserialize the enum as follows:
![image](https://github.com/asyncapi/modelina/assets/23041146/94d495a1-8f5a-4789-a6fb-962b95b0a87c)
This results in the following error when trying to deserialize the enum:
`The best overloaded method match for 'CBS.Viewer.Integration.Events.EnvironmentExtensions.ToEnvironment(string)' has some invalid arguments`

### Expected behavior

We would expect the resulting json converter to look like this:
![image](https://github.com/asyncapi/modelina/assets/23041146/a961bc9b-e9f9-41ee-8d60-743269553f3a)

### Screenshots

Screenshot provided throughout.

### How to Reproduce

Our asyncapi spec for the enum looks like this:
![image](https://github.com/asyncapi/modelina/assets/23041146/4167c44b-28cc-4203-970e-6acd870ae084)
The property on one of our events:
![image](https://github.com/asyncapi/modelina/assets/23041146/60be3de7-9a70-4937-be02-8f33f8f2b848)

We used version 2.0.2 of the asyncapi cli and version 3.5.3 of modelina and ran the following command:
`asyncapi generate models csharp ./asyncapi.json --namespace=Test --output=Models --csharpSystemJson`
Our async api specification is defined in version 2.4.0.

### 🥦 Browser

Mozilla Firefox

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by jonaslagoni** [comment]
@jespitae feel free to provide a PR :v: I don't think the `next` version has this solved 🤔 Just remember that enums can be any valid JSON value 🙂

**Comment by jespitae** [comment]
@jonaslagoni In that case maybe it's better to change the parameter type of the To... extension method to dynamic. I'll provide a PR.
