### ISSUE TITLE
[Docs Bug 🐞 report]: error in KotlinGenerator's example output with `generatorOptions.showTypeMappingExample == true`

### ISSUE THREAD

**Issue by Christian1984** [asyncapi/modelina#2107]
### Describe the bug you found in AsyncAPI Docs.

The output of KotlinGenerator's example with `generatorOptions.showTypeMappingExample == true` in KotlinGenerator.ts:18 reads 

```
dependencyManager.addDependency('import kotlinx.datetime.*');
```

This generates the import statement `import import kotlinx.datetime.*`, so the `import` keyword should be ommited in the example. It should read

```
dependencyManager.addDependency('kotlinx.datetime.*');
```

in the example output.

### Attach any resources that can help us understand the issue.

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jonaslagoni** [comment]
Love to get it fixed if it shows incorrectly :pray:

**Comment by Manancode** [comment]
Fixed it [here](https://github.com/asyncapi/modelina/pull/2115#issue-2615750375)
