### ISSUE TITLE
Support additionalItems in CommonModel

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#224]
#### Reason/Context
The CommonModel currently has no knowledge of `additionalItems` that the array/tuple must also support. This should change in the same way as `additionalProperties` are implemented.

**Comment by magicmatatjahu** [comment]
Be also aware, that the next version of JSON Schema (2019-09) has `prefixItems` and `items` (and as I remember also `additionalItems `) works slighty different than previous draft-07.

**Comment by jonaslagoni** [comment]
Lets not overcomplicate it as we have no use-case for `2019-09` as of yet. Once we do we can adapt for it 🙂

**Comment by jonaslagoni** [comment]
While trying to think about the code generation process. 

Say we have the following JSON Schema 
```js
{
  $id: 'Address',
  type: 'object',
  properties: {
    arrayProperty: {
      items: [
        {
          type: "string"
        }, {
          type: "number"
        }
      ],
      additionalItems: {
        type: "boolean"
      }
    }
  }
}
```

Do we want to generate the output (gonna use TS as example here) as:
```ts
class Address {
  arrayProperty: [String, number],
  arrayPropertyAdditionalItems?: Array<boolean>
}
```
or simply:
```ts
class Address {
  arrayProperty: Array<String | number | boolean>
}
```

Any other way around it? Adding support functions to add things to the array to comply with the restrictions of correct types for arrayProperty[0] and arrayProperty[1] but not the rest?

**Comment by magicmatatjahu** [comment]
```ts
class Address {
  arrayProperty: Array<String | number | boolean>
}
```

isn't correct. We should write it as:

```ts
class Address {
  arrayProperty: [String, number | ...boolean[]];
}
``` 

and we probably solve the problem :)

If additionalItems will be with `object` shape we can write

```ts
class Address {
  arrayProperty: [String, number | ...SomeObject[]];
}
```

**Comment by jonaslagoni** [comment]
Regardless of how languages should render it, we still need the `additionalItems` property for the CommonModel.

In TS we are able to render this to:
```ts
class Address {
  arrayProperty: [String, number, ...boolean?[]];
}
```
Where for other languages (especially for Java) we need to add helper methods such as something along the line of
```java
class Address {
    List<object> arrayProperty;
    public void addToArray(Object entry, int index) {
        if(index == 0) {
           ...
        }
        ...
    }
}
```
To ensure that the developer cannot add entries to an array, and this will basically enable tuple support for Java which at the moment does not have any help to support this.
