### ISSUE TITLE
Solve code smells for JavaRenderer

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#235]
#### Reason/Context
Based on the following [sonarcloud issues](https://sonarcloud.io/project/issues?fileUuids=AXjKlPosVLGRvzF4eQL5&id=asyncapi_generator-model-sdk&resolved=false) we should remove all code smells from [JavaRenderer](https://github.com/asyncapi/modelina/blob/master/src/generators/java/JavaRenderer.ts).

Make sure to read the readme file [how to contribute](https://github.com/asyncapi/modelina#contributing), if you have any questions feel free to reach out here, or in our [Slack](https://www.asyncapi.com/slack-invite).

**Comment by Blakelist7** [comment]
Hey, @jonaslagoni can I try this one too ?

**Comment by jonaslagoni** [comment]
> Hey, @jonaslagoni can I try this one too ?

@Blakelist7 of course, go for it 👍

**Comment by Blakelist7** [comment]
Thank you

1) In 1st and 3rd issue we have to rename `type`, `value` with let's say `mtype`, `mvalue` respectively, right? I am not good with variable names 😅  so do suggest.

2) In the 2nd issue we have to Refactor the code to not use nested template literals, right?

**Comment by jonaslagoni** [comment]
>     1. In 1st and 3rd issue we have to rename `type`, `value` with let's say `mtype`, `mvalue` respectively, right? I am not good with variable names 😅  so do suggest.

Yea that makes sense 👍 

> * In the 2nd issue we have to Refactor the code to not use nested template literals, right?

Yep 👍 

Just a quick hint, in sonarcloud when you see the issues you can click on `Why is this an issue?` where it will show you an example compliant solution and noncompliant 🙂
