### ISSUE TITLE
Generated model requires unknown imports 

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#238]
#### Describe the bug
At the moment the generators have no way of telling the user which imports they require.

For example, for the Java generator, it generates enums with the expectation of `com.fasterxml.jackson` library to be present, however, the user has no way of knowing it is.

#### Expected behavior
I expected to be able to generate the model as is, without having to require me to dig into the generator to figure out which imports/required libraries are needed.

**Comment by magicmatatjahu** [comment]
We can add helper array in each generation of model where dev/user can pass needed dependencies in presets/generators for given model.

**Comment by jonaslagoni** [comment]
> We can add helper array in each generation of model where dev/user can pass needed dependencies in presets/generators for given model. Something like we have for `getNearestDependencies()` function, but as an array/object :)

Good idea 👍

I just see a dilemma down the line. You now have a list of dependencies that are required for the model. But in your project (where the user output writes the models to) we require you to manually add those (dynamic) dependencies to your project dependencies... Then the user would need to "know" about the dependencies anyway 😕 Of course it helps in importing the dependencies in the model output file, just not for the project itself.

**Comment by magicmatatjahu** [comment]
> I just see a dilemma down the line. You now have a list of dependencies that are required for the model. But in your project (where the user output writes the models to) we require you to manually add those (dynamic) dependencies to your project dependencies... Then the user would need to "know" about the dependencies anyway 😕 Of course it helps in importing the dependencies in the model output file, just not for the project itself.

We can log all unique dependencies when someone will generate models as post-generation hook and only inform that project needs given deps to property work.

**Comment by jonaslagoni** [comment]
Could do yea 🤔 

Well, an issue for a later day I guess.
