### ISSUE TITLE
Add a skeleton generator structure 

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#256]
#### Reason/Context
At the moment it takes a lot of effort to set up new language support.

A code skeleton with the bare minimum would help along way.

**Comment by jonaslagoni** [comment]
Still relevant.

**Comment by ritik307** [comment]
@jonaslagoni @magicmatatjahu i would like to work on this issue 😊

**Comment by jonaslagoni** [comment]
> @jonaslagoni @magicmatatjahu i would like to work on this issue 😊

Great @ritik307! Feel free to ping us if have any questions.
