### ISSUE TITLE
User-centric docs

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#287]
#### Reason/Context
At the moment all docs are contributor-centric and do not explain how a user can use the project.

#### Description
We need to add user-centric docs together with examples in generator language.

Should solve the following issues: https://github.com/asyncapi/modelina/issues/318 #296 https://github.com/asyncapi/modelina/issues/45

**Comment by jonaslagoni** [comment]
The initial take on how we could change the documentation to be more user-centric. I declared each question as a potential use-case (or more specifically a feature in Modelina) that the user of the library can encounter. Each of these use-cases will be an individual document, that will explain how to accomplish it and the reason behind it.

1. Generate Go models
3. Generate C# models
4. Generate Java models
5. Generate TypeScript models
6. Generate JavaScript models
7. Integrate Modelina in a website
8. Integrate Modelina in an AsyncAPI generator template
9. Generate each model in the same file
10. Generate a model in separate files
11. Change the generated indentation type and size
12. Change the naming format for properties
12. Change the naming format for data models
13. Include a custom function in the data model
15. Use the models for data transfer
16. Extend the logic of an existing renderer
17. Build your own model renderer
18. Create your own models from the ground up, instead of a supported input
 
## Language-specific use-cases
### TypeScript
1. Generate an `interface` instead of `class`
2. Generate un/marshal functions for each class


### Java
1. Include `equals` function for the class
2. Include `hashCode` function for the class
3. Change the collection type for arrays
4. Include `toString` function for the class
5. Include `Java doc` for properties
6. Include `javax` validation constraints annotations for properties
7. Include `Jackson` annotations for the class

Anything missing?

**Comment by derberg** [comment]
The majority of these docs topics are about coding, using Modelina API. Providing initial docs is easy, harder to maintain in the future. Did you plan to write just markdown or rather `examples` for each, examples that can be tested on a PR?

**Comment by jonaslagoni** [comment]
> The majority of these docs topics are about coding, using Modelina API. Providing initial docs is easy, harder to maintain in the future. Did you plan to write just markdown or rather `examples` for each, examples that can be tested on a PR?

Good point 🤔 Most of these are actually already in place as tests. They are just all over the place (not structured to be easily discovered based on example), would you suggest we create an extra specific test per example, or restructure the tests, so there are no duplicates @derberg ?

**Comment by derberg** [comment]
for user most important is example, not test itself so might be that tests are in one location, refactored to not have duplications. More important is to have "runnable examples"

**Comment by magicmatatjahu** [comment]
> Each of these use-cases will be an individual document, that will explain how to accomplish it and the reasons behind it. 

Do we really need this? 🤔  I think that idea having each language as separate document with possible options - described by examples, not by tables like currently - should be better. For the rest use cases we can create `advanced.md` file for the cases like `Use the models for data transfer`, `Include a custom function in the data model` and `integration.md` to describe integration with Generator, front-end app etc.

When we are talking about tests, it's ok for me, but as I remember the test cases, probably we should restructure them.

**Comment by derberg** [comment]
> When we are talking about tests, it's ok for me, but as I remember the tests structure, probably we should restructure them.

it can be separate to not mix with library itself as they are not library-related but rather examples only + they work as integration tests too (which is then library related) 😆

**Comment by smoya** [comment]
> it can be separate to not mix with library itself as they are not library-related but rather examples only + they work as integration tests too (which is then library related) 😆

In that way, we ensure provided examples are real working examples 👍

**Comment by jonaslagoni** [comment]
>  I think that idea having each language as separate document with possible options - described by examples, not by tables like currently - should be better. For the rest use cases we can create `advanced.md` file for the cases like `Use the models for data transfer`, `Include a custom function in the data model` and `integration.md` to describe integration with Generator, front-end app etc.

@magicmatatjahu you are right, we should probably bundle a lot of the cases together. 

So to sum it up, what if we divide it into:
- `integration.md` 
    - Listing the different, tested integration methods.
- `advanced.md`
    - For advanced customization of the output.
- `<language>.md`
    - For language specific use-cases.

For the test structure, we can address it later, not anything we have to decide upon now 🙂 

> it can be separate to not mix with library itself as they are not library-related but rather examples only + they work as integration tests too (which is then library related) 😆

> In that way, we ensure provided examples are real working examples 👍

@derberg @smoya I love killing two birds with one stone 😄 Solves https://github.com/asyncapi/modelina/issues/296.
