### ISSUE TITLE
Add End to End test so we ensure users can use @asyncapi/modelina npm package.

### ISSUE THREAD

**Issue by smoya** [asyncapi/modelina#296]
#### Reason/Context
Recently I tried to run the example located at https://github.com/asyncapi/modelina#example with no success.
When compiling TS, I got the few errors. The issue behind was fixed (thanks to super fast @magicmatatjahu ⚡ ) by https://github.com/asyncapi/modelina/pull/290 but also https://github.com/asyncapi/modelina/pull/292, https://github.com/asyncapi/modelina/pull/294 and https://github.com/asyncapi/modelina/pull/297.

The point is that I, as a user, couldn't run the example at all. Meaning  more users like me, were not able to use Modelina either.

I suggest we run a test testing `@asyncapi/modelina` module  through the example, running it from a user point of view so we ensure Modelina can, at least, be used by any user and new releases don't break it.

#### Description
A test that creates a simple project, installs modelina npm package (from local code) and compiles the TS example.
More details and suggestions:

- Build the project a
- Move the example from the `README.md` to it's own file so we can reuse it in this test.
- a `tsconfig.json` file like https://gist.github.com/ccnokes/e8c419e2874111c5ef41cc1442680acb should be enough.
- `tsc -p tsconfig.json` command should exit with code zero. Js file should be there.

**Comment by jonaslagoni** [comment]
I think we can close this issue now with the introduction of example tests. Thoughts @smoya?

**Comment by smoya** [comment]
> I think we can close this issue now with the introduction of example tests - https://github.com/asyncapi/modelina/tree/master/examples. Thoughts @smoya?

What do you mean by example tests? Are we running a full end to end test where we compile modelina from source code?

**Comment by jonaslagoni** [comment]
> What do you mean by example tests? Are we running a full end to end test where we compile modelina from source code?

Hmm, I guess we arent no 🤔

**Comment by jonaslagoni** [comment]
With the new [example tests](https://github.com/asyncapi/modelina/tree/master/examples) and [black box tests](https://github.com/asyncapi/modelina/tree/master/test/blackbox), I would comfortably say we have as much end-to-end tests and we possibly can 😄

Closing this issue.
