### ISSUE TITLE
Including referenced models as dependencies

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#330]
#### Describe the bug
Given a JSON Schema which results in two models being generated such as the following:
```json
{
      "type": "object",
      "required": ["lumen"],
      "properties": {
	      "lumen": {
		      "type": "integer",
		      "description": "How bright should the light be."
	      },
	      "test": {
		      "type": "object",
		      "$id": "OtherModel",
		      "required": ["lumen"],
		      "properties": {
			      "lumen": {
				      "type": "integer",
				      "description": "How bright should the light be."
			      }
		      }
	      }
      }
}
```

When we want to render these models we do something along these lines (using TS generator as example) :
```ts
const typescriptGenerator = new TypeScriptGenerator();
const generatedModels = await typescriptGenerator.generate(input);
for (const generatedModel of generatedModels) {
  const modelFileName = `${FormatHelpers.toPascalCase(generatedModel.modelName)}.ts`;
  const modelFileContent = `
${generatedModel.dependencies.join('\n')}
${generatedModel.result}
  `;
}
```

Problem is that the generated class includes a property called `private _test?: OtherModel;`, but the `dependencies` does not include this other model. 

So the question remains, how do we best give the user access to which other models that we depend upon?

I see two ways to solve this.

1. We create a `modelDependencies` property (similar to `dependencies` but only for models which we depend upon). This will give greater power to the user. In terms of complexity, #287 #288 would simplify normal use-cases and still allow for greater freedom for complex use-cases.
1. Utilize the existing `dependencies` list. It will create a problem though since we cant dynamically locate models differently from one another, as we would need to add the dependency `import OtherModel from ./OtherModel.ts`. However, the generator has no knowledge (for now) of what you do with the models... So that would be tricky to implement IMO.

**Comment by jonaslagoni** [comment]
cc @magicmatatjahu

**Comment by magicmatatjahu** [comment]
I prefer way with going with `dependencies` list. We should avoid unnecessary props like `modelDependencies`.

> It will create a problem though since we cant dynamically locate models differently from one another...

Even if we traverse all properties/patternProperties/additionalProperties of model and check if given prop has `$ref`? :)

We can also extend `dependencies` list to include info about imported models like:

```ts
dependencies = [
  {
    import: `import OtherModel from './OtherModel'`,
    type: 'model'
  },
    {
    import: `import something from 'something'`,
    type: 'package'
  }
]
```

but I see the problem with path to the `OtherModel` because user should have possibility to defined it in another place that the rendered model.

**Comment by jonaslagoni** [comment]
> Even if we traverse all properties/patternProperties/additionalProperties of model and check if given prop has `$ref`? :)

It is not a problem traversing the model for `$ref`s as we will need to do it regardless. However, `import OtherModel from './OtherModel'` will not be possible to assume as in theory it can be located anywhere (as the functionality currently allows this).

With `modelDependencies` you would of course need to manually keep track of where you output the models. So when dependencies need to be rendered, you would need to do something like:
```js
const typescriptGenerator = new TypeScriptGenerator({ ... });
const generatedModels = await typescriptGenerator.generate(asyncapi);
const fileNaming = (modelName) => {
  return `${FormatHelpers.toPascalCase(modelName)}.ts`
};
const modelLocations = {};
for (const generatedModel of generatedModels) {
  const modelFileName = fileNaming(generatedModel.modelName);
  modelLocations[generatedModel.modelName] = `./${modelFileName}`;
  const fileContent = `
${generatedModel.dependencies.join('\n')}
${generatedModel.modelDependencies.map((modelName) => {return modelLocations[fileNaming(modelName)]})}
${generatedModel.result}
  `;
}
```
This is of course not a silver bullet because now referenced models need to be listed in order (which we currently do not comply with), and what about circular dependencies, you need to handle that as well.

Another reason why we might want to split the dependencies into two lists is that maybe you place all models inside the same file, here you won't need the model dependencies, as they already have access to each other.

> We can also extend `dependencies` list to include info about imported models like:

I honestly think this is the best approach at the moment. Do you foresee any problems later on? 🤔

**Comment by jonaslagoni** [comment]
We need to remember that each model has a `getNearestDependencies` function, meaning you can actually include this already, and won't need any extra implementation.

**Comment by jonaslagoni** [comment]
Closing as we already have the functionality to retrieve the models.
