### ISSUE TITLE
Swagger / OpenAPI input

### ISSUE THREAD

**Issue by voxpelli** [asyncapi/modelina#360]
#### Reason/Context
Please try answering few of those questions
- Why we need this improvement?
  - Swagger / OpenAPI is very similar to AsyncAPI and also builds upon JSON Schema style model definitions
- How will this change help?
  - Enable more types of conversions and a more complete toolchain for models of all types of sources.

#### Description
Please try answering few of those questions
- What changes have to be introduced?
  - Probably the same that was needed to support AsyncAPI on top of JSON Schema
- Will this be a breaking change?
  - Nope
- How could it be implemented/designed?
  - Probably the same way that AsyncAPI was

**Comment by jonaslagoni** [comment]
Just leaving this for later:

- [OpenAPI 3.0.3](https://spec.openapis.org/oas/v3.0.3) - superset of [draft-wright-json-schema-00](https://datatracker.ietf.org/doc/html/draft-wright-json-schema-00)
- [OpenAPI 3.1](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#schemaObject) - superset of [2020-12 draft](https://tools.ietf.org/html/draft-bhutton-json-schema-00)
- [Swagger 2.0](https://swagger.io/specification/v2/) - superset of [JSON Schema Specification Draft 4](http://json-schema.org/specification-links.html#draft-4)

**Comment by jonaslagoni** [comment]
@voxpelli do you by any chance have any Swagger/OpenAPI documents you can share, that I can test with? 🙂 

Also, do you mind if I ping you for giving a review once the features are complete?

**Comment by voxpelli** [comment]
@jonaslagoni Unfortunately nothing public, but I do remember the file I was looking at this time as being a Swagger 2.0 file, so #378 would solve it.

Please ping me when you want a review!

**Comment by jonaslagoni** [comment]
@voxpelli the PR is ready from our side to be merged, if you want to give your review, now is the time 😄 Let me know if you don't have time to review it, so we don't wait in vain 👍

I suggest to download the branch and adapt the example to fit your need - https://github.com/jonaslagoni/generator-model-sdk/tree/feature/swagger_new/examples/swagger2.0-from-object

**Comment by voxpelli** [comment]
Still relevant :)

**Comment by voxpelli** [comment]
Still relevant :)

**Comment by AnimeshKumar923** [comment]
still valid? @jonaslagoni @voxpelli

**Comment by voxpelli** [comment]
I guess this still holds true:

> still need to support OpenAPI 3.1

But maybe better to add that as a new issue? To make it clearer?

**Comment by jonaslagoni** [comment]
Lets keep this closed and focus on https://github.com/asyncapi/modelina/issues/1749 🙂
