### ISSUE TITLE
Typescript: Using oneOf leads to creation and use of an anonymous schema rather than use of a union type

### ISSUE THREAD

**Issue by stefanerwinmayer** [asyncapi/modelina#367]
#### Describe the bug
Typescript: Using oneOf leads to creation and use of an anonymous schema rather than use of a union type.

#### How to Reproduce

api.yaml
```
asyncapi: 2.1.0
info:
  title: oneOf bug
  version: "0.1.0"
channels: {}
components:
  messages:
    a:
      payload:
        $ref: "#/components/schemas/a"

  schemas:
    a:
      type: object
      properties:
        prop:
          oneOf:
            - $ref: "#/components/schemas/b"
            - $ref: "#/components/schemas/c"

    b:
      type: object
      properties:
        someProp:
          type: integer
          format: int32

    c:
      type: object
      properties:
        anotherProp:
          type: integer
          format: int32

```
Example code to consume the api:
```
import { TypeScriptGenerator } from "@asyncapi/modelina";
import fs from "fs";
import parser from "@asyncapi/parser";

const generator = new TypeScriptGenerator({ modelType: "interface" });
const contents = fs.readFileSync("api.yaml", "utf8");
const doc = await parser.parse(contents);

async function generate() {
  const models = await generator.generate(doc);
  models.forEach((model) => console.log(model.result));
}

generate();
```
Generated outcome:
```
export interface A {
  prop?: AnonymousSchema_1;
  additionalProperties?: Map<String, object | string | number | Array<unknown> | boolean | null>;
}
export interface AnonymousSchema_1 {
  someProp?: number;
  anotherProp?: number;
  additionalProperties?: Map<String, object | string | number | Array<unknown> | boolean | null>;
}
```

#### Expected behavior
According to my understanding, this should be generated instead:
```
export interface A {
  prop?: B | C
  additionalProperties?: Map<String, object | string | number | Array<unknown> | boolean | null>;
}
export interface B {
  someProp?: number;
  additionalProperties?: Map<String, object | string | number | Array<unknown> | boolean | null>;
}
export interface C {
  anotherProp?: number;
  additionalProperties?: Map<String, object | string | number | Array<unknown> | boolean | null>;
}
```

**Comment by stefanerwinmayer** [comment]
Prematurely submitted by accident. Will continue to edit this.

**Comment by jonaslagoni** [comment]
I am in the process of rewriting the underlying model, as this scenario is currently not possible and too tightly coupled with JSON Schema. Once the rewrite is complete I will take a look at this 👍

**Comment by stefanerwinmayer** [comment]
Thank you @jonaslagoni. I will eagerly await your rewrite.

**Comment by panwauu** [comment]
As the union is a typescript specific feature, maybe it could help to think about how the expected output should look like with other generators.

**Comment by cameronbraid** [comment]
I would suggest that union types in java could be done if asyncapi adopted the openapi spec in regards to discriminators

https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/

then you could do :

```
            discriminator:
              propertyName: objectType
              mapping:
                a: '#/components/schemas/a'
		b: '#/components/schemas/b'
``

```
public abstract class A {
  abstract String getObjectType();
  Map<String, Object> additionalProperties;
}

public class B extends A {
  Long someProp;

}
public class C extends A {
  Long anotherProp;
}

```

**Comment by kennethaasan** [comment]
At Sportradar we're trying to adopt AsyncAPI with Modelina, and we are facing this issue. Is this being worked on in the next branch? If not, I can try to solve it for TypeScript and possibly Java at least.

**Comment by jonaslagoni** [comment]
> At Sportradar we're trying to adopt AsyncAPI with Modelina, and we are facing this issue. Is this being worked on in the next branch? If not, I can try to solve it for TypeScript and possibly Java at least.

It is yes 🙂

**Comment by kennethaasan** [comment]
Awesome! I'll share our use case in case you need a spec to test with. I would expect a data model for _Message_, _Goal_, _YellowCard_, and hopefully _Event_ using inheritance. 

```yaml
asyncapi: "2.4.0"
info:
  title: Soccer
  version: "v1.0.0"
  description: Soccer

servers: {}

defaultContentType: application/json

channels: {}

components:
  messages:
    Message:
      name: Message
      payload:
        $ref: "#/components/schemas/Message"

  schemas:
    Message:
      $id: Message
      type: object
      additionalProperties: false
      properties:
        event:
          $id: Message::Event
          oneOf:
            - $ref: "#/components/schemas/Goal"
            - $ref: "#/components/schemas/YellowCard"

    Event:
      $id: Event
      type: object
      additionalProperties: false
      properties:
        id:
          type: string
      required:
        - id

    Goal:
      $id: Event::Goal
      type: object
      additionalProperties: false
      allOf:
        - $ref: "#/components/schemas/Event"
        - type: object
          properties:
            scored_by_team_id:
              type: string
            scored_by_player_id:
              type: string
      required:
        - scored_by_team_id
        - scored_by_player_id

    YellowCard:
      $id: Event::YellowCard
      type: object
      additionalProperties: false
      allOf:
        - $ref: "#/components/schemas/Event"
        - type: object
          properties:
            for_team_id:
              type: string
            for_player_id:
              type: string
      required:
        - for_team_id
        - for_player_id
```

**Comment by jacopomaroli** [comment]
I think the problem is here https://github.com/asyncapi/modelina/blob/7a2394956f8f82670e10859efd6b1c67c4487033/src/interpreter/Interpreter.ts#L85-L86

It shouldn't interpret and combine the schemas for oneOf but should just reference the underlying schemas https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/#anyof-vs-oneof

**Comment by jacopomaroli** [comment]
hey folks, I made some changes to address this. I'll open a PR later today/tomorrow after running the tests. feel free to reference the feature branch and let me know if this works for you
https://github.com/asyncapi/modelina/compare/master...jacopomaroli:modelina:fix_oneOf_impl?expand=1
