### ISSUE TITLE
Figure out how to render union types for Java class

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#391]
#### Reason/Context
For languages such as TS it is easy to create union types, however, for Java it is a bit more difficult as there are no native types for this.

So how should we handle those?

**Comment by Tenischev** [comment]
In `java-spring-template` I generate inner class for `allOf` where each property of aggregation is present as variable, please have a look:
https://github.com/asyncapi/java-spring-template/blob/9ba5e5a8c6f19376b2367c9803b826e88188a2d0/template/src/main/java/com/asyncapi/model/%24%24objectSchema%24%24.java#L85-L112


for support of `anyOf` or `oneOf` an empty interface will be generated:
https://github.com/asyncapi/java-spring-template/blob/9ba5e5a8c6f19376b2367c9803b826e88188a2d0/template/src/main/java/com/asyncapi/model/%24%24objectSchema%24%24.java#L67-L83

with piece of magic generation in hook: https://github.com/asyncapi/java-spring-template/blob/9ba5e5a8c6f19376b2367c9803b826e88188a2d0/hooks/04_processOneOfAnyOf.js

**Comment by f-lutz-sportradar** [comment]
I'm not sure whether there is any other discussion about this subject, but one possible way I can think about solving the union (allOf) in jsava would be: In case of an allOf having multiple $ref, for each $ref, create an Interface having the setters / getters for all the properties on the particular reference and add all the properties in the class. This way, it's possible to reuse the same interface in multiple classes.

**Comment by kennethaasan** [comment]
We're working on solving this in https://github.com/asyncapi/modelina/pull/960

**Comment by memdal** [comment]
Adding to @f-lutz-sportradar's comment.
Representing union types as a Java interface also has the added advantage of having out of the box deserialization support from Jackson with the [@JsonTypeInfo](https://fasterxml.github.io/jackson-annotations/javadoc/2.4/com/fasterxml/jackson/annotation/JsonTypeInfo.html) annotation.
Cat/Dog union type example:
```java
public class Cat implements Pet { }
```
```java
public class Dog implements Pet { }
```
```java
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "type") // type being the discriminator
@JsonSubTypes({
    @JsonSubTypes.Type(value = Cat.class, name = "Pet.Cat"),
    @JsonSubTypes.Type(value = Dog.class, name = "Pet.Dog")
})
public interface Pet { }
```
```java
new ObjectMapper().readValue("{ \"type\": \"Pet.Cat\" }", Pet.class); // Will deserialize to Cat based on discriminator -> class mapping.
```

I'd also like to have:
 - Sealed interfaces for exhaustive pattern matching in switch expression/statements.
 - Interface getters/setters for intersecting properties in the subtypes. 

The only challenge I see is that union types containing non-generated classes such as Integer/String will need extra boxing for us to add them as an interface subtype.

**Comment by jonaslagoni** [comment]
Still relevant.

**Comment by dlkj** [comment]
@jonaslagoni - with #1271 and #1276 is there anything outstanding on this issues?

**Comment by jonaslagoni** [comment]
Think we can close it yea 👍
