### ISSUE TITLE
Show how to generate TS data models with un/marshal functions

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#418]
## What to solve

Sometimes you want to use the models for data transfers, and while most cases would work out of the box, custom serializer functionality is needed for the advanced cases. 

If you generated the data models based on a JSON Schema document and you want the serialized data to validate against the schema, this functionality is REQUIRED.

This can be done by including the preset `TS_COMMON_PRESET` using the option `marshalling`.

Use the following code in the example:
```ts
generator = new TypeScriptGenerator({ 
  presets: [
    {
      preset: TS_COMMON_PRESET,
      options: {
        marshalling: true
      }
    }
  ]
});
```

Duplicate the folder https://github.com/asyncapi/modelina/tree/master/examples/TEMPLATE and rename it to `typescript-generate-unmarshal`. Update any relevant documentation.

<details>
<summary>Some folks want more specific tasks to complete, or use this if you get stuck - CLICK ME</summary>
<p>

This issue is specially designed for first-time contributors, that want to contribute their very first code. If you are accustomed to how to solve issues in AsyncAPI, you can skip some of the steps.

#### What to know before getting started
Before actually getting started with solving the issue, there are a few things that need to be set up:
- Make sure you familiarize yourself with our [code-of-conduct](https://github.com/asyncapi/.github/blob/master/CODE_OF_CONDUCT.md) and [contributor guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md) 
- We work on forks of repositories and branches in forks, if you are unsure how to set this up you can follow the guide on our [git-workflow setup](https://github.com/asyncapi/.github/blob/master/git-workflow.md).

Feel free to reach out either here in the issue, or on [slack under #tooling](https://www.asyncapi.com/slack-invite) if you have any questions or are stuck, we will gladly help.

## Getting started

This is a task list, that you copy into your PR description to ensure everything is included, this list walks you through each step as to how to solve this issue. It assumes that you have already set up your fork and branch and are ready to commit code.
- [ ] Duplicate the folder `https://github.com/asyncapi/modelina/tree/master/examples/TEMPLATE` and rename it to `typescript-generate-unmarshal`. This will give you a good base to start out with.
- [ ] Adapt the documentation about the feature and ensure the example are linked correctly.
    - The docs that need to change are the following: [docs/languages/TypeScript.md#generate-unmarshal-functions-for-classes](https://github.com/asyncapi/modelina/blob/master/docs/languages/TypeScript.md#generate-unmarshal-functions-for-classes)
    - The documentation must reference an actual example that is tested and contain no code itself. It is because the docs will inevitably become desynchronized and display incorrect code.
- [ ] Adapt the [examples overview](https://github.com/asyncapi/modelina/tree/master/examples/README.md) to include your new example. 
- [ ] Now it is time to adapt the test code (in examples/typescript-generate-unmarshal/index.spec.ts) and the implementation (in examples/typescript-generate-unmarshal/index.ts).
- [ ] Make sure that the test succeeds, by standing in the new example folder and execute `npm run test`.  
- [ ] Make sure that there are no linting errors, by standing in the root folder and execute `npm run lint`. 
- [ ] Create your PR, by selecting your branch that should be merged with the master branch - https://github.com/asyncapi/modelina/compare
- [ ] It is good practice to double-check your PR before requesting a review from someone else, the same way you read an assignment before handing it in.

## Do you have any examples I can check for reference?
We have currently 4 example documentations that you can look for guidance on how to achieve the desired output:
- [How to add logging to the library](https://github.com/asyncapi/modelina/tree/master/docs/advanced.md#add-logging-to-library)
- [Generate models from AsyncAPI documents](https://github.com/asyncapi/modelina/tree/master/docs/usage.md#generate-models-from-asyncapi-documents)
- [Generate models from JSON Schema draft 7 documents](https://github.com/asyncapi/modelina/tree/master/docs/usage.md#generate-models-from-json-schema-draft-7-documents)
- [Generate an interface instead of class](https://github.com/asyncapi/modelina/docs/tree/master/languages/TypeScript.md#generate-an-interface-instead-of-class)

</p>
</details>

**Comment by alequetzalli** [comment]
Happy Hacktoberfest, everyone! ✨✨ Feel free to reach out to me for any questions you may have about adding documentation on these open issues. 🙂

Tag me in your AsyncAPI Doc PRs 📄, my GitHub handle is /alequetzalli 🐙.

**Comment by panwauu** [comment]
I am really interested in the un/marshal functions, but I dont get the idea totally to be honest. Maybe if you get me up to speed, I can tackle this one.

**Comment by jonaslagoni** [comment]
> I am really interested in the un/marshal functions, but I dont get the idea totally to be honest. Maybe if you get me up to speed, I can tackle this one.

Awesome 👍 Of course, which part of the idea dont you get? 🙂

**Comment by jonaslagoni** [comment]
> So does the marshal function generate a json schema in order to validate json data or does it validate the data directly including validation of all properties?

It does not validate anything on it's own, maybe it should do that? 🧐 That's actually not a bad feature 🥳 Want to create a feature request for it?

 Currently, the un/marshalling functions only convert to and from JSON, nothing more nothing less. But indirectly it ensures that if you generated the models with JSON Schema (or indirectly AsyncAPI and OpenAPI inputs, as they both define payloads with JSON Schema), it complies with the schema 🙂

**Comment by jonaslagoni** [comment]
Hmm, true, might have been too much to mix that in 😅 

It is needed any time you wish to convert the models to and from JSON i.e. when using the data models in the context of sending data back and forth. 

While you can do `JSON.stringify(datamodel)`, it will definitely give you an output that can be used in most cases, however, there are edge cases where it does not:
1. If you generated the data models from JSON Schema, and you want the models once marshaled to JSON to validate against the Schema (This is because what you defined as property name, might not be the property name generated as an output)
1. When you send data between two applications, written in different languages i.e. TS and C#, and the data models are generated with Modelina, it will need a shared understanding of the model in some sense. Similar to reason 1.

That's why I recommend, to generate the un/marshalling functionality alongside the data models and use `model.marshal()` and `Model.unmarshal(json)` instead of the native way of converting it. 

Maybe it provides better context if you take a look at this test: https://github.com/asyncapi/modelina/blob/fa6d914321af8c453a5e4f22c541c7cc829ed8de/test/generators/typescript/preset/MarshallingPreset.spec.ts#L227

Here I am using 3 models generated from Modelina (copy/pasted into the test) where I highlight that we can validate JSON against the [JSON Schema they are generated from](https://github.com/asyncapi/modelina/blob/fa6d914321af8c453a5e4f22c541c7cc829ed8de/test/generators/typescript/preset/MarshallingPreset.spec.ts#L5)
