### ISSUE TITLE
C# presets uses .NET dependencies

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#446]
There is no clear documentation about which presets uses .NET dependencies, and I did not even check it myself when creating them.

We need some clear structure so users know what presets they can use.

**Comment by jonaslagoni** [comment]
Still relevant.

**Comment by Samridhi-98** [comment]
@jonaslagoni  I would like to work on it.
Will you  please explain the issue more and where to start?

**Comment by jonaslagoni** [comment]
Awesome @Samridhi-98!

The [Csharp preset that add serializer capabilities to the data models](https://github.com/asyncapi/modelina/tree/master/examples/csharp-generate-serializer) uses the [following dependencies](https://github.com/asyncapi/modelina/blob/b819c6fff9337005c6837be81daadb23901cfc83/src/generators/csharp/presets/JsonSerializerPreset.ts#L250):

- System.Text.Json
- System.Text.Json.Serialization
- System.Text.RegularExpressions

I am having difficulty figuring out whether these dependencies har .NET specific dependencies or something that will work in all C# environments. So that is more or less the task. 

Figure out if any of the preset dependencies are .NET specific. Maybe they are not and we can close the issue, if they are, we need to add some documentation that explains it 🙂

**Comment by Samridhi-98** [comment]
> Awesome @Samridhi-98!
> 
> The [Csharp preset that add serializer capabilities to the data models](https://github.com/asyncapi/modelina/tree/master/examples/csharp-generate-serializer) uses the [following dependencies](https://github.com/asyncapi/modelina/blob/b819c6fff9337005c6837be81daadb23901cfc83/src/generators/csharp/presets/JsonSerializerPreset.ts#L250):
> 
> * System.Text.Json
> * System.Text.Json.Serialization
> * System.Text.RegularExpressions
> 
> I am having difficulty figuring out whether these dependencies har .NET specific dependencies or something that will work in all C# environments. So that is more or less the task.
> 
> Figure out if any of the preset dependencies are .NET specific. Maybe they are not and we can close the issue, if they are, we need to add some documentation that explains it 🙂

Okay, I got it.
I will check and let you know 😊

**Comment by Samridhi-98** [comment]
@jonaslagoni  I found this [article](https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-apis/) and also tried running the sample example on online CSharp compiler and got the error mentioned below. 🙂

![image](https://user-images.githubusercontent.com/54466041/153048888-dfddd723-ed13-44fb-acba-acbf89ccf445.png)

**Comment by jonaslagoni** [comment]
How do you suggest we let the users know of this dependency? 🙂

**Comment by Samridhi-98** [comment]
> How do you suggest we let the users know of this dependency? 🙂

In the documentation of CSharp, we can add an `important note` where we will provide info for this.

**Comment by jonaslagoni** [comment]
Do you mind providing a PR for this? 

Keep in mind we should use the same setup, regardless of whether it's a C# preset that have certain dependencies, or Java 🙂

**Comment by Samridhi-98** [comment]
> Do you mind providing a PR for this?
> 
> Keep in mind we should use the same setup, regardless of whether it's a C# preset that have certain dependencies, or Java 🙂

Sure, will do it🙂
