### ISSUE TITLE
Document how to implement generator for language

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/modelina#45]
After first release, we will have only 3 languages which we will support - JS, TS and Java with custom presets, e.g. with Jackson support (Java). We should document how community can contribute to our `model-sdk` with implementation of new languages and presets. Documents should contain:

- [X] how to extend `AbstractGenerator`.
- [ ] how to extend `AbstractRenderer`.
- [ ] how to write custom renderers and how to connect them to the generator.
- [X] how to write default preset
- [X] how to write custom presets for given language

Also mentioned in https://github.com/asyncapi/generator-model-sdk/issues/70
- [X] how generator works

**Comment by jonaslagoni** [comment]
Still relevant.

**Comment by jonaslagoni** [comment]
Because of https://github.com/asyncapi/modelina/pull/850 I am gonna close this one. Most docs have been redone and many of these things defined.
