### ISSUE TITLE
Special cases in enum values fails to generate accurate enum output

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#450]
#### Describe the bug
Given the schema:
```
{ "enum": ["medium", "medium+"] } 
```
It would generate the enum output 

```
export enum X {
  MEDIUM = "medium",
  MEDIUM = "medium+"
}
```

Which cannot happen as no duplicate keys may be generated

**Comment by panwauu** [comment]
Also I noticed that in OpenAPI generator they have a [similar issue](https://github.com/OpenAPITools/openapi-generator/issues/5110). Sadly they did not solve the problem yet so we cannot see how they tackled it

**Comment by jonaslagoni** [comment]
@panwauu for sure!

Each language has its own rendering of the raw enums.

Gonna focus on the TS enum renderer, as I assume this is the one you want to solve?

More precisely [it is the normalizeKey function you want to look at](https://github.com/asyncapi/modelina/blob/4248b55da0e5e7c9c44869b2ea8a686ee362fc30/src/generators/typescript/renderers/EnumRenderer.ts#L40), this is what determines the key of the enum.

If the enum value is a string (which can contain special chars), then we need to format the key here - https://github.com/asyncapi/modelina/blob/4248b55da0e5e7c9c44869b2ea8a686ee362fc30/src/generators/typescript/renderers/EnumRenderer.ts#L53. I.e. where you replace special chars with their full name (create a new function for this, I would probably add it to https://github.com/asyncapi/modelina/blob/master/src/helpers/NameHelpers.ts so we reuse it). 

If you want the index of the enum value, then you need to pass it all the way from the [rendering of all enums](https://github.com/asyncapi/modelina/blob/4248b55da0e5e7c9c44869b2ea8a686ee362fc30/src/generators/typescript/renderers/EnumRenderer.ts#L29) -> which runs the [default item preset](https://github.com/asyncapi/modelina/blob/4248b55da0e5e7c9c44869b2ea8a686ee362fc30/src/generators/typescript/renderers/EnumRenderer.ts#L37) -> [which then normalizes the key](https://github.com/asyncapi/modelina/blob/4248b55da0e5e7c9c44869b2ea8a686ee362fc30/src/generators/typescript/renderers/EnumRenderer.ts#L92).
