### ISSUE TITLE
Broken links to customization

### ISSUE THREAD

**Issue by panwauu** [asyncapi/modelina#483]
I dont know where the links were supposed to lead so I cant fix it. 
BTW is there a tool to check all the links in the documentation? Would be a neat thing ([Issue in .github](https://github.com/asyncapi/.github/issues/92)).

https://github.com/asyncapi/modelina/blob/d72f11fda764b4eeaa0fe83f2c25279ed37b0da8/docs/generators.md?plain=1#L36
https://github.com/asyncapi/modelina/blob/d72f11fda764b4eeaa0fe83f2c25279ed37b0da8/docs/generators.md?plain=1#L37

**Comment by Samridhi-98** [comment]
@jonaslagoni  Is this issue still valid?
I would take this issue,
