### ISSUE TITLE
Implement Python generator and renderers

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/modelina#49]
Implement Python generator and renderers like in TS or Java.

Generator should have possibility to define presets for `class`, `enum` type.

Additional: create presets for serialisation/converters from json.

**Comment by joe-narvaez** [comment]
If we could get dataclass and/or pydantic support, that would be ideal.

**Comment by humbleengineer** [comment]
> If we could get dataclass and/or pydantic support, that would be ideal.

Double thumbs up to that!

**Comment by derberg** [comment]
@damaru-inc hey, this one might be interesting for you. Since you created https://github.com/asyncapi/python-paho-template/ it means to me you are a good candidate to contribute here. Side effect is that later you can use Modelina in your template to generate some Python code

**Comment by jonaslagoni** [comment]
Tasklist to implement it:

- [ ] Duplicate one of the existing generators, for example, the Java generator, (I find it easier to start with that) https://github.com/asyncapi/modelina/tree/master/src/generators
- [ ] Start with empty generator options
  - https://github.com/asyncapi/modelina/blob/57948b508f9f5472f6ee14b2ac130d5e5fee9c1d/src/generators/java/JavaGenerator.ts#L17
  - https://github.com/asyncapi/modelina/blob/57948b508f9f5472f6ee14b2ac130d5e5fee9c1d/src/generators/java/JavaGenerator.ts#L13
- [ ] Adapt reserved keyword list to match it for python - https://github.com/asyncapi/modelina/blob/master/src/generators/typescript/Constants.ts
- [ ] Adapt the core PythonRenderer to render python types - https://github.com/asyncapi/modelina/blob/57948b508f9f5472f6ee14b2ac130d5e5fee9c1d/src/generators/typescript/TypeScriptRenderer.ts#L14
- [ ] I find it easiest to start with [two renders](https://github.com/asyncapi/modelina/tree/master/src/generators/java/renderers) (those that call presets at specific times during the rendering process), one for `Class` and one of `Enum`.
- [ ] Adapt the code being generated for the Class and Enum to match Python.
- [ ] Start with no [presets](https://github.com/asyncapi/modelina/tree/master/src/generators/typescript/presets) as we just start with the bare minimum.
- [ ] Adapt all releated docs. 


For testing (yes we need tests 😄) I would again start by copying one of the existing test collections for a generator https://github.com/asyncapi/modelina/tree/master/test/generators/typescript and then remove anything that is not related to what you have in the Python generator.

@mahakporwal02 let me know if this makes sense 🙏

**Comment by mahakporwal02** [comment]
> Tasklist to implement it:
> 
> * [ ]  Duplicate one of the existing generators, for example, the Java generator, (I find it easier to start with that) https://github.com/asyncapi/modelina/tree/master/src/generators
> * [ ]  Start with empty generator options
>   
>   * https://github.com/asyncapi/modelina/blob/57948b508f9f5472f6ee14b2ac130d5e5fee9c1d/src/generators/java/JavaGenerator.ts#L17
>   * https://github.com/asyncapi/modelina/blob/57948b508f9f5472f6ee14b2ac130d5e5fee9c1d/src/generators/java/JavaGenerator.ts#L13
> * [ ]  Adapt reserved keyword list to match it for python - https://github.com/asyncapi/modelina/blob/master/src/generators/typescript/Constants.ts
> * [ ]  Adapt the core PythonRenderer to render python types - https://github.com/asyncapi/modelina/blob/57948b508f9f5472f6ee14b2ac130d5e5fee9c1d/src/generators/typescript/TypeScriptRenderer.ts#L14
> * [ ]  I find it easiest to start with [two renders](https://github.com/asyncapi/modelina/tree/master/src/generators/java/renderers) (those that call presets at specific times during the rendering process), one for `Class` and one of `Enum`.
> * [ ]  Adapt the code being generated for the Class and Enum to match Python.
> * [ ]  Start with no [presets](https://github.com/asyncapi/modelina/tree/master/src/generators/typescript/presets) as we just start with the bare minimum.
> * [ ]  Adapt all releated docs.
> 
> For testing (yes we need tests smile) I would again start by copying one of the existing test collections for a generator https://github.com/asyncapi/modelina/tree/master/test/generators/typescript and then remove anything that is not related to what you have in the Python generator.
> 
> @mahakporwal02 let me know if this makes sense pray

Sure will look into it

**Comment by mahakporwal02** [comment]
Thanks @jonaslagoni :+1:

**Comment by jonaslagoni** [comment]
Solved in https://github.com/asyncapi/modelina/pull/863
