### ISSUE TITLE
Add helper functions to un/marshal data models for JS

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#490]
#### Reason/Context
We need some helper functions to be able to marshal the data model instances to JSON and unmarshal JSON to instances of the data model.

#### Description
The reason we need to write this our self is that we add properties to data models which are technically not properties directly, an example here is `additionalProperties`, as it is rendered as a property in the data model, but when you want to convert an instance of the data model to bytes or JSON for a payload, it should not be used as is but unwrapped.

**Comment by Samridhi-98** [comment]
@jonaslagoni  I would like to work on this issue.

**Comment by jonaslagoni** [comment]
@Samridhi-98 feel free to ping me if you need starting points 👍

**Comment by Samridhi-98** [comment]
> @Samridhi-98 feel free to ping me if you need starting points 👍

I have implemented the un/marshalling for JS and I ran the `npm run test`, it passed all test suits.
Let me know if I need some other command to test the implementation or simply open the PR?

**Comment by jonaslagoni** [comment]
Hey @Samridhi-98 do you mind adding a draft PR? 🙂 That way it is easier to see what has been done.

However, a test such as this one would be necessary: https://github.com/asyncapi/modelina/blob/5622923731bab2f45c4ede416761227bd4557ce3/test/generators/typescript/preset/MarshallingPreset.spec.ts#L27

**Comment by Samridhi-98** [comment]
> 

Yeah, sure I will draft a PR.
