### ISSUE TITLE
Special cases in enum values fails to generate accurate enum keys for Java generator

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#502]
#### Describe the bug
Thanks to @panwauu, we already have it solved in the TS generator, see https://github.com/asyncapi/modelina/issues/450 and fix in https://github.com/asyncapi/modelina/pull/497.

We need to apply the same fix we did here:
https://github.com/asyncapi/modelina/blob/2a8659da465f53f9cfe1097a622ed82d0fa7594c/src/generators/typescript/renderers/EnumRenderer.ts#L53
to this line:
https://github.com/asyncapi/modelina/blob/2a8659da465f53f9cfe1097a622ed82d0fa7594c/src/generators/java/renderers/EnumRenderer.ts#L52

**Comment by quadrrem** [comment]
I gave it a shot in the PR #526 above, please let me know what you think.
