### ISSUE TITLE
Special cases in enum values fails to generate accurate enum keys for C# generator

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#503]
#### Describe the bug
Thanks to @panwauu, we already have it solved in the C# generator, see https://github.com/asyncapi/modelina/issues/450 and fix in https://github.com/asyncapi/modelina/pull/497.

We need to apply the same fix we did here:
https://github.com/asyncapi/modelina/blob/2a8659da465f53f9cfe1097a622ed82d0fa7594c/src/generators/typescript/renderers/EnumRenderer.ts#L53
to this line:
https://github.com/asyncapi/modelina/blob/2a8659da465f53f9cfe1097a622ed82d0fa7594c/src/generators/csharp/renderers/EnumRenderer.ts#L110

**Comment by ron-debajyoti** [comment]
Hi @jonaslagoni , let me take this up and try to solve this issue !

**Comment by jonaslagoni** [comment]
No need to ask for permission, go right ahead @ron-debajyoti 🙂

**Comment by ron-debajyoti** [comment]
Hi @jonaslagoni !
I followed the same process used to fix #497. Please review the pull request and the test snapshots I added.
