### ISSUE TITLE
Java equals and hashcode breaks compilation

### ISSUE THREAD

**Issue by ThanksForAllTheFish** [asyncapi/modelina#510]
When generating a java model including equals and hashcode settings, the resulting files break compilation.

The reason is that equals is generated using `Objects.equals` util method, but the relative `import java.util.Objects` is omitted.

Sample repo: https://github.com/ThanksForAllTheFish/modelinabug

How to reproduce once cloned:

- `npm ci`
- `npm run generate`
- check files in `java/org/t4atf/asyncapi`, equals and hashcode are properly implemented, but the import is missing

Verified against latest modelina npm package (0.39.4)

**Comment by jonaslagoni** [comment]
@all-contributors please add @ThanksForAllTheFish for bug
