### ISSUE TITLE
please add python 

### ISSUE THREAD

**Issue by yangs0459** [asyncapi/modelina#514]
#### Reason/Context
Please try answering few of those questions
- Why we need this improvement?
- How will this change help?
- What is the motivation? 

#### Description
Please try answering few of those questions
- What changes have to be introduced?
- Will this be a breaking change?
- How could it be implemented/designed?

**Comment by magicmatatjahu** [comment]
Duplicated https://github.com/asyncapi/modelina/issues/49 :)
