### ISSUE TITLE
Java generation - support for 'format' classifier

### ISSUE THREAD

**Issue by reuben-tonna-ixaris** [asyncapi/modelina#533]
In the specification when I define my schema I can define a format e.g. datetime, email, etc.

At the moment when I generate with modelina java DTOs properties having a format defines are given a type of "Object".

Having the generated code support the api specified constraints (string = email, or string is to be interpreted as a date) is important for correctness and consistency of how an API is used.

Below is an example illustrating such an issue with date format.

![image](https://user-images.githubusercontent.com/85121176/146532868-4a188e6d-a0d6-4698-b9cb-fd52470e0dd1.png)

**Comment by jonaslagoni** [comment]
As mentioned in https://github.com/asyncapi/modelina/issues/534, the java generator actually supports semi formats (not all).

Gonna leave this issue open until we get a better handle on which formats are allowed and how they should be represented.

**Comment by 200Puls** [comment]
I actually encountered this issue today with the example schema that uses the 'email' format.

I guess it would be most useful to use the type if no special handling for the format is found.
So that java.lang.String would be used for type= string, format=email.

**Comment by 200Puls** [comment]
I've tried a quick fix in #1019.
