### ISSUE TITLE
Java DTO generation for strict formats is assigning type 'Object' instead of expected type 'String'

### ISSUE THREAD

**Issue by reuben-tonna-ixaris** [asyncapi/modelina#534]
Short term at least get the type to reprot as String (as happens for other languages - this is the bug referred to here). Longer term support for strict formats is highly desirable especially for types like dates - this is the enhancement referred to by https://github.com/asyncapi/modelina/issues/533.

Sample yaml:

asyncapi: 2.2.0
info:
  title: Example
  version: 0.1.0

servers:
  production:
    url: broker.mycompany.com
    protocol: kafka
    description: This is "My Company" broker.
  qa:
    url: broker.mycompany.com
    protocol: kafka
    description: This is "My Company" broker.
  dev:
    url: broker.mycompany.com
    protocol: kafka
    description: This is "My Company" broker.

channels:
  user/signedup:
    publish:
      summary: "Say hello"
      operationId: "onSayHello"
      message:
        $ref: '#/components/messages/hello-msg'

components:
  messages:
    hello-msg:

      name: "SayHello"
      title: "Say hello"
      description: "Message received when a hello event is raised"
      contentType: "application/json"

      tags:
        - name: "hi"
        - name: "hallo"
        - name: "hola"

      headers:
        type: "object"
        properties:
          correlationId:
            description: "Correlation id set by the application"
            type: string
          applicationInstanceId:
            description: "Unique identifier for a given instance of the publishing application"
            type: string

      payload:
        type: object
        $id: "SayHello"
        additionalProperties: false
        properties:
          name:
            type: string
          sentAt:
            $ref: '#/components/schemas/sent-at'

      correlationId:
        description: "Default correlation id"
        location: "$message.header#/correlationId"

      examples:
        - name: "SimpleSignup"
          summary: "A simple signup example message"
          headers:
            correlationId: "my-correlation-id"
            applicationInstanceId: "my-instance-id"
          payload:
            name: "Joe Borg"
            sentAt: "2020-12-17T09:00:00.000"

  schemas:
    sent-at:
      type: string
      description: The date and time a message was sent.
      format: datetime

Observed result:

![image](https://user-images.githubusercontent.com/85121176/146533412-41a15988-35f3-4b46-a5e5-a79adb157650.png)

**Comment by jonaslagoni** [comment]
@reuben-tonna-ixaris for the java generator, it is actually already supported. The only problem you are phasing is that you are using the format `datetime`, when it should be [date-time](https://json-schema.org/understanding-json-schema/reference/string.html#dates-and-times).

With this change, it generates the type `java.time.OffsetDateTime`. It reason it generates `Object` is that it is our backup type in case it [encounters unrecognized types](https://github.com/asyncapi/modelina/blob/593a6e83740827444d7e72746a8feec8a82f3a78/src/generators/java/JavaRenderer.ts#L123).

Gonna close this issue down, feel free to reopen if it is still not solved 🙂
