### ISSUE TITLE
Non-required properties are required by constructor

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#538]
#### Describe the bug
The JavaScript generator creates constructors that requires non-required properties.

#### How to Reproduce
Given the following input: 

```js
{
      $id: 'TestObj',
      type: 'object',
      properties: {
        requiredProp: { type: 'string' },
        optionalProp: { type: 'string' },
      },
      required: ['requiredProp'],
}
```

It generates:

```js
class TestObj {
  streetName;
  city;

  constructor(input) {
    this.requiredProp = input.requiredProp;
    this.optionalProp = input.optionalProp;
  }

  get requiredProp() { return this.requiredProp; }
  set requiredProp(requiredProp) { this.requiredProp = requiredProp; }

  get optionalProp() { return this.optionalProp; }
  set optionalProp(optionalProp) { this.optionalProp = optionalProp; }
}
```

#### Expected behavior
Only expected the constructor to be:

```js
  constructor(input) {
    this.requiredProp = input.requiredProp;
  }
```

This is because the [JavaScript class render](https://github.com/asyncapi/modelina/blob/593a6e83740827444d7e72746a8feec8a82f3a78/src/generators/javascript/renderers/ClassRenderer.ts) creates the parameters based on all properties instead of only the required properties, see:

https://github.com/asyncapi/modelina/blob/593a6e83740827444d7e72746a8feec8a82f3a78/src/generators/javascript/renderers/ClassRenderer.ts#L74

To solve this, filter out any properties which are not required `model.isRequired(propertytName)`.

**Comment by Devansh-kajve** [comment]
Hey there @jonaslagoni👋 can I resolve this one? I understand the issue but can you please elaborate on how to filter out the unrequired properties. it's also my first time dealing with a typescript file

**Comment by jonaslagoni** [comment]
> Hey there @jonaslagoni👋 can I resolve this one? I understand the issue but can you please elaborate on how to filter out the unrequired properties. it's also my first time dealing with a typescript file

Of course! 

You can use something called a filter funktion before calling the `map()` function.  

Some people like to not get the entire answer and work it out themselves, if my answers is not sufficient, just let me know 🙂
