### ISSUE TITLE
Allow customizing of type mappings in renderers

### ISSUE THREAD

**Issue by kamko** [asyncapi/modelina#546]
#### Reason/Context
Currently when there is `number` or `double` defined in the spec we convert it to `java.lang.Double`. 
This looks correct but frequently it's needed to convert these float types to `java.math.BigDecimal` (e.g. monetary API). Also, there could be more cases where you want to have a custom type in place of a predefined one.

#### Description
This mapping is being done here:
https://github.com/asyncapi/modelina/blob/593a6e83740827444d7e72746a8feec8a82f3a78/src/generators/java/JavaRenderer.ts#L100-L102

This could be done by adding support for custom formats aka direct A -> B mapping. 
For example by adding some `format -> javaType` map to renderer options ([e.g. mapping in swagger-codegen](https://github.com/swagger-api/swagger-codegen/issues/5587#issuecomment-368805748))

Also not instantiating the renderers in place and having the possibility to inject them could also help customization in the future.
https://github.com/asyncapi/modelina/blob/master/src/generators/java/JavaGenerator.ts#L78-L83

-- 
If I'm right to work around this currently would require to duplicate `JAVA_DEFAULT_CLASS_PRESET`.

**Comment by jonaslagoni** [comment]
I really like this, definitely something we should look into. And it is something all languages can benefit from. 

I think what makes the most sense is to right before rendering the type, check any provided mapping, whether the rendered type should be mapped to something different. This gives the most power to the user I think 🤔 

i.e. for Java, we provide the mapping as:
```json
{"mapping": {"double" : "java.math.BigDecimal"}}
```

An immediate problem I see us running into, is if a custom type requires a dependency, not all languages have the fortune to define it in the type such as `java.math.BigDecimal` but would require to actually import it. For example in TS, we would probably have to support something like this: 
```json
{"mapping": {"double" : {"type": "MyCustomType", "dependency": "import MyCustomType from '../custom/path/MyCustomType';"}}}
```
For the Java representation we could do:
```json
{"mapping": {"double" : {"type": "BigDecimal", "dependency": "import java.math.BigDecimal;"}}
```

> Also not instantiating the renderers in place and having the possibility to inject them could also help customization in the future.
> https://github.com/asyncapi/modelina/blob/master/src/generators/java/JavaGenerator.ts#L78-L83

@kamko do you think we should do this mapping through custom renders rather then options? 🤔

**Comment by kamko** [comment]
I'm happy that you like the idea :).

The proposed mapping configuration looks fine as long as the dependency will be optional (for example in Java I would like to have full class names instead of imports). 

Currently, the type mapping is part of the parent rendered (at least for java) so I think the options should be passed to the renderer and that should be responsible for all the required steps for getting a type for some schema property:

1. check if a dependency is needed for this mapping
2. add dependency if not already present
3. return the correct type

This way it will be transparent for all the presets. The mapping could be part of the generator options and then forwarded to the renderer.

Regarding the custom renderers, I just meant that having the possibility to override only renderers without changing generator implementation could be useful. For example by providing the factory method as an input parameter to the generator or something like that. As for example to implement this without changes in library my first thought was to extend JavaRenderer and reimplement only the `toJavaType` method but that wouldn't help me without also changing generator.

My current solution is to duplicate default preset and enhance it with options (btw why isn't it possible to provide som extra options to default preset? :D I had to remove default and add it as first one in the array)

**Comment by kamko** [comment]
@jonaslagoni what is your opinion here?

**Comment by jonaslagoni** [comment]
Inheritance of a custom rendering would definitely also be an option 🤔 

Right now, I am reengineering the [new core data model](https://github.com/asyncapi/modelina/pull/530), which means the renderer will not be the one determining the type anymore. The constrained data model will have already constrained to a language, [so all you need to do is](https://github.com/jonaslagoni/generator-model-sdk/blob/feature/prepare_for_new_internal_model/docs/Internal%20language.md#the-constrained-data-model) `model.type`. 

In order to provide the most freedom, I think we should focus on the options. As the user doesn't need to know the underlying implementation (i.e. there exists a renderer that needs to be overwritten), they just need to know the interface.

> The proposed mapping configuration looks fine as long as the dependency will be optional (for example in Java I would like to have full class names instead of imports).

For sure 👍

**Comment by jonaslagoni** [comment]
@kamko I wanted to get your perspective on a solution that soon will live in `next`. With the upcoming change you would be able to define the custom mapping as such: 

```
const generator = new TypeScriptGenerator({
  constraints: {
    typeMapping: {
      Number: ({renderer, model}) => {
        return 'integer';
      }
    }
  }
});
```

Where `Number` is one of the core model types. Through this, you can easily add dependencies and conditional type rendering based on the model that is being generated. 

For your Java project you can then easily do:

```
const generator = new JavaGenerator({
  constraints: {
    typeMapping: {
      Number: ({renderer, model}) => {
        return 'java.math.BigDecimal';
      }
    }
  }
});
```
Would that suit your needs?

**Comment by kamko** [comment]
That looks good! - it fits the original issue I had.

The `Number` is a set of fixed types or it will be for formats also (e.g. type: string, format: UUID)? 

Would it be possible to also pass the "property/field" (don't know the naming) that is currently being mapped to the method?

My thinking is that I would like to have custom mappings based on some additional data linked to specific property.

**Comment by jonaslagoni** [comment]
> The `Number` is a set of fixed types or it will be also for formats (e.g. type: string, format: UUID)?

`Number` is one of the [core abstracted type](https://github.com/asyncapi/modelina/blob/next/docs/processing.md#the-meta-model), where formats, in the long run, would form something like `sub types` within them. At least that is the idea, but not a focus at the moment.

> Would it be possible to also pass the "property/field" (don't know the naming) that is currently being mapped to the method?

I am looking into that yes, as part of the `context` parameter, which the `renderer` is part of.

**Comment by jonaslagoni** [comment]
Solved in the `next` branch, see https://github.com/asyncapi/modelina/blob/next/examples/change-type-mapping/index.ts

**Comment by gabormagyar** [comment]
@jonaslagoni

I don't see the renderer param in the `TypeMappingFunction` interface. I would like to add dependencies as you showed above:

```ts
Number: ({renderer}) => {
        renderer.addDependency('import java.math.BigDecimal;'); ...
```

Is this still planned?

**Comment by jonaslagoni** [comment]
Damn... I removed it last minute from the PR because I could not recall why it was needed, as all I saw in the current generators was the access to options. So the extra functionality for them to access the renderer would be in vain. Forgot about this one!

Should definitely be fixed, adding another issue.
