### ISSUE TITLE
Including a `.nvmrc` file for the project

### ISSUE THREAD

**Issue by ron-debajyoti** [asyncapi/modelina#575]
#### Questions

- Why we need this improvement?
Since, this project specifies the node version to be >= 14

- How will this change help?
 Some developers like me use different versions of node for different projects, hence having a `.nvmrc` file would automatically be helpful in preventing human errors :smile: .  If this file exists, we just have to load the specified version using it. 

#### Description
- What changes have to be introduced?
We just need to add a `.nvmrc` file in the root directory.

- Will this be a breaking change?
 No, It's just a specification file.

- How could it be implemented/designed?
 By running the command : `node -v > .nvmrc `

**Comment by ritik307** [comment]
Hi @ron-debajyoti Kindly assign me the issue I would like to work on this

**Comment by jonaslagoni** [comment]
I have never had any problems or had the use for the file. However, I can see the benefits in having it 🙂 

So go ahead and create a pull request, make sure to update any relevant documentation :)

**Comment by ron-debajyoti** [comment]
>  have never had any problems or had the use for the file.

I actually don't have node v14 set as default. So, every time I run locally, I either had to manually change the node version or just make nvm do the work, hence the suggestion.
