### ISSUE TITLE
Assign optional/non required arguments in the constructor if provided

### ISSUE THREAD

**Issue by mahakporwal02** [asyncapi/modelina#581]
#### Reason/Context
- We can add an enhancement to javascript generator to assign optional/non required arguments in the constructor during object formation.
- Constructor accept arguments and set it to required member variables. But currently it only set values for only required arguments.
- For example:
If email is non required property - 
```
const jsonSchemaDraft7 = {
  $schema: 'http://json-schema.org/draft-07/schema#',
  type: 'object',
  additionalProperties: false,
  properties: {
    email: {
      type: 'string',
      format: 'email'
    }
  }
}
```
The model generated would be - 
```
class Root {
  email;
  constructor(input) {
  }
  get email() { return this.email; }
  set email(email) { this.email = email; }
}
```
After adding the enhancement the model generated would be -
```
class Root {
  email;
  constructor(input) {
  	if (input.hasOwnProperty(email)) {
  		this.email = input.email;
  	}
  }
  get email() { return this.email; }
  set email(email) { this.email = email; }
}
```

**Comment by ritik307** [comment]
@derberg @fmvilas @mahakporwal02 I would like to work on this issue

**Comment by mahakporwal02** [comment]
@ritik307 Apologies, didn't see your comment until now.
