### ISSUE TITLE
Add JSON Schemas for available options in languages

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/modelina#595]
Currently, we have a serious problem with reusing options (or rather available values etc) for languages in other projects. Of course, if one uses a library in a TS project then has a typing that validates the passed options. The problem arises in the case when we want to validate these options in runtime and not at development time, e.g. in our `cli` (related PR and comment https://github.com/asyncapi/cli/pull/173#issuecomment-1018612209), `server-api` or `studio` we have a problem because we don't currently provide this possibility. I think we should create JSON Scheme for each language and then we can reuse this json scheme in other projects.

So some benefits:
- we will have on source of truth that we can consume in other projects
- thanks to automatic bumping we won't have to edit options in other repos (they will consume them from JSON Schemas)
- in cli we'll be able to validate parameters, in server-api also and we'll be able to create forms based on JSON Schemas in the studio :)

**Comment by jonaslagoni** [comment]
Hmm, maybe that is possible yea :thinking:

That way I could reuse it in the website as well. Let me see what I can do.

**Comment by magicmatatjahu** [comment]
@jonaslagoni In the future we should switch the playground in the website to the Studio, but it's a idea to update "forms" in the `modelina` repo and reuse that in other projects.

**Comment by jonaslagoni** [comment]
Tbh, I feel like modelina together with docs, playground examples and use-cases need its own website at some point, time is just not right just yet 😛 Of course if you want studio to integrate modelina as well, go for it 😆

**Comment by magicmatatjahu** [comment]
@jonaslagoni Do you mean that problems related to reference using `$id`?

**Comment by jonaslagoni** [comment]
That and references are not looked up by tooling under `definitions`, meaning it will be difficult to have separate schemas and bundle them together.

And the idea was to generate the option types through Modelina itself from the schema files so we use them as a single source of truth. Both for CLI, playground, and generator arguments.

I did a quick test here:
- [JSON Schema options](https://github.com/jonaslagoni/generator-model-sdk/tree/feature/options-json/options/definitions)
- [Bundling the definitions together](https://github.com/jonaslagoni/generator-model-sdk/tree/feature/options-json/tools/bundler) to form the [complete schema](https://github.com/jonaslagoni/generator-model-sdk/tree/feature/options-json/options) 
- [Using that complete schema to generate the types](https://github.com/jonaslagoni/generator-model-sdk/tree/feature/options-json/tools/typegenerator). 

I.e. currently https://github.com/asyncapi/modelina/issues/608 blocks the progress.

I tried to do some manual changing of the complete schema, and I can get it to work: https://github.com/jonaslagoni/generator-model-sdk/tree/feature/options-json/tools/typegenerator/output, but then I ran into https://github.com/asyncapi/modelina/issues/610 😆

**Comment by jonaslagoni** [comment]
Of course, we could skip the type generation for now, but then I feel like it won't be worth the problems. So I know know 😄
