### ISSUE TITLE
Can you add a support for PHP documentation generator?

### ISSUE THREAD

**Issue by albalakg** [asyncapi/modelina#598]
#### Reason/Context
- There are a lot of websites based on PHP that wants to use it
- Could help us develop the documentation on the fly and save us time

thanks

**Comment by jonaslagoni** [comment]
@albalakg do you mind giving us an example of what exactly you would like to have generated? 🙂

**Comment by jonaslagoni** [comment]
Closing down, cause of no further clarification.
