### ISSUE TITLE
Immutable java objects

### ISSUE THREAD

**Issue by scarlier** [asyncapi/modelina#607]
#### Reason/Context
Please try answering few of those questions
- Why we need this improvement?
thread-safe java objects

#### Description
Please try answering few of those questions
- What changes have to be introduced?
java code generator needs to generate immutable objects

- Will this be a breaking change?
no

- How could it be implemented/designed?
a. an preset that will use a builder pattern instead of setters
b. an preset that will only generate properties with an lombok builder annotation

**Comment by ritik307** [comment]
@scarlier I would like to work on this
