### ISSUE TITLE
Exclude `_` from TypeScript key enum rendering

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#609]
#### Reason/Context
Given an enum key such as `something_something` the enum renderer creates the following key `SOMETHING_UNDERSCORE_SOMETHING` even when TS fully supports `SOMETHING_SOMETHING`

#### Description

We need to add `_` to the exclusion list here: https://github.com/asyncapi/modelina/blob/71ac65a5aafd44731f7d421aec88c2ccfbfc2cad/src/generators/typescript/renderers/EnumRenderer.ts#L53

**Comment by RishiKumarRay** [comment]
we have to add exclude[ ' _ ' ] ???

**Comment by jonaslagoni** [comment]
> we have to add exclude[ ' _ ' ] ???

Yes, excluding that we don't have to replace `_` with `underscore`, as it is perfectly fine to have among the key for an enum 🙂

**Comment by Ishan-Saini** [comment]
I'd like to work on this!

**Comment by jonaslagoni** [comment]
@all-contributors please add @Ishan-Saini for code and test
