### ISSUE TITLE
[📑 Docs]:  Update JavaScript.md with un/marshal function

### ISSUE THREAD

**Issue by Samridhi-98** [asyncapi/modelina#625]
### What Dev Docs changes are you proposing?

**Description**
To let the user know that `un/marshal feature` of `javascript` is now available to use.

- [ ] Upate `docs/languages/JavaScript.md`.
- [ ] Add examples for this feature in example folder.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Samridhi-98** [comment]
@jonaslagoni  If you approve of this issue, I would like to work on this issue.

**Comment by jonaslagoni** [comment]
Don't need to approve anything, solid suggestion 👍
