### ISSUE TITLE
Utilising shorthands for accessors in CSHARP_DEFAULT_CLASS_PRESET

### ISSUE THREAD

**Issue by slowikowskiarkadiusz** [asyncapi/modelina#670]
#### Reason/Context
Currently, each property is generated like this
```
private Type field;

public Type Field
{
    get { return field; }
    set { field = value; }
}
```
which generates 6 times more code than it's necessary. C# allows for such a shorthand:
```
public Type Field { get; set; }
```
Way less code, the result the same

#### Description
I don't think it's a breaking change. Generated data models will be able to be used the same way they currently are.
The resolution for it would include modifying the `src/generators/csharp/renderers/ClassRenderer.ts` file and more specifically the implementation of CSHARP_DEFAULT_CLASS_PRESET. If anybody would ever want to use the more complex way of declaring properties, they would still be able to do it by implementing their own CsharpClassPreset, but I don't see a reason to make it default.

**Comment by slowikowskiarkadiusz** [comment]
I've made a PR for this now

**Comment by jonaslagoni** [comment]
With the shorthand notation, is it still possible to completely overwrite the setter implementation? Say you want to add some validation rules to what is allowed to be set as values, will it still support something like this:
```
    set { if(value === 'test') {field = value;} else {throw new Exception} }
```

**Comment by slowikowskiarkadiusz** [comment]
> With the shorthand notation, is it still possible to completely overwrite the setter implementation? Say you want to add some validation rules to what is allowed to be set as values, will it still support something like this (just example):
> 
> ```
>     set { if(value == 'test') {field = value;} else {throw new Exception} }
> ```

Unfortunately it wouldn't be possible. For some reason if you want to include any logic in the getter or in the setter, you have to declare a separate field on which you're going to operate (so pretty much use the current way of generating properties). It happens rather rarely so I think it makes sense to not make it default
 
> > If anybody would ever want to use the more complex way of declaring properties, they would still be able to do it by implementing their own CsharpClassPreset, but I don't see a reason to make it default.
> 
> Or is this what you mean?

Yes
