### ISSUE TITLE
should render additionalProperties 

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#68]
#### Reason/Context
Currently the `CommonModel` does include additionalProperties, however they are not rendered as properties in the generator 

Questions:
- How should we handle `additionalProperties` if we already have a property called `additionalProperties`?

**Comment by magicmatatjahu** [comment]
@jonaslagoni You pinged me about problems with `addProperties` etc in slack, so I give you some tips here, also to check by another people from community:

For `additionalProperties`:
- in TS and JS we should render for additionalProperties additional accessor for set and get, but not native, but something like `getAdditionalProperty(key: string): {type}` and `setAdditionalProperty(key: string, value: {type}): void`.
- in Java we can make something similar `public {type} getAddtionalProperty(String key) { this.additionalProperties.get(key) }` and similar `setAdditionalProperty`.

For `patternProperties` situation is very similar to `additionalProperties`. We have an example:

```ts
{
  "type": "object",
  "patternProperties": {
    "^S_": { "type": "string" },
    "^I_": { "type": "integer" }
  },
  "additionalProperties": false
}
```

- in TS and JS we should render:

```ts
patternProperties: Record<string, any>;

getPatternProperty(key: string): {type | undefined} {
  return patternProperties[key];
}

setPatternProperty(key: string, value: any): void {
  // here we must check patterns
  if (/^S_/.test(key) && typeof value === "string") {
    this.patternProperties[key] = value;
  }
  if (/^I_/.test(key) && typeof value === "number") {
    this.patternProperties[key] = value;
  }
  // maybe throw error
}
```

- for Java very similar like for TS - additional get and set for patternProperties and inside them check pattern before saving data.

`additionalProperties` and `patternProperties` you can render in 2 ways:
- using `additionalContent` preset for class [here](https://github.com/asyncapi/generator-model-sdk/blob/master/src/generators/typescript/renderers/ClassRenderer.ts#L79) or
- adjust `renderProperties` in appropriate renderer
