### ISSUE TITLE
Preset options are not typed

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#681]
#### Reason/Context
How the generic system works currently for presets results in options being forced to `any`. Each language has its own generic setup but should be pretty quick to change. Each preset should already have the options defined, just never used.

For example for TS we need to change [TypeScriptPreset](https://github.com/asyncapi/modelina/blob/master/src/generators/typescript/TypeScriptPreset.ts) to:
```ts
export type TypePreset<R extends TypeRenderer = TypeRenderer, O extends object = any> = CommonPreset<R, O>

export type TypeScriptPreset<O extends object = any> = Preset<{
  class: ClassPreset<ClassRenderer, O>;
  interface: InterfacePreset<InterfaceRenderer, O>;
  enum: EnumPreset<EnumRenderer, O>;
  type: TypePreset<TypeRenderer, O>;
}>;

export const TS_DEFAULT_PRESET: TypeScriptPreset = {
  class: TS_DEFAULT_CLASS_PRESET,
  interface: TS_DEFAULT_INTERFACE_PRESET,
  enum: TS_DEFAULT_ENUM_PRESET,
  type: TS_DEFAULT_TYPE_PRESET,
};

```
That way we can change [each preset to](https://github.com/asyncapi/modelina/blob/4e3604828c92c8951731e0fe569887b1162cbaf1/src/generators/typescript/presets/CommonPreset.ts#L195):

```ts
...
export const TS_COMMON_PRESET: TypeScriptPreset<TypeScriptCommonPresetOptions> = {
...
```

Don't adapt all the generators in 1 PR, but split it up to be more manageable, something like 1 for each generator should make sense.

Checklist for completion:

- [x] #702
- [x] #707
- [x] #708
- [x] #710
- [x] #711

**Comment by Samridhi-98** [comment]
Hey, @jonaslagoni I would like to work on the TypeScript Generator for this issue 🙂

Also, should we convert the above checklist into multiple issues or simply link the PR with this one?

**Comment by jonaslagoni** [comment]
> Hey, @jonaslagoni I would like to work on the TypeScript Generator for this issue 🙂
> 
> Also, should we convert the above checklist into multiple issues or simply link the PR with this one?

🎉 

Up to you @Samridhi-98, however, you feel like doing it 🙂

**Comment by jonaslagoni** [comment]
Awesome @Samridhi-98!
