### ISSUE TITLE
Python 

### ISSUE THREAD

**Issue by aazammazaa** [asyncapi/modelina#685]
#### Python with FastAPI or Django
Please try answering few of those questions
- Why we need this improvement?
- Python is also an popular in ML and AI and RL training in real life example easier 
- How will this change help?
- help lots of iot doers
- What is the motivation?
- MQTT 

#### Description
Please try answering few of those questions
- What changes have to be introduced?
- Will this be a breaking change?
- How could it be implemented/designed?

**Comment by jonaslagoni** [comment]
Related to https://github.com/asyncapi/modelina/issues/49 and already underway in https://github.com/asyncapi/modelina/pull/604
