### ISSUE TITLE
[C#] Generated JsonSerializer does not compile with .NET 6

### ISSUE THREAD

**Issue by Polygens** [asyncapi/modelina#701]
#### Describe the bug
Code does not compile when generated using the C# code generation with `CSHARP_JSON_SERIALIZER_PRESET`

```
The call is ambiguous between the following methods or properties: 'JsonSerializer.Serialize<TValue>(TValue, JsonSerializerOptions?)' and 'JsonSerializer.Serialize<TValue>(TValue, JsonTypeInfo<TValue>)' [HAModels-DotNet]csharp(CS0121)
```

#### How to Reproduce
The issue is a known breaking change in .NET 6 further explained here: https://docs.microsoft.com/en-us/dotnet/core/compatibility/serialization/6.0/jsonserializer-source-generator-overloads

#### Expected behavior
Generated code can compile. Now I'm manually adding `, (JsonSerializerOptions)null` to the following line: https://github.com/asyncapi/modelina/blob/51062c1d74e6bf0514619510e0e6f413d73bf4e3/src/generators/csharp/presets/JsonSerializerPreset.ts#L119

**Comment by jonaslagoni** [comment]
@Polygens do you mind creating a PR fixing this? 

> Generated code can compile. Now I'm manually adding , (JsonSerializerOptions)null to the following line: 

I am assuming this is backward compatible with older versions?

**Comment by jonaslagoni** [comment]
> Does Modelina target a specific version of .NET actually? I could not find it in the docs

My hope is we can avoid introducing multiple generators for specific versions. We might be forced to do this through some kind of option for the generator. Have yet to encounter the advanced use-case for it that require a solution, but I bet it will come soon 😅
