### ISSUE TITLE
Java Template: json schema union is generated as object

### ISSUE THREAD

**Issue by RobinGoussey** [asyncapi/modelina#749]
#### Describe the bug
In our schema, we have multiple types, that are nullable types, like a string.
Eg.
```
          username:
            type: [ "string", "null" ]
            description: The username of the user that sent this message
```
What we expected would happen:
  private String username;

What we got
  private Object username;

#### How to Reproduce
We generate our file like this:

```java
const generator = new JavaFileGenerator({
  collectionType: 'List',
  presets: [
    {
      preset: JAVA_COMMON_PRESET,
      options: {
        equals: true,
        hashCode: true,
        classToString: true,
      },
    },
    JAVA_CONSTRAINTS_PRESET,
    JAVA_JACKSON_PRESET,
    JAVA_DESCRIPTION_PRESET,
  ],
});

(async () => {
  const asyncDoc = readFileSync(schemaFile, 'utf8');
    const parsedDoc = await parser.parse(asyncDoc);
  await generator.generateToFiles(parsedDoc, outDirectory, {
    packageName: rootPackage,
  });


  //Temp fix:
  /*
   * We replace the union of nulls, with just the object, because currently the code generation turns it into objects, instead of string or boolean etc.
   */
  //const parsedDoc = await parser.parse(
  //  asyncDoc.replace(/\[(?: ?null" ?,)? ?("\w+")(?: ?, ?"null")? ?]/g, '$1')
  //);
  //await generator.generateToFiles(parsedDoc, outDirectory, {
  //  packageName: rootPackage,
  //});
})();
```

#### Expected behavior
Making a string nullable, should leave it as a java String, instead of turning it into an object.

**Comment by magicmatatjahu** [comment]
@RobinGoussey Hello! Do you wanna create fix for that? It should be fixed here in this place https://github.com/asyncapi/modelina/blob/master/src/generators/java/JavaRenderer.ts#L56

**Comment by RobinGoussey** [comment]
@jonaslagoni
The behaviour of 
```
            type: [ "string", "integer", "null" ]

```
should not have changed, and will thus be an object[]. Which is the behavior it had before. As in test test('Should render mismatching tuple types as Object', () => { in JavaRenderer.spec.ts

**Comment by jonaslagoni** [comment]
> should not have changed, and is still object[]. Which is the behavior it had before. As in test test('Should render mismatching tuple types as Object', () => { in JavaRenderer.spec.ts

I know, I just want to make sure [that the upcoming change](https://github.com/asyncapi/modelina/tree/next) will work as "expected". So just want to dig a bit deeper 🙂

**Comment by RobinGoussey** [comment]
I have no clue on what will happen if the upcoming changes, and my PR come together. I hadn't really considered the uniion of 2 types + nullable. As I think currently in Java, all types are nullable.

So maybe I need to rework, but how do I best do this then? Do I create merge your branch into mine, and create a PR to your branch?

**Comment by jonaslagoni** [comment]
> So maybe I need to rework, but how do I best do this then? Do I create merge your branch into mine, and create a PR to your branch?

You don't have to worry about the next branch, ill make sure to adapt it appropriately 🙂 I will take a look at the PR later today or tomorrow 👍

**Comment by jonaslagoni** [comment]
Still relevant.
