### ISSUE TITLE
Cannot be used for browsers 

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#757]
#### Describe the bug
The website cannot use the newest version of modelina, because of the dependency `typescript-json-schema` as it uses `ts-node` which out of the box is not compatible with CommonJS.

#### Expected steps to solve

Might be as easy as:
1. Add a specific website example we can use as test to ensure it always works going forward.
2. My assumption is that we can add a configuration to the tsconfig.json file to solve this: https://github.com/TypeStrong/ts-node/issues/935#issuecomment-913179458

**Comment by derberg** [comment]
hint for the test:
- we do it already in parser -> https://github.com/asyncapi/parser-js/blob/master/test/browser_test.js
- puppeteer is the key, but I've heard Microsoft has alternative project that gets some attention, so maybe you wanna use it
- simple HTML https://github.com/asyncapi/parser-js/blob/master/test/sample_browser/index.html
- and then just npm script that starts the server before starting test -> https://github.com/asyncapi/parser-js/blob/master/package.json#L22 using `start-server-and-test` package

not expert in TS, but yeah, if simple config won't work, you can always switch to parser approach where we bundle browser compatible version of the parser

**Comment by jonaslagoni** [comment]
Solved in https://github.com/asyncapi/modelina/pull/843
