### ISSUE TITLE
Schema dependencies should be iterated

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#79]
#### Reason/Context
Currently we do not iterate schema dependencies. We should iterate them and combine properties/items/types etc together.

```json
{
  "type": "object",
  "properties": {
    "name": { "type": "string" },
    "credit_card": { "type": "number" }
  },
  "required": ["name"],
  "dependencies": {
    "credit_card": {
      "properties": {
        "billing_address": { "type": "string" }
      },
      "required": ["billing_address"]
    }
  }
}
```

should merge it together to give the model:

```
{
  "type": "object",
  "properties": {
    "name": { "type": "string" },
    "credit_card": { "type": "number" },
    "billing_address": { "type": "string" }
  },
  "required": ["name"]
}
```
Reason why `billing_address` is not added to the list of required properties, is that it is a runtime requirement that we cannot do anything about when rendering the model.

see more here: http://json-schema.org/understanding-json-schema/reference/object.html#schema-dependencies

**Comment by magicmatatjahu** [comment]
@jonaslagoni Please have in mind that final schema is only valid, when you have defined `credit_card` - like in example in linked web, so I think that there we have an union type with given schema:

```js
{
  oneOf: [
    {
      "type": "object",
      "properties": {
        "name": { "type": "string" },
        "credit_card": { "type": "number" },
        "billing_address": { "type": "string" }
      },
      "required": ["name", "credit_card", "billing_address"]
    },
    {
      "type": "object",
      "properties": {
        "name": { "type": "string" },
        "billing_address": { "type": "string" }
      },
      "required": ["name"]
    }
  ]
}
```

**Comment by jonaslagoni** [comment]
> @jonaslagoni Please have in mind that final schema is only valid, when you have defined `credit_card` - like in example in linked web, so I think that there we have an union type with given schema:

As we have another issue defining this problem, this union type will not be the focus in this.
