### ISSUE TITLE
PHP code generation support

### ISSUE THREAD

**Issue by marcinbos92** [asyncapi/modelina#830]
Hello,
I'm doing a short investigation about AsyncApi and PHP language support. In my current company I would like to introduce AsyncApi idea for developing and documenting async communication. Is it any way to generacje PHP classes, enums etc. from asyncApi json or yaml file? Or do you have any information about current work on it? If no, could I get some more information how to jump into the modelina and design/implement code generation to PHP?

Best regards,
Marcin

**Comment by jonaslagoni** [comment]
Hey @marcinbos92, until some official documentation is made, I suggest you take a look at this PR as it has all the right components to add a new generator: https://github.com/asyncapi/modelina/pull/818

Also make sure you target the `next` branch 🙂 

Let me know if you have any questions 👍

**Comment by jonaslagoni** [comment]
I have added an initial set of template for new generators and added documentation how to create new generators. Checkout https://github.com/asyncapi/modelina/pull/850

**Comment by jonaslagoni** [comment]
Duplicate issue of https://github.com/asyncapi/modelina/issues/744
