### ISSUE TITLE
RustGenerator Blackbox tests failing

### ISSUE THREAD

**Issue by leigh-johnson** [asyncapi/modelina#847]
#### Describe the bug
Couple of RestGenerator blackbox tests are failing in the `next` mainline branch. 

#### How to Reproduce
`npm run test:blackbox`

#### Expected behavior
Tests pass :stuck_out_tongue_closed_eyes: 

----

- [ ] `Error: Error: Command failed: cargo build /home/runner/work/modelina/modelina/test/blackbox/output/JsonSchemaDraft-4/traefik-v2/rust/struct` 
[link](https://github.com/asyncapi/modelina/runs/7707920632?check_suite_focus=true#step:9:257)
Should be `cargo build --manifest-path <test dir>`

- [ ] `TypeError: Cannot read property '0' of undefined`
[link](https://github.com/asyncapi/modelina/runs/7707920632?check_suite_focus=true#step:9:237)
Revisit the way enum member names are generated. The current implementation assumes a valid JSON draft 07 enum definition is passed and fails for all other inputs.

**Comment by leigh-johnson** [comment]
:wave: Just a head's up, I've blocked out time to address this issue November 14 - 18. Finally! Sorry for the long wait, I had a lot of pre-work to complete before moving PrintNanny.ai over to a NATS + AsyncAPI event stack.

**Comment by jonaslagoni** [comment]
AS this is a testing problem and does not affect anything other than the black-box tests, I think we can leave this out from the v1 milestone 🙂 It's just something that needs to be fixed at some point 😅

**Comment by AnimeshKumar923** [comment]
@jonaslagoni still valid?
