### ISSUE TITLE
Add a new example for JSON Schema draft 6

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#853]
#### Reason/Context
Currently, we only have an [example for JSON Schema draft 7](https://github.com/asyncapi/modelina/tree/master/examples/json-schema-draft7-from-object), I think it would make sense to add another one for draft 6. 

**Remember to create your branch from the `next` branch and NOT `master` and also target the PR towards `next`.**

#### Description
You can copy the draft 7 example folder, and rename it to `json-schema-draft6-from-object` and then apply the following changes:
- Change the [draft 7 schema to draft 6](https://github.com/asyncapi/modelina/blob/6c9c7039068e63f609e4b666fb8615998ac525d7/examples/json-schema-draft7-from-object/index.ts#L4):
```
const jsonSchemaDraft6 = {
  $schema: 'http://json-schema.org/draft-06/schema#',
  type: 'object',
  additionalProperties: false,
  properties: {
    email: {
      type: 'string',
      format: 'email'
    }
  }
};
```
- Adapt the package file: https://github.com/asyncapi/modelina/blob/25203c71bd55d6d8e84a8c9aa4672e5d3e857504/examples/json-schema-draft7-from-object/package.json#L2 with the new folder name
- Adapt the readme file https://github.com/asyncapi/modelina/blob/next/examples/json-schema-draft7-from-object/README.md
- Update the test snapshots `npm run test:examples -- -u`
- Add your example to the list of examples https://github.com/asyncapi/modelina/blob/next/examples/README.md
- Add your example to the usage docs: https://github.com/asyncapi/modelina/blob/next/docs/usage.md#generate-models-from-json-schema-documents. Do this by adding a new list item called `Generate from a JSON Schema draft 6 pure JS object`

Feel free to reach out if you have any questions 🙂

**Comment by jonaslagoni** [comment]
@derberg can we label this as hacktoberfest or is it too complex?

**Comment by derberg** [comment]
@jonaslagoni It is complex, but it is not hard, as the instructions are super good, and similar tasks were completed by others already too.

My advice -> add `hacktoberfest` label

**Comment by amit-ksh** [comment]
I want to work on this issue. Please assign this issue to me?

**Comment by jonaslagoni** [comment]
> I want to work on this issue. Please assign this issue to me?

@amit-ksh there are no assignments, you just pick it up and provide a PR with the changes 🙂 

Feel free to ping me if you have any questions 🙂
