### ISSUE TITLE
originalSchema for CommonModel should be called originalInput

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#86]
#### Reason/Context
The reason why we should make this change is that the input does not necessarily have be JSON Schema but could be something completely unrelated.

**Comment by magicmatatjahu** [comment]
@jonaslagoni Maybe we should have `originalInput` next to `originalSchema`? I mean, if we will have processor for graphql data from SDL to JSON Schema, then finally we must process JSON Schema not SDL, so `originalSchema` should stay.

**Comment by jonaslagoni** [comment]
Agreed in many cases if ever passed through the JSON Schema input processor it would stay `originalSchema`. 

However, if you provide another processor which does something completely different XML for example, it does not have to convert the XML into JSON for the JSON Schema input processor but can create the CommonModel representation itself. 

Then `originalSchema` would not make sense since it would now be `originalStructor` or what ever you could call it. Therefore a more neutral name such as `originalInput` makes more sense IMO.

**Comment by magicmatatjahu** [comment]
This is a one of POV, but here is also a question: why we want to processor xml in custom way, if we have possibility to change xml to json and then process it as JSON Schema? :)  `OriginalSchema`/`OriginalInput` should be also useful to read it from code, using pure GraphQL or XML you haven't this option.

**Comment by jonaslagoni** [comment]
XML is just an example, could by any type of input, with its own `InputProcessor` that does not use the JSON Schema simplifier. They could handle their own processing of transforming the input to CommonModels.
