### ISSUE TITLE
Adding AVSC support

### ISSUE THREAD

**Issue by tzahibena-simplex** [asyncapi/modelina#872]
#### Reason/Context
Hey!
My company is aiming to achieve an AsyncAPI document which is a single source of truth, for the Kafka messages schemas we produce.
For that we are looking to create an AsyncAPI converted to **AVRO** _avsc_ format, and then we will be able to send them to the Schema Registry as the most up to date schema.

#### Description
For this implementation we would need to create a new Avro converted similar to other converters which Modelina currently has.

I would like to hear your opinion on my company's use case and understand if you think this is correct.

**Comment by jonaslagoni** [comment]
just to clarify @tzahibena-simplex, you want to generate AVRO avsc format, i.e. writing to a `.avro` file in the end?
