### ISSUE TITLE
snake_case property becomes camelCase?

### ISSUE THREAD

**Issue by PanMan** [asyncapi/modelina#885]
#### Describe the bug
Hi! I have a property in my asyncApi doc, named `ts_human`
When I use Modelina to generate typescript types, this becomes `tsHuman`. Therefore I can't use the type to generate the JSON, which expects ts_human.

#### How to Reproduce
Steps to reproduce the issue. Attach all resources that can help us understand the issue:

* Include property with snake_case name
* Generated type is in camelCase

#### Expected behavior

I would expect my generated type to also be snake_case ? or am I missing something here?

**Comment by jonaslagoni** [comment]
Thanks for the issue @PanMan!

The reason for the naming formatting changes of properties is that we have to ensure that ANY string variant is compliant in TS. 

However, we are also quite aware that some cases are unique and you might need to customize this behavior. So you have two choices here.

1. You use the [marshaling preset](https://github.com/asyncapi/modelina/blob/next/examples/typescript-generate-marshalling/index.ts) so the models are accurately converted to JSON i.e. that the JSON property is no longer `tsHuman` but your desired `ts_human`, while still ensuring that all property names are compliant in TS.

2. You overwrite the [default naming behavior for properties](https://github.com/asyncapi/modelina/blob/73d16cc261bd8f8dcbc5dc201ae0df39b4eed40d/examples/overwrite-naming-formatting/index.ts#L6) and just let all property names be as-is:
```ts
const generator = new TypeScriptGenerator({
  constraints: {
    propertyKey: typeScriptDefaultModelNameConstraints({
      NAMING_FORMATTER: (name) => {
        return name;
      }
    })
  }
});
```

**Comment by jonaslagoni** [comment]
That is if you use the `^1.0.0-next.7` version of course!

**Comment by WhereJuly** [comment]
@jonaslagoni @PanMan just FYI

The above one was probably not actual anymore. The soluton working in Modelina v5.10.1.

```typescript
    const generator = new TypeScriptGenerator({
        modelType: 'interface', // my choice, not specific to the solution

        /**
         * There was solution advised to fix the snake case issue.
         * The solution is not working, at least in "@asyncapi/modelina": "^5.10.1"
         * @see https://github.com/asyncapi/modelina/issues/885
         * 
         * The working solution is below.
         */
        constraints: {
            propertyKey: (context: PropertyKeyContext<any>) => {
                return context.objectPropertyModel.propertyName;
            }
        }
    });
```

The whole script transforming input definitions into models as [the gist](https://gist.github.com/WhereJuly/1cadad5a60adf13caa0599655b63c26b) for convenience.
