### ISSUE TITLE
Document C# preset CSHARP_JSON_SERIALIZER_PRESET require Microsoft.CSharp dependency

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#915]
#### Describe the bug
When using the preset `CSHARP_JSON_SERIALIZER_PRESET` it requires (for additionalProperties) the dependency Microsoft.CSharp version 4.7 I believe.

This needs to be added to the list of dependencies for the preset here: https://github.com/asyncapi/modelina/blob/next/docs/languages/Csharp.md#using-native-systemtextjson

Remember to target the `next` branch for any changes.

Feel free to reach out if you need any clarifications, either here or on slack!

**Comment by sambhavgupta0705** [comment]
Hey @jonaslagoni ,in this issue we need to add  Microsoft.CSharp in the dependency?

**Comment by jonaslagoni** [comment]
@sambhavgupta0705 yes to the list of dependencies in the documentation for the feature, you can find it here: https://github.com/asyncapi/modelina/blob/master/docs/languages/Csharp.md#using-native-systemtextjson
