### ISSUE TITLE
C# generator does not render optional properties correctly

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#941]
#### Describe the bug
As seen in the following example, the C# generator does not render optional properties `string?` as it does on master:
https://github.com/asyncapi/modelina/blob/next/examples/csharp-generate-required-properties/__snapshots__/index.spec.ts.snap
https://github.com/asyncapi/modelina/blob/master/examples/csharp-generate-required-properties/__snapshots__/index.spec.ts.snap

**Comment by zaytsevand** [comment]
@jonaslagoni looks like this bug was fixed, but with a side-effect. I've added two examples to demonstrate erroneous output.
```csharp
  public class OrderCreate
  {
    public string? SampleCategory { get; set; } // <- optional autoproperties are fine
    public stringfalse OrderId { get; set; } // <- required are bugged
```

**Comment by zaytsevand** [comment]
Updated PR to fix the issue.
