### ISSUE TITLE
Add example to generate all models within the same file

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#949]
#### Reason/Context
In some situations, you dont want the models generated into separate files but rather everything within a single file.

Make sure that you base your changes on the `next` branch and also target the PR to that branch 🙂 

Extending the contributing documentation https://github.com/asyncapi/modelina/blob/next/docs/contributing.md#adding-examples
- Instead of using the default input type let's use one that creates multiple models for example something along the lines of:
```
{
  $schema: 'http://json-schema.org/draft-07/schema#',
  type: 'object',
  additionalProperties: false,
  properties: {
    email: {
      type: 'string',
      enum: ['example1@test.com', 'example2@test.com']
    }
  }
};
```
- For the code, join all the model-generated code together and potential imports:
```ts
import { promises as fsPromises } from 'fs';
import { join } from 'path';
...
  const outputFile = join(__dirname, './models.ts');
  const models = await generator.generate(jsonSchemaDraft7);
  const modelCode = models.map((outputModel) => {return outputModel.result });
  const imports = models.map((outputModel) => {return outputModel.dependencies});
  const uniqueImports = [... new Set(imports)];
  const codeWithImports = `${uniqueImports.join('\n')}
${modelCode.join('\n')}`;
  await fsPromises.writeFile(outputFile, codeWithImports);
  console.log(codeWithImports);
```
- The tests you can assert that a file has been written, don't care much about the content, as that can be tested by the spied logging. 
- In the end, add the example to the advanced use case: https://github.com/asyncapi/modelina/blob/next/docs/advanced.md#generate-each-model-in-the-same-file

If you have any questions let me know!

**Comment by amit-ksh** [comment]
I would like to work on this issue, assign this issue to me.

**Comment by anaysarkar7** [comment]
Hello @jonaslagoni 
I would like to work on this Issue!
If i have any doubts or get stuck,I'll msg on slack #how-to-contribute channel
