### ISSUE TITLE
Add Support for CPP language 

### ISSUE THREAD

**Issue by Willena** [asyncapi/modelina#953]
#### Reason/Context

I have JSON objects that are consumed/produced by Java and CPP (c++) programs. I would love to be able to generate the model for both of them with a single tool. 

 #### Description

Implement a CPP (c++) class generator

**Comment by jonaslagoni** [comment]
That would indeed be great to have!

We have described the process for adding new generators here: https://github.com/asyncapi/modelina/blob/next/docs/contributing.md#new-generators

Adding new generators is a bit of an endeavor, but we are here to support you on the journey 💪 

If anyone is willing to pick this up or has any questions feel free to reach out!

**Comment by anaysarkar7** [comment]
@jonaslagoni I would like to work on this issue. I will reach out incase i face any problem.

**Comment by anaysarkar7** [comment]
@jonaslagoni i am facing issues after adding the templates and replacing template with cpp , still there are some errors not going away

**Comment by jonaslagoni** [comment]
@anaysarkar7 just by saying there is errors does not provide any context, so its impossible for me to help you 😄 Can you create a draft PR with the changes?

**Comment by sambhavgupta0705** [comment]
hi @jonaslagoni can you please elaborate this issue a little.As in what we need to do in this one.

**Comment by jonaslagoni** [comment]
@sambhavgupta0705 we need to create a new generator, so we can support outputting the models to C++. 

You can find the guide how to add a generator here: https://github.com/asyncapi/modelina/blob/master/docs/contributing.md#adding-a-new-generator

Let me know if you have any questions 🙂

**Comment by sambhavgupta0705** [comment]
Thanks Jonas:)
