### ISSUE TITLE
Warning: Model did not have $id, ignoring into 2.5.0

### ISSUE THREAD

**Issue by mohamedelhabib** [asyncapi/modelina#954]
#### Describe the bug
I  am using asyncapi to generate java model based on an AsyncApi spec 2.5.0.
I am getting the following output but no code is generated.

```shell
 ›   Warning: Model did not have $id, ignoring.
Successfully generated the following models: 
```

#### How to Reproduce
This is an example to reproduce
```shell
asyncapi generate models java https://raw.githubusercontent.com/asyncapi/spec/master/examples/oneof.yml -o /tmp/java-test --packageName=com.test
```

Changing the version to 2.4.0 seems to fix the issue

```shell
curl -s https://raw.githubusercontent.com/asyncapi/spec/master/examples/oneof.yml | sed 's|2.5.0|2.4.0|g' > /tmp/oneof.2.4.0.yml && rm -fr /tmp/java-test/ && asyncapi generate models java /tmp/oneof.2.4.0.yml -o /tmp/java-test --packageName=com.test
```

#### Expected behavior

Java should be generated or an error with a more clear message should be displayed

**Comment by jonaslagoni** [comment]
Weird, let me take a look!

**Comment by jonaslagoni** [comment]
A bit of a multitude problem 😄 

1. The CLI does not yet use the newest `next` version where the AsyncAPI 2.5 version is supported, I am gonna do a PR for the CLI today.
2. We need to improve the error message in the AsyncAPI processor regardless to throw a meaningful error when a version is not supported by Modelina, I am gonna creat an issue for that.

Thanks for raising the issue!

**Comment by bintoll** [comment]
Hello! I also face this issue. Tried to just update modelina dependency in cli package to the next branch but it did not help, because got another issue. So looks like release version of cli still is not working, do you have any plans to make it working soon?

**Comment by jonaslagoni** [comment]
hey @bintoll, I do yes, just requires a few things first 🙂 

The interaction with the old parser is not great... So the progress is currently being blocked in the following order:
1. https://github.com/asyncapi/parser-js/pull/687
2. https://github.com/asyncapi/modelina/pull/1050
3. https://github.com/asyncapi/cli/pull/374

Should happen beginning of next week 👍

**Comment by jonaslagoni** [comment]
Closing as it has been fixed in other repos, do reopen if you still run into problems 🙂
