### ISSUE TITLE
additionalProperties within TS interfaces

### ISSUE THREAD

**Issue by mitjacotic** [asyncapi/modelina#959]
#### Describe the bug
When generating interfaces (instead od default classes) for typescript, `additionalProperties` are added as actual property to the interface.

For example:
```json

"Foo": {
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "foo": {
      "type": "string"
    }
  },
  "required": ["id", "foo"],
  "additionalProperties": {
    "type": "string"
  }
}
```

Produces such interface:
```ts
interface Foo {
  id: string;
  foo: string;
  additionalProperties?: Record<string, string>;
}
```

AFAIK additional property should allow for adding properties not listed in the interface, probably something like this:
```ts
interface Foo extends Record<string, string> {
  id: string;
  foo: string;
}
```

At the same time if additionalProperties is not present in the asyncapi definition for example, it is considered as if additiona properties are allowed. This probably means that interfaces should by default all extend `Record<string, any>` in absence of additionalProperties?

**Comment by jonaslagoni** [comment]
For interfaces specifically, I would probably say that's a good alternative 👍 I am not sure whether we need both options what do you think? 🤔 
-

**Comment by mitjacotic** [comment]
My proposal would be to have a flag (or preset) that would enable this. And the logic (if enabled) would be:
 - if additionalProperties is not present or not false -> extend all interfaces with `Record<string,  string|number|boolean|...>`
 - else if present then extend it with whatever interpreter returns already

**Comment by moltar** [comment]
Running into this as well.

Generating TS interfaces from [GitHub Workflow JSON Schema](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/github-workflow.json).

Getting this kind of output:

```ts
interface WorkflowTriggerEventConfigWorkflowCall {
  inputs?: OnOneOf_2WorkflowCallInputs;
  secrets?: OnOneOf_2WorkflowCallSecrets;
}

interface OnOneOf_2WorkflowCallSecrets {
  additionalProperties?: Map<string, WorkflowTriggerEventConfigWorkflowCallSecret>;
}

interface WorkflowTriggerEventConfigWorkflowCallSecret {
  description?: string;
  required: boolean;
}
```

This is wrong, because then the object would be:

```ts
const trigger: WorkflowTriggerEventConfigWorkflowCall = {
  secrets: {
	// 👇🏻 This prop wrapper is not needed
    additionalProperties: {
      foo: {
		required: true,
      }
    }
  }
}
```

Correct result should be:

```ts
interface WorkflowTriggerEventConfigWorkflowCall {
  inputs?: OnOneOf_2WorkflowCallInputs;
  secrets?: Map<string, WorkflowTriggerEventConfigWorkflowCallSecret>;
}

interface WorkflowTriggerEventConfigWorkflowCallSecret {
  description?: string;
  required: boolean;
}
```
