### ISSUE TITLE
feat: implement proper typing for OpenAPI built-in type arrays 

### ISSUE THREAD

**Issue by zaytsevand** [asyncapi/modelina#972]
#### Reason/Context
It appears that currently, any array of a [built-in type](https://swagger.io/docs/specification/data-models/data-types/) will be rendered as an array of `dynamic` type in C#.
The clearness of the generated model could be improved if the item type is explicitly typed to a C# primitive type (if such mapping exists).

#### Description
Consider the following input schema:
```typescript
    const model = await generator.generate({
      $id: 'Test',
      type: 'object',
      additionalProperties: false,
      properties: {
        array: {
          type: 'array',
          additionalProperties: false,
          items: {
            additionalProperties: false,
            type: 'number'
          }
        }
      }
    });
```
The actual output would be:
```csharp
public class Test
{
  public dynamic[]? Array { get; set; }
}
```
Desired output would be:
```csharp
public class Test
{
  public double[]? Array { get; set; }
}
```

**Comment by jonaslagoni** [comment]
The reason you get this output is because of `additionalItems` (that function just as `additionalProperties` just for arrays) 🙂 

If your use the following input instead: 
```
{
  $id: 'Test',
  type: 'object',
  additionalProperties: false,
  properties: {
    array: {
      type: 'array',
      additionalItems: true,
      items: {
        type: 'number'
      }
    }
  }
}
```

You get:

```csharp
public class Test
{
  private double[] array;

  public double[] Array 
  {
    get { return array; }
    set { array = value; }
  }
}
```

**Comment by jonaslagoni** [comment]
While this is the intended behavior, we can argue that it's not the intended output for the user that did not create the schema and `additionalItems` should be ignored if possible. 

But that deserves it's own issue I think 🙂

**Comment by zaytsevand** [comment]
I'm learning more and more about OpenAPI spec than I ever thought existed in the first place... Thanks for the clarification, much appreciated! To be honest, such a design decision looks overengineered and too complex, but I assume it has a set of use cases I'm unaware of. Anyway, it's greatly out of the scope of this work.
