### ISSUE TITLE
Java Jackson_Preset does not work for serialization and deserialization

### ISSUE THREAD

**Issue by dwlabcube** [asyncapi/modelina#983]
#### Describe the bug
Because the @Builder and @Jacksonized Annotation do not take into account the Annoation-Property on the getter Method things will fail in deserialization of the object.

#### How to Reproduce
Generated Code of a Model "TestDevice" with one Property called nameBAG.

```
      codeBAG:
          type: string
```

```
  @SpringBootTest
  public class JsonTest {
      @Autowired
      private ObjectMapper objectMapper;
  
  
      @SneakyThrows
      @Test
      public void serializatinDeserializationTest() {
          TestDevice d = TestDevice.builder().codeBag("Code123").build();
          String string = objectMapper.writeValueAsString(d);
          TestDevice newD = objectMapper.readValue(string, TestDevice.class);
  
          Assertions.assertThat(string).isEqualTo("{\"codeBAG\":\"Code123\"}"); //this works
          Assertions.assertThat(newD.getcodeBag()).isEqualTo(d.getcodeBag()); //this fails
      }
  
  
      @Builder
      @Jacksonized
      public static class TestDevice {
  
          //   @JsonProperty("codeBAG") should be put here
          private String codeBag;
  
          @JsonProperty("codeBAG")
          public String getcodeBag() {
              return this.codeBag;
          }
          public void setCodeBag(String codeBag) {
              this.codeBag = codeBag;
          }
      }
  }
```

this Test fails with:

> org.opentest4j.AssertionFailedError: 
expected: "Code123"
 but was: null
Expected :"Code123"
Actual   :null

#### Expected behavior
If you put the annotation upon the Java-Field (property) things work fine.

**Comment by jonaslagoni** [comment]
Thanks for raising the issue @dwlabcube, are you using the `next` version for generating the data models?

**Comment by artur-ciocanu** [comment]
@dwlabcube could you please try the latest `next` version. It has the Jackson fix. Thank you.

**Comment by jonaslagoni** [comment]
Closing as this should be solved in the new version.
